### ISSUE TITLE
App crashes after pressing Write - tested every release

### ISSUE THREAD

**Issue by minim8** [HiddenRamblings/TagMo#10]
Galaxy Note 3, Android 5. 
Like the title says, I tested every release of this git and it always crashes when I try to write. Even 2.32, which seem to work for some people, crashes. Can anyone help?

**Comment by shad00m** [comment]
Galaxy Note 2 Android 4.4.2 also crashes on Writing or restoring :(

**Comment by azsde** [comment]
Please try with my forked version.

**Comment by RoXuS** [comment]
@azsde do you have a released version of your fork ?

**Comment by azsde** [comment]
No, I do not have the authorization to distribute it, you'll have to compile it yourself.

**Comment by RoXuS** [comment]
Ok thx @azsde, I have the following error on your fork when I write:
```
03-09 17:47:13.924 8756-8985/? D/NfcActivity: Error
                                              java.lang.Exception: Error while writing main data (stage 1)
                                                  at com.hiddenramblings.tagmo.TagWriter.writeToTagAuto(TagWriter.java:49)
                                                  at com.hiddenramblings.tagmo.NfcActivity.onTagDiscovered(NfcActivity.java:169)
...
```

**Comment by azsde** [comment]
Are you sure your tag is blank ?

If so, can you try placing it at different positions ?

Finally, if it still doesn't work, can you try using another file explorer when loading your .bin file ?

**Comment by RoXuS** [comment]
@azsde ... Ok it's my fault, I took the only tag that looked corrupt among the 10 that I received ...

It is ok !! Thx.

Can we rewrite a tag that was written or not?

**Comment by RoXuS** [comment]
@azsde it is ok with your version !

I have tested in game and it works (I have a wolf in BOTW on switch !!!).

Thx really.

Ok ok so I have to buy several others tags because I have only 9 tags.

**Comment by zburke911** [comment]
@azsde,
This may be a stupid question but how would I go about compiling your fork?

**Comment by DarkCodedDragon** [comment]
Roxus do you have compile of Azsde work? if not I can get to it when I have time just at work received my tags and  wanted to try write one.

Thanks

**Comment by DarkCodedDragon** [comment]
I am getting this same crash with HTC M8 android 4.4.4 also tried complying AZSDE version inside of Android studio with gradle and still must be doing something wrong as I end up with 3 apks and all of them fail.

**Comment by Satin181** [comment]
@azsde 
Hey, how do I compile your fork? The default tagmo isn't working for me.

**Comment by DarkCodedDragon** [comment]
Look at comments on issue 13 Kidel goes into the steps on how to compile the fork.

**Comment by Mikeferaz** [comment]
Hello, If anyone can help Id apreciate it. I have a Xperia Z5, so far Ive tried EVER version listed here https://github.com/HiddenRambler/TagMo/releases

none has worked, the last 3 versions crash when trying to write auto my tag

the bottom 3 versions like new hope didnt crash but said  "error while writing main data (stage 1) java.io.IOException: tranceive failed﻿"

Scanning an amiibo works fine, when scanning a tag I get "transceive failed"

**Comment by suTrust** [comment]
Hello! Looking for instructions on compiling an APK... 
This page seems relevant:
https://stackoverflow.com/questions/35014071/how-can-i-compile-an-apk-from-a-github-source

**Comment by Bombastisch** [comment]
Could you check the latest version (2.5) an see if your problems are solved?

**Comment by Bombastisch** [comment]
Main topic of the issue should be fixed. If you @Mikeferaz still have a problem on the latest version, please open a new issue thread.
