### ISSUE TITLE
Can't load key files.

### ISSUE THREAD

**Issue by Crackst** [HiddenRamblings/TagMo#102]
Hello,
I'm using a Samsung Galaxy S5 and whenever I try to load in the keys I get a message saying "Error: uri". I tried different releases, it's the same issue on every version tho. I also tried different Keys, but again, same issue.
Screenshot shows the messages I'm getting on 2.3.2 and 2.6.1 (on 2.3.2 the error message pops up, on 2.6.1 theres only the grey bar on the bottom) 
![screenshot_20171127-132226](https://user-images.githubusercontent.com/34029225/33266556-5e805142-d376-11e7-8b2d-1c531f2f21e2.png)
![screenshot_20171127-132324](https://user-images.githubusercontent.com/34029225/33266557-5e9ad85a-d376-11e7-8ac1-692cbc4d5ced.png)

**Comment by Bombastisch** [comment]
Could you replicate your problem again, and then click on the 3 dots in the mainmenu and "dumb logcat" and please send the logcat.txt in this thread. Then our devs will be able to fix it

**Comment by Bombastisch** [comment]
Closed? Did it work now?

**Comment by Crackst** [comment]
It did work. I just had to use another file manager, the Samsung one caused the Problem. Thank you for your reply anyways!
