### ISSUE TITLE
Tag won't write

### ISSUE THREAD

**Issue by rupes1987** [HiddenRamblings/TagMo#110]
Im using a nexus 6p phone with the latest version of tagmo and it won't write to my nfc stickers.
Theyre ntag215 stickers.  I run the program and it sits at the writing to tag screen but doesn't do anything, just sits there.

**Comment by Bombastisch** [comment]
Do you put your tags exactly above the nfc-writer of your phone?

**Comment by rupes1987** [comment]
Wooooow.  Turns out I'm a dummy.
Didn't have it held to the right part of my phone.

Thanks!!
