### ISSUE TITLE
Cant find keys

### ISSUE THREAD

**Issue by Ndog28** [HiddenRamblings/TagMo#111]
I dont know if ive downloaded the wrong keys but its saying the key signature doesnt match im using an Lg V30 if that helps

**Comment by Bombastisch** [comment]
You probably don't have the right keys. Try to get them from another source

**Comment by Ndog28** [comment]
This is the only website for the keys right?

**Comment by Bombastisch** [comment]
The keys aren't availible on Github. You need to find them yourself somewhere else.

**Comment by Ndog28** [comment]
I still havent solved it yet been pretty busy lately lol

**Comment by Bombastisch** [comment]
The key file/s need to be obtained from somewhere else. We can't share them due to copyright issues. Your fave search engine might help^^

**Comment by Ndog28** [comment]
Oh i get it now lol i got a new phone and i forgot how to find the keys
again thanks for the help
