### ISSUE TITLE
Not detecting .bin files

### ISSUE THREAD

**Issue by JackThRipper99** [HiddenRamblings/TagMo#114]
TagMo is not detecting the .bin files I have downloaded. I am using a Samsung Galaxy S4 mini.

**Comment by Bombastisch** [comment]
Hi. Are you sure you set up TagMo correctly and loaded the keys?

**Comment by draconispax** [comment]
How do I find and load the key files?

**Comment by Bombastisch** [comment]
There is a  instruction in or github wiki: https://github.com/HiddenRamblings/TagMo/wiki/Instructions 

U have to obtain the key file from somewhere else, because we cannot share it.

**Comment by draconispax** [comment]
I was being a noob, ignore me.  I already got the files and have it working
