### ISSUE TITLE
Implement simple filebrowser to load keys

### ISSUE THREAD

**Issue by Bombastisch** [HiddenRamblings/TagMo#126]
We recently often had the issue that people couldn't load files without putting them onto Google Drive before.

This might sound like an easy workaround, but it will be an issue for some people and we will have further issue threads.

This workaround isn't the right solution.

I tried to implement a simple filebrowser based on this: http://www.christophbrill.de/how-to-create-a-android-file-browser-in-15-minutes/

But as usual, I failed.

I don't think implementing it, compared to solving the issue for users, is worth the small implementation. ;)

**Comment by AbandonedCart** [comment]
Android now handles a lot of the heavy lifting for locating files and the current UI takes care of the rest, so this appears to have been resolved. Closing this unless new information arises.
