### ISSUE TITLE
SSB Data is limited

### ISSUE THREAD

**Issue by LeafBlitz** [HiddenRamblings/TagMo#130]
Any amiibo that has a character in SSB can be used as an SSB amiibo, but only SSB series amiibo can be edited.

**Comment by Bombastisch** [comment]
I have seen that on Reddit yesterday as well. @North101 's new beta apk fixes that. But this is still underdevelopment and TagMo is a free project and the devs have to work irl as well, it takes a time until it will be ready to be merged and an official release.

**Comment by LeafBlitz** [comment]
The link you posted says the file has been removed, but thanks anyways!

**Comment by Bombastisch** [comment]
Welp. @North101 removed it then. You can still compile the .apk from the "experimental ui" branch in Android Studio and test it.

**Comment by AbandonedCart** [comment]
This has become a part of the released experimental branch. Thanks @North101 for all your hard work.
