### ISSUE TITLE
Tag was lost / Isn't working

### ISSUE THREAD

**Issue by Araraura** [HiddenRamblings/TagMo#131]
I'm using HTC 10 to try scan the nfc tags I bought from here: https://www.amazon.com/gp/product/B071KTC2J6/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

I'm trying to use TagMo and it looks like I did everything right, but when I put the sticker to the scanner I either hear a beeping noise playing again and again (probably to indicate that the scan was unsuccessful) or I'm getting a "Tag was lost" error. I tried multiple versions but nothing works.

**Comment by Bombastisch** [comment]
There seems to be a general problem with your phone: https://forum.xda-developers.com/htc-10/help/problems-scanning-writing-nfc-tags-t3592499

You could try, if other apps can write/read amiibo or NFC tags, to check if it's your phone or TagMo which is causing the issue.

**Comment by Bombastisch** [comment]
Any feedback on this? Did it work now or did you use another phone? :)

**Comment by Araraura** [comment]
I used another phone, it worked.
