### ISSUE TITLE
Amiibo file browser down with too much amiibo

### ISSUE THREAD

**Issue by Ahellina** [HiddenRamblings/TagMo#134]
I have 695 amiibo data and I use galaxy note 5

**Comment by Bombastisch** [comment]
What exactly is your problem?

**Comment by Ahellina** [comment]
After I press "Load tag" button, amiibo brower pop up then after some loading and tagmo app shut down.

**Comment by Bombastisch** [comment]
You can disable the amiibo file browser in the settings as a workaround

**Comment by Bombastisch** [comment]
Maybe your phone is running out of memory? You can change the directory it's looking for in the bar at the bottom of your screen. Maybe by narrowing down the folder you have your dumps in will circumvent the crashing.

**Comment by ErbayI** [comment]
You've probably downloaded an Amiibo collection with lots of subfolders, this is too much for tagmo, you have to put all the bin stuff in one folder after that everything should work.
Maybe my answer is too late but it could help others too and I'm sorry for my bad English knowledge, I'm German ;D
