### ISSUE TITLE
App keeps crashing when searching

### ISSUE THREAD

**Issue by JayDoofus** [HiddenRamblings/TagMo#135]
When searching I entered "ur" and before I could finish the app crashed. However the app remembers the the previous search, so it instantly crashed after rebooting. And it becomes a cycle of crashing and rebooting. Only got it to work normally again after deleting and reinstalling.

**Comment by Bombastisch** [comment]
Is it with all searches? Or just the  "ur"?

**Comment by JayDoofus** [comment]
surprisingly actually it only happens when searching "ur"!

**Comment by Bombastisch** [comment]
I can't reproduce that problem and I have never heard of that problem before. If it is the only search it crashes on, you are maybe better of searching "bosa" instead! :D
