### ISSUE TITLE
"Done" although no tag

### ISSUE THREAD

**Issue by tobiasmuecksch** [HiddenRamblings/TagMo#137]
I'm using a Samsung Galaxy J5 2017 with Android 7.0. TagMo Version 2.6.1

What I did:

1. Import keys (locked and unfixed)
2. Select an amiibo
3. Press write Tag (Without holding a tag to the phone)
4. "Done" is shown immediately

Even if I hold a NTAG215 card to the phone the behavior is the same and the card does not work.
Empty Tags are correctly recognized.

**Comment by tobiasmuecksch** [comment]
Somehow the issue disappeared. While "Done" is still shown immediately the write process is working now.

**Comment by Bombastisch** [comment]
It's a copy & paste bug in the source code, which was already fixed months ago. We just haven't had a new release yet so the "Done" still shows up.

Don't worry about it, as it actually doesn't mean anything.
