### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by KiraKaiju** [HiddenRamblings/TagMo#142]
Ok I am new I guess. I used to be able to download an APK and have the app install as if it came from the app store. Now I get a zip file and have no idea what to do with it. Yes I used google, no the read me won"t open, I just need some direction on how to get the app on my phone again. Thank you.

**Comment by Bombastisch** [comment]
https://github.com/HiddenRamblings/TagMo/releases

This is the link to the download page.
Select the latest version and download the "tagmo.apk"
