### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by agent40** [HiddenRamblings/TagMo#143]
How do I install it?? Its a zip I extract it but I can't find any apk or anything

**Comment by Liamlink9** [comment]
it works great thanx.



Am So., 6. Jan. 2019, 07:25 hat Adam Baxter <notifications@github.com>
geschrieben:

**Comment by agent40** [comment]
I downloaded the bin file for the wind waker link amiibo and placed it inside the tagmo file but I can't find it or load it

**Comment by Bombastisch** [comment]
Initial problem seems to be solved. Closing this now, any specific issues can usually be asked on the subreddit /r/amiibomb
