### ISSUE TITLE
Galaxy s9 Tag Lost

### ISSUE THREAD

**Issue by ChazPounder** [HiddenRamblings/TagMo#144]
As soon as i touch the tag to the back of the phone it says tag detected then instantly tag lost.

I have the right tags and everything and have scanned with other programmes,  any one offer some advice?

**Comment by Bombastisch** [comment]
Go to the settings and disable "Tag Verification".
Does this fix the problem?

**Comment by ChazPounder** [comment]
No it didnt, i tried that. However the battery on the phone was below 50% and as soon as i connected the phone to my PC via USB it started working. I have no idea why

**Comment by Bombastisch** [comment]
Can this be closed? Seems like a weird bug, but it works

**Comment by ChazPounder** [comment]
Yeah sorry

Please close.

I will upload bug log if it happens again

**Comment by Bombastisch** [comment]
Great! Thank you :)
