### ISSUE TITLE
PowerTag survey

### ISSUE THREAD

**Issue by ErbayI** [HiddenRamblings/TagMo#146]
I wanted to ask how it looks with the Datel PowerTag whether it works well or badly with Tagmo or
if there are big bugs, I know that this is still in the beta but wanted to ask if it is worthwhile to buy one or not. Since there are no real reports on the PowerTag with Tagmo, I wanted to ask for your experience and I thank you for your reports.
(Sorry for my bad English knowledge, I'm German ;D)

**Comment by Liamlink9** [comment]
i m german too!

Am Fr., 8. Feb. 2019, 14:02 hat ErbayI <notifications@github.com>
geschrieben:
