### ISSUE TITLE
App crashes when attempting to load tags

### ISSUE THREAD

**Issue by mmmeeggss** [HiddenRamblings/TagMo#153]
App crashes whenever I hit "load tag". Sometimes I manage to open the drop-down menu to choose a folder to search in, usually I can't make it that far. Using a Samsung S10+ on latest version of Android. 

[Logcat ](https://drive.google.com/file/d/1-CTHYB-VDqlAe3JdcNLUjxznGetoS-WC/view?usp=drivesdk)

**Comment by Bombastisch** [comment]
You can try to disable the Amiibo File Browser in the settings. Maybe that helps?

How many GBs is your storage? Maybe it's "too" much and so it crashes.

**Comment by xJam-es** [comment]
I have the same issue - it works once i disable Amiibo File Browser.

I have all my tags in /TagMo/Amiibo/ and then folders for each category.

I have 37GB free of 118GB (Pixel 2 XL 128GB version).

**Comment by AbandonedCart** [comment]
This should be solved by the new storage management methods. Please feel free to stop back if the problem wasn't solved to open this issue again.
