### ISSUE TITLE
Transceive fail tagmo 2.7.0

### ISSUE THREAD

**Issue by julia12321** [HiddenRamblings/TagMo#162]
Hi, I am trying to use tagmo 2.7.0 to write on a new NTAG215 with a samsung galaxy s4 but the transceive fail window keeps popping up. Is there a way to fix this? Thank you

**Comment by Bombastisch** [comment]
Turn off tag validation in the settings. Samsung phones can sometimes be picky.

**Comment by pemsl2** [comment]
is there another solution?
i have the same error and turning off the validation didn't fix it
any and all help is appreciated

**Comment by Bombastisch** [comment]
Do you have a phone case?
Remove it and try again.

Do other NFC apps work? Can TagMo read amiibo?

**Comment by pemsl2** [comment]
thanks for the response.

no i removed the case before attempting the transfer
yes while reading other nfc apps and tagmo work

my only guess right now is, that the cards i use are not compatibel, i ordered different ones and will try with them again

**Comment by AbandonedCart** [comment]
This issue appears resolved, but please let us know if new cards were not the solution.
