### ISSUE TITLE
Can't scan or write amiibo's

### ISSUE THREAD

**Issue by Callum-W** [HiddenRamblings/TagMo#165]
I just installed the latest version (2.7.0) of TagMo on a Samsung S9+, NFC is turner on and I have ensured the unfixed and locked keys are loaded, but I still can't scan any amiibo's.

I attempted to write to an NTAG215 card and the message "Done" appeared.  But then when trying to scan that card there is no response.  It just stays on the "Place the Tag under the Phone" screen.

Is there something I'm missing?  I assumed that maybe the cards I got were bad, but it won't even read amiibo's either.

**Comment by Bombastisch** [comment]
What happens exactly if you try to scan a real amiibo?

- Does it show up in the menu?
- Do you get stuck on the scan menu?
