### ISSUE TITLE
Tag keys won't load nor write. Keep getting errors.

### ISSUE THREAD

**Issue by ChaosQueen713** [HiddenRamblings/TagMo#166]
I had the older version and  I had the BIN files for the amiibo cards I wanted to make and it has worked before. I load the Tag and when I hit Write NFC and put the nfc card under it I get the Source UID does not match the target. I have used these before with different characters from another series and it worked perfectly. 

I updated the app to the new version and load the Amiibo key I wanted but Write tag was greyed out and it kept saying Amiibo Key not loaded. I go into settings and don't exactly know what to click so I uninstalled and Deleted everything.

What do I need to do to get these working? It scans the blank cards just fine. I do have the Samsung S9+ phone now while before I used the S7+ and prior models.

**Comment by Bombastisch** [comment]
You cannot overwrite amiibo cards.

Once they are an amiibo you can't revert it or change the amiibo type.

To load the keys, open the settings and click on the red error "keys not loaded" to open a file dialog and load the keys.

**Comment by ChaosQueen713** [comment]
I am wanting to make a card. I have blank NFC tags. I do hit the triple
dots and find a load a Tag, yet I still get the error message that one is
not loaded. The Write button is greyed on the new version so I cant. On the
older tagmo version when i hit write it scanned the blank NFC tag but gave
me the Error Code Source UID not found.

**Comment by Bombastisch** [comment]
You don't load a .bin via the three dot menu.

Just click on the violett "load tag" button and select a bin from there.

**Comment by ChaosQueen713** [comment]
Sorry I got mixed up there.
But yeah I did load the .bin file through the load tag button and I can't
Write the tag to a blank NFC. The Write button is greyed out

**Comment by Bombastisch** [comment]
It's usually only greyed out when NFC is turned off or the keys aren't loaded.

Have you loaded the keys?

**Comment by ChaosQueen713** [comment]
At the time yes.
I think I'll download it again and redownload all the keys I had and see if
it works.

**Comment by ChaosQueen713** [comment]
> It's usually only greyed out when NFC is turned off or the keys aren't loaded.
> 
> Have you loaded the keys?

I took screen shots of what I see and do on my phone. What can I do?

I keep getting this https://imgur.com/a/ri2i0Im

**Comment by Bombastisch** [comment]
It clearly shows a red error in the settings which I mentioned before.

https://i.imgur.com/9xncXlI_d.jpg

The keys are not loaded. Click on that error message and load the key(s).  It's usually a 40byte .bin file

**Comment by ChaosQueen713** [comment]
Where would I find they keys? Are they part of the tags download? I'm not
finding the bin file.

**Comment by Bombastisch** [comment]
Please read the Github readme -> requirements.

I cannot provide those.
Googling can help.

**Comment by ChaosQueen713** [comment]
Ah I thought the load keys were something different that could be. My bad.
Thank you!

**Comment by Bombastisch** [comment]
Does it work now?
Can I close the issue?

**Comment by ChaosQueen713** [comment]
Yes please! It.works.now thank you!
