### ISSUE TITLE
Samsung Galaxy S4 wont allow me to install the apk at all.

### ISSUE THREAD

**Issue by Sejha** [HiddenRamblings/TagMo#169]
Title

**Comment by Sejha** [comment]
To clarify, actually, going to the install page for the apk just results in the only option being cancel.

**Comment by Bombastisch** [comment]
You need to enable "install app from unknown sources" in your phones security settings to install TagMo, as it's not available on Google Play

**Comment by Sejha** [comment]
I am well aware of this and have the setting turned on, I simply am somehow not allowed to click install on the page. I mean its kind of obvious its not on play when Im downloading the APK directly, Ive done this before, its just THIS app that wont load.
    On Monday, March 30, 2020, 12:43:07 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


You need to enable "install app from unknown sources" in your phones security settings to install TagMo, as it's not available on Google Play

**Comment by Bombastisch** [comment]
Which Android version are is your phone on.

In the newer versions (<7.0 ?) you need to grant the permission per app. So maybe you need to give the unknown sources permission to your file explorer.

Other case could be that  you still have the older version installed.

Please uninstall it beforehand. I already put a notice in the download page.

**Comment by Sejha** [comment]
Ah that might be it, I'll see if I can change the permissions on the actual file explorer as Im using the latest version of android available to my phone.
    On Monday, March 30, 2020, 01:39:32 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


Which Android version are is your phone on.

In the newer versions (<7.0 ?) you need to grant the permission per app. So maybe you need to give the unknown sources permission to your file explorer.

Other case could be that you still have the older version installed.

Please uninstall it beforehand. I already put a notice in the download page.

**Comment by Sejha** [comment]
Alright just went in and checked and Im on android 5.0.1, model SGH I337-M
    On Monday, March 30, 2020, 01:39:32 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


Which Android version are is your phone on.

In the newer versions (<7.0 ?) you need to grant the permission per app. So maybe you need to give the unknown sources permission to your file explorer.

Other case could be that you still have the older version installed.

Please uninstall it beforehand. I already put a notice in the download page.

**Comment by Bombastisch** [comment]
Not sure when Google exactly changed that. Was just a guess.

Does it work now?

**Comment by Sejha** [comment]
I actually for some reason am not allowed to change the permissions for the my files app, and feel like there's some sort of cascade of options preventing me from installing it. I'll do some more research but this is a pain.
    On Monday, March 30, 2020, 01:52:40 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


Not sure when Google exactly changed that. Was just a guess.

Does it work now?

**Comment by Bombastisch** [comment]
One option would be to give the permisson to chrome/firefox, download TagMo again and then install the app right from the push notification.

Another option would be to give that permission to the android integrated "downloads" app and install from there.

**Comment by Sejha** [comment]
Well Im fucked, apparently I can't do this without rooting the device which Im not willing to at this time. This is beyond frustrating as it used to be easy to do it.
Why is *this* apk the only one that it doesnt work with.
    On Monday, March 30, 2020, 02:36:46 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


One option would be to give the permisson to chrome/firefox, download TagMo again and then install the app right from the push notification.

Another option would be to give that permission to the android integrated "downloads" app and install from there.

**Comment by Bombastisch** [comment]
TagMo still does not need your phone to be rooted.

I use it on my unrooted phone as well.

- Have you tried using an older version of TagMo?
- Did you check if you still have an older version of TagMo installed? You need to uninstall an older version first to install 2.7.0.

I can't replicate your problem, as TagMo is straight forward to install, your phones just needs the permission.

**Comment by Sejha** [comment]
Changing the permission is what is what I need to root for as there is no option available on my version of android and Id have to downgrade to get the option back. I have no idea why this is the way it is. 
    On Monday, March 30, 2020, 05:28:05 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


TagMo still does not need your phone to be rooted.

I use it on my unrooted phone as well.
   
   - Have you tried using an older version of TagMo?
   - Did you check if you still have an older version of TagMo installed? You need to uninstall an older version first to install 2.7.0.

I can't replicate your problem, as TagMo is straight forward to install, your phones just needs the permission.

**Comment by Bombastisch** [comment]
There are lot's of people running TagMo on a S4, i don't think you need root for it.

If you want to put further effort into this feel free to send screenshots into this thread of your phone not wanting to install TagMo.

eG. send me a screenshot of your sertting's screen showing that permission to installing unknown apps is actually set for your browser

**Comment by Sejha** [comment]
I think theres a critical reading failure going on here. I cannot set that permission. It won't allow me to access that as an option.
    On Monday, March 30, 2020, 05:47:53 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


There are lot's of people running TagMo on a S4, i don't think you need root for it.

If you want to put further effort into this feel free to send screenshots into this thread of your phone not wanting to install TagMo.

eG. send me a screenshot of your sertting's screen showing that permission to installing unknown apps is actually set for your browser

**Comment by Bombastisch** [comment]
Huh... Okay thank you for clarification.

That's still odd.
Just one more try, since all other S4s seem to be able to run TagMo.

Does your settings app have a searchbar?
Type in "unknown".
Usually you can find the correct setting really quickly that way, as that option is buried somewhere deep in the settings.

**Comment by Sejha** [comment]
It does not have a searchbar at all, Unknown Sources only shows up once anywhere and its in security and its been turned on now for a while, I even flicked it off and on again and restarted the phone to see if it was a stuck setting. Still no dice.Other nfc programs work, even the old Unsafe Amiiwrite from years ago but no such luck here. I can't quite figure it out.
    On Monday, March 30, 2020, 06:30:46 p.m. EDT, Basti <notifications@github.com> wrote:  
 
 


Huh... Okay thank you for clarification.

That's still odd.
Just one more try, since all other S4s seem to be able to run TagMo.

Does your settings app have a searchbar?
Type in "unknown".
Usually you can find the correct setting really quickly that way, as that option is buried somewhere deep in the settings.

**Comment by Bombastisch** [comment]
I sadly don't know either then...

Can you install other .apk from unknown sources?
e. g. download and install F-Droid

**Comment by Sejha** [comment]
Yeah theres no issue with other APK it seems its just this one that it wont let me do and I cant put my finger on it. I'll get back to you if I come up with anything.
    On Tuesday, March 31, 2020, 06:58:52 a.m. EDT, Basti <notifications@github.com> wrote:  
 
 


I sadly don't know either then...

Can you install other .apk from unknown sources?
e. g. download and install F-Droid

**Comment by Sejha** [comment]
FIGURED IT OUT AND I AM FUCKING LIVID
I was using twilight as a screen filter and apparently as a system level protection it will not allow you to click install when its running. I have no idea why it was only THIS app that was doing it but hey I got it fixed.
    On Tuesday, March 31, 2020, 06:58:52 a.m. EDT, Basti <notifications@github.com> wrote:  
 
 


I sadly don't know either then...

Can you install other .apk from unknown sources?
e. g. download and install F-Droid
