### ISSUE TITLE
Getting "NFC Read Error. Try Again" when using NTag215 tags on Xperia XA2 Ultra

### ISSUE THREAD

**Issue by Joelgp83** [HiddenRamblings/TagMo#175]
Not sure what I'm doing wrong, or if reading / writing tags is broken on this particular Xperia.  I did try to use NXP taginfo on some previous tags made with a previous phone of mine (that one I no longer have), also got that same error.  Figured I'd leave the error report with you guys incase this is something you can workaround.

-edited to fix some things.

**Comment by AbandonedCart** [comment]
Closing this as outdated, but please leave a comment if the issue needs to be opened again.
