### ISSUE TITLE
File Browser Failed

### ISSUE THREAD

**Issue by Eldin-Bridge** [HiddenRamblings/TagMo#182]
When I installed the app it worked for me a few days, but then it started to close every time I loaded the tags, so I decided to deactivate the file search and it worked, I think it needs a new update focused on this problem, I have a samsung galaxy A8, I would like to contribute in some way to be able to fix it and launch version 2.7.1 correcting this error, in addition to this I have had the problem that the nintendo switch doesn't detect the card as an amiibo despite having been written correctly, it has only happened to me with 2 data that I throw an error.

**Comment by Bombastisch** [comment]
Can you use Android Studio?
Compile the master2 branch and run it. Maybe switching to AndroidX helps and fixes it

**Comment by Eldin-Bridge** [comment]
I haven't used android studio but I have knowledge of arduino and PLC programming, I will try to work on this app to improve it by adding functions and correcting errors, first I will try to see what the android studio app is about and then I get to work, I suppose that the app It is based on Java, right?

**Comment by minalou** [comment]
WHY do you send your mail to me?? Fuck...

Le lun. 20 avr. 2020 à 08:52, Eldin-Bridge <notifications@github.com> a
écrit :

**Comment by Eldin-Bridge** [comment]
Hi, I don't remember sending you my email 🤔 but I apologize for any misunderstanding.

**Comment by AbandonedCart** [comment]
The methods discussed in this issue are no longer a part of the core functionality and have been completely rewritten.
