### ISSUE TITLE
master2 branch App crash due to Collections.sort

### ISSUE THREAD

**Issue by zxavier94** [HiddenRamblings/TagMo#183]
com.hiddenramblings.tagmo.BrowserAmiibosAdapter.AmiiboFilter#publishResults  Collections.sort((ArrayList<AmiiboFile>) filterResults.values, new AmiiboComparator()); 
this line code cause the App crash

**Comment by zxavier94** [comment]
android phone: redmi note 8 pro
os: android 9

**Comment by Eldin-Bridge** [comment]
In which program did you check it?

**Comment by zxavier94** [comment]
> In which program did you check it?
I download release 2.7.0 and install on my phone.When I open the app and search amiibo bin file,the app always crash.so, I pull the master2 branch to local，and use android studio build, and debug the app.Finally,I find the problem code.After I comment the code , and build the app, the app can run normally.

**Comment by Eldin-Bridge** [comment]
Excellent, if you can support that this program can improve, contact the manager to upload a review of the problems that you correct, I haven't had time for now but when I can I will try to help, all good intention thanks, if it doesn't bother you and you want to support non-profit go ahead

**Comment by zxavier94** [comment]
> Excellent, if you can support that this program can improve, contact the manager to upload a review of the problems that you correct, I haven't had time for now but when I can I will try to help, all good intention thanks, if it doesn't bother you and you want to support non-profit go ahead

Thank you!I am a gamer.These days i like Animal crossing,so I'll be glad to help others.I will try to  fix the problem tomorrow or on this saturday,then i will contact the manager and push the code.

**Comment by zxavier94** [comment]
Sorry,I have token 2 hours to try to fix the problem,but i failed.I change the way of reading the Amiibo.json file.
![QQ截图20200424215835](https://user-images.githubusercontent.com/19486599/80222291-306f8080-8679-11ea-8fd3-cc5f7f604f0c.png)
I let the app read Amiibo,json from External Files Dir,because the app can't read file from the root path,then i comment the Collections.sort code.
![QQ截图20200424215848](https://user-images.githubusercontent.com/19486599/80222523-922fea80-8679-11ea-907b-2a64adfc153a.png)
Finally,the app can run normally.I don't know why,the com.hiddenramblings.tagmo.BrowserActivity file is really complicated.

**Comment by AbandonedCart** [comment]
This should be resolved in the newest versions, but please feel free to comment back if this issue needs to be opened again.
