### ISSUE TITLE
Failed to parse amiibo info when trying to import the keys. 

### ISSUE THREAD

**Issue by SunflowersxLemonade** [HiddenRamblings/TagMo#187]
I've downloaded tagmo 2.7 and the locked and unfixed bin files. But when I go into the app and try to to import them. It says failed to parse amiibo info. I'm at a loss at what to do to fix this.

**Comment by AbandonedCart** [comment]
Make sure to sync with AmiiboAPI. That is where the app downloads Amiibo info. It will be in the app settings.
