### ISSUE TITLE
Amiibos can no longer be deleted from the cards.

### ISSUE THREAD

**Issue by Luca-g14** [HiddenRamblings/TagMo#189]
I go on allow that I can delete the amiibos from the cards.  But it just doesn't work.  😥 When I use the function on the card it says that it is done, but that is not true. The cards are still occupied with the previous amiibo.

**Comment by critterm** [comment]
This is happening for me too

**Comment by Bombastisch** [comment]
You cannot delete amiibo once they are written onto NTag215s.
Just like real amiibo they are locked once they are written.
The Readme clearly states that, but I think many just overlook that.

If you want another amiibo you need to use another tag.

**Comment by reactor-sa** [comment]
NTAG215 is not re-writable, nothing to do with the software

**Comment by Luca-g14** [comment]
but I have already deleted a card and put a new amiibo on it
