### ISSUE TITLE
can't write data

### ISSUE THREAD

**Issue by iamapie13** [HiddenRamblings/TagMo#19]
I scanned my Link amiibo, but when I click "WRITE TAG (AUTO)" or "WRITE TAG (RAW)" keeps giving me an error message

**Comment by DarkCodedDragon** [comment]
What error is it giving

**Comment by genekri7** [comment]
Same

**Comment by Bombastisch** [comment]
You can't write completly new data on a existing amiibo. 

If you want to create your own amiibo, you have to buy blank NTAG215s.

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
