### ISSUE TITLE
Key file signature

### ISSUE THREAD

**Issue by cocoloco432** [HiddenRamblings/TagMo#192]
Tagmo, key file signature does not match

I've downloaded Tagmo version 2.7.0, uninstalled and tried both 2.6.1 and 2.6.0 but every time I try to load the downloaded .bin files on my phone (Pixel 3 XL) the error says "Key file signature does not match". I have tried moving the bin files from my download folder to a system folder with no luck. Can anyone offer advice please?

Disabling amiibo file browser also changes nothing. Thank you for your time.

**Comment by Bombastisch** [comment]
You need to load the correct encryption keys
