### ISSUE TITLE
transceive failed

### ISSUE THREAD

**Issue by stephen12x** [HiddenRamblings/TagMo#194]
Hi, I have a samsung galaxy note 3 and I have the Tagmo app working and everything but when I try to write a tag it immediately says transceive failed. I’ve tried two different kinds of NTAG15 cards and neither of them work so I think it’s an issue with my phone, idk where to go from here so if anyone has any ideas please let me know, thank u.

**Comment by AbandonedCart** [comment]
There were a few reports of similar issues, so it is hard to say. Have you tried the newest release to see if this is still an issue?
