### ISSUE TITLE
Tagmo Not reading Tags

### ISSUE THREAD

**Issue by peachespeachy** [HiddenRamblings/TagMo#196]
I’ve got older locked and unfixed bins. when i go to put my tag under my phone for the reader to read it it comes up with “done” but keeps asking for my to out the tag under the reader? super confused not sure what to do, ive tried 2 different bin files and tags and it was the same thing.

**Comment by lennydvette** [comment]
I had this same issue just now on my S9+.. After struggling with it for a bit I ended up turning off Android Beam under NFC settings and it started recognizing tags immediately after that..

**Comment by Bombastisch** [comment]
Did that work @peachespeachy?

**Comment by Agent-Lol** [comment]
E
