### ISSUE TITLE
When you click load tag it just crashes and goes back to the front screen

### ISSUE THREAD

**Issue by lizziem25** [HiddenRamblings/TagMo#197]
Please can someone help me ASAP every time I click load tag it just crashes and goes back to the front screen. Tried rebooting the phone

**Comment by LeVraiRoiDHyrule** [comment]
I've got the same issue here. Redmi Note 8T with Havoc OS 3.5, Tagmo latest version installed. When trying to load bin tags, Tagmo just crashes.

**Comment by Bombastisch** [comment]
Probably related to #183.

I will look into it... can't promise to fix it soon

**Comment by reylas81** [comment]
I am having the same issue since yesterday.

I upgraded my phone from a Samsung S9+ to the new S20+ 5G... it worked until I had a System Update this morning...

**Comment by skizdidlyidler** [comment]
This started happening to me after adding the SSB Ultimate amiibo folder last fall (2019). I was still using an older version at the time which prompted me to look for an update. But the newer 2.6.1 was also doing the same thing. The only fix I have found is to disable the internal file viewer "Enable Amiibo File Browser" in the settings, which is very unfortunate, as I much prefer the UI of the Amiibo File Browser.

**Comment by reylas81** [comment]
Disabling the TagMo amiibo browser fixed the issue for me!
