### ISSUE TITLE
"View hex" Question

### ISSUE THREAD

**Issue by vladdnikolic** [HiddenRamblings/TagMo#198]
In the"View Hex" screen, different regions of the hex are color coded. What do these colors mean?

**Comment by HiddenRambler** [comment]
Each color highlights the kind of data stored in that location. Mostly useful when debugging why a tag has wrong data or to help identify a new tag.

https://github.com/HiddenRamblings/TagMo/blob/189f162bf3e22a58ecda7490f379c1e4e5e04394/app/src/main/java/com/hiddenramblings/tagmo/HexViewerActivity.java#L38
