### ISSUE TITLE
Stuck on scan tag after flashing Lineage OS 17 on the Samsung Galaxys S9

### ISSUE THREAD

**Issue by tony052034** [HiddenRamblings/TagMo#199]
Hi, I was trying to scan the NFC tag after I flash Lineage OS 17, But eventually just stuck on the scan tag won't return anything......is there any way to fix this issue?

**Comment by tony052034** [comment]
Please can someone help me? Thank you

**Comment by Bombastisch** [comment]
Do other NFC apps work? Like scanning an existing amiibo with NXP taginfo

**Comment by tony052034** [comment]
Hi, I didin't try it yet, but i use NFC Tool app to try to scan an existing amiibo it didn't work

**Comment by Bombastisch** [comment]
Try TagMo

**Comment by tony052034** [comment]
Tagmo didn't work either...

**Comment by Bombastisch** [comment]
Update your Lineage maybe NFC was broken somehow in that release.

**Comment by AbandonedCart** [comment]
Closing this as outdated, but please leave a comment if the issue needs to be opened again.
