### ISSUE TITLE
I cannot restore tag

### ISSUE THREAD

**Issue by LocusAmoenus2** [HiddenRamblings/TagMo#201]
hello,
I used my ntag 215 to write an animal crossing amiibo on but I cannot restore a tag to another amiibo even if I allow "restore to different tag" . it says "done" but the old amiibo keeps being here 
Anyone could help me ?

**Comment by Bombastisch** [comment]
https://github.com/HiddenRamblings/TagMo/wiki/Limitations & Requirements

**Comment by Bombastisch** [comment]
The restore option is a not perfecetly named button. It does not do what you think it does.

Amiibo are permanent once written.
