### ISSUE TITLE
TagMo Won't Load Tags

### ISSUE THREAD

**Issue by butterybuffalobutt** [HiddenRamblings/TagMo#208]
Hello, I've downloaded TagMe, downloaded the .bin files, and enabled every single setting I could possibly need for this project, but when I click "load tags" it tells me No Amiibos Found. Then at the bottom it has a gray bar with a folder that says /Download.
Help! What am I doing wrong? Thanks!

**Comment by Bombastisch** [comment]
You need to navigate to the correct folder where you saved your bin files.

**Comment by butterybuffalobutt** [comment]
So I got it to work. I think I may have forgotten to extract the .bin files properly. Thank you for your time!
