### ISSUE TITLE
Unable to import keys

### ISSUE THREAD

**Issue by hujan4701** [HiddenRamblings/TagMo#209]
I downloaded from the two .bin files from the correct sources. Previously when I used them it unlocked the keys perfectly fine but my NFC tags were fake. This time the keys won't unlock at all despite using the same files
<img width="467" alt="Screenshot 2020-06-24 at 1 15 42 PM" src="https://user-images.githubusercontent.com/67357771/85503693-d0676d00-b61c-11ea-8d8d-396cfc343187.png">

**Comment by Straahl** [comment]
I had this trouble. I get the files from my older phone who was crypted.
get new files from the net, it will work
