### ISSUE TITLE
Deleting Tags

### ISSUE THREAD

**Issue by WeeWigglyWoo** [HiddenRamblings/TagMo#211]
There should be an option to delete tags because I accidentally downloaded loads of duplicate tags that are mixed with the amiibos I already had that were the same character. I tried deleting them through my files but I couldn't and trust me, I tried for almost a solid hour. Until there's an option to delete tags, TagMo is almost useless to me now, destroying any chance of me editing amiibos and getting new ones.

**Comment by omfgnuts** [comment]
bruh, just reinstall the app

**Comment by Bombastisch** [comment]
Deleting them through your file manager should work. I don't know your exact problem. You can always still reinstall the app or clear the cache if that's an issue.
