### ISSUE TITLE
I specially registered to ask questions 特意来问问题

### ISSUE THREAD

**Issue by geter44** [HiddenRamblings/TagMo#222]
你好，特意注册来问问题的。我用的是老手机佳域S3高配版（Jiayu S3 Plus [MT6753] ）。
为什么tagme2.7 261 260 252不支持，2.3却支持写白卡(ntag215)，其他tagmo版本没测试。就是越新版本就不支持，老版本却可以。不能出个全兼容的app吗。

Hello, I specially registered to ask questions. I use Jiayu S3 plus [mt6753] of my old mobile phone.
Why does tagme 2.7 261 260 252 not support it, but 2.3 supports writing white cards (ntag215). Other versions of tagmo are not tested. The new version doesn't support it, but the old version can.
Can't a fully compatible app come out.

**Comment by AbandonedCart** [comment]
Check with the experimental branch. It has added compatibility for newer and older devices.
