### ISSUE TITLE
Bin files in tagmo folder, still not loading tag

### ISSUE THREAD

**Issue by honeydewisland** [HiddenRamblings/TagMo#223]
I have multiple .bin files in the tagmo folder, yet when I go to load tag, it only shows one bin file I DO NOT HAVE ANYWHERE ON MY PHONE. 
Any help would be appreciated.

**Comment by AbandonedCart** [comment]
Storage in older (and newer) devices has been addressed. Please let us know if the issue comes back so this can be opened again.
