### ISSUE TITLE
Reuse TAG with password

### ISSUE THREAD

**Issue by Leproide** [HiddenRamblings/TagMo#225]
Hi!
I think we can reuse the tag with this tool:
https://github.com/nfctoys/nfctoys

Here you can read how retrieve the amibo nfc password:
https://nfc.toys/workflow-ami.html

Anyone have tried?

**Comment by HiddenRambler** [comment]
Every tag either legitimate figurines or ones created with TagMo has to two types of data pages.

1) Readonly - containg the meta data of the tag (type of figure etc)
2) Writable - containing the game specific data (which is what is saved by SSB etc).

I believe the article is talking about the 2nd type of data pages. AFAIK i know of no way of updating a tag once the readonly pages are locked unless we are talking about special tags like PowerTags or similar ones.
