### ISSUE TITLE
Galaxy Note 4, won't find the Locked and Unfixed .bin files (and can't navigate fylesystem)

### ISSUE THREAD

**Issue by OmegaXavier** [HiddenRamblings/TagMo#226]
That's about it, on Galaxy Note 4 I placed the key files on TagMo Folder and won't detect, copied to Downloads (a very commong folder) and it wont find it.

Furthermore, I can't freely navigate the filesystem to go to the precise folder the files are on.

Thanks for addressing this issue.

KEEP UP THE GOOD WORK GUYS!

**Comment by AbandonedCart** [comment]
This is being fixed. Progress is currently hosted on the experimental branch.
