### ISSUE TITLE
Large amounts of tags crash the application

### ISSUE THREAD

**Issue by witcheslive** [HiddenRamblings/TagMo#230]
I downloaded a large archive of tags that would cause the application to crash even upon launch after using the Amiibo File Browser that necessitated me deleting my data and starting over. There is no error message, the app just quits back to the home screen.

I am able to use the app if I disable the Amiibo File Browser, but it would be nice to be able to use that with a large collection!

I am using a Samsung Note 20.

**Comment by kaivar** [comment]
I have the same issue. It doesn't crash, but rather just goes back to the main screen instead of home screen. Pixel 3a on 11.

**Comment by kaivar** [comment]
Yep, that was it. Awesome, thank you!
