### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MichelD34** [HiddenRamblings/TagMo#231]
Attemp to invoke virtual metod 'short Android.os.bundle.getShort(java.lang.string)' on a null object reference

**Comment by gabixkawaii** [comment]
Everytime i click on "load tag" the app keeps closing ;-;

**Comment by AbandonedCart** [comment]
This should be resolved in the newest experimental build. Please feel free to comment if this needs to be opened again.

**Comment by EndahCookieh** [comment]
I have a simmilar issue null object
