### ISSUE TITLE
Transceive Failed, Tag was lost

### ISSUE THREAD

**Issue by WolfWyrm** [HiddenRamblings/TagMo#232]
New to Tagmo, this is my first attempt trying to write Animal Crossing amiibos. I'm currently using [these cards from Amazon](https://www.amazon.ca/gp/product/B08P2C92WD/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1). I'm using a Google Pixel4a, each write attempt gives me java.io.IOExeption: transeive failed or Tag was lost HOWEVER, when I then scan the tag with Tagmo, it correctly detects the amiibo, but in-game, it fails to read the cards and gives me "That's... not an amiibo. Please use an Animal Crossing character's amiibo."

I've turned off tag validation with no change. I can attach logcat if need be.

Edit: It's a 2.7 issue specifically, I was able to successfully write with 2.6.1 perfectly fine.

Edit 2: Despite the unsuccessful writes and TagMo reading them as not blank, I was able to re-write them using 2.6.1!

**Comment by AbandonedCart** [comment]
Is this still an issue with the newest experimental build?

**Comment by WolfWyrm** [comment]
Unfortunately I don't have any tags left to test or I'd gladly give it a shot!

**Comment by AbandonedCart** [comment]
Closing this for now, but it can be opened again if you come across the same issue.
