### ISSUE TITLE
Mi9 keyfile signature does not match

### ISSUE THREAD

**Issue by Nvffsed** [HiddenRamblings/TagMo#235]
Tagmo wont let me write or load bin files on my tags no matter what the bin file i select i keep getting the same error message and the write option is greyed out. Anybody with a solution?

**Comment by RollieGiraffe** [comment]
It's doing the same thing for me, any news on this?

**Comment by Nvffsed** [comment]
Yes you have to download the unfixed key and locked key bin files and it
works fine after that

Le mar. 18 mai 2021 à 03:59, RollieGiraffe ***@***.***> a
écrit :
