### ISSUE TITLE
Crashes when attempting to Write

### ISSUE THREAD

**Issue by genekri7** [HiddenRamblings/TagMo#24]
Using S7Edge android v6.0.1 tried 2.3.3 and 2.3.4 apks.

Anyone else similar or know a fix?

**Comment by LordFrz** [comment]
Same issue on the S7Edge, unable to write.

**Comment by LordFrz** [comment]
IT seems to be an issue with the S7Edge, as my old axiom works, but not my new S7.

**Comment by theDevelopper** [comment]
Not working on Pixel as well. Tried 2.3.4 beta as well. Simply crashes

**Comment by DarkCodedDragon** [comment]
See issue 13

**Comment by LordFrz** [comment]
azsde's branch while not crashing, still gives an error.

**Comment by Mikeferaz** [comment]
Hello, If anyone can help Id apreciate it. I have a Xperia Z5, so far Ive tried EVER version listed here https://github.com/HiddenRambler/TagMo/releases

none has worked, the last 3 versions crash when trying to write auto my tag

the bottom 3 versions like new hope didnt crash but said  "error while writing main data (stage 1) java.io.IOException: tranceive failed﻿"

Scanning an amiibo works fine, when scanning a tag I get "transceive failed"

**Comment by johnaho** [comment]
@Mikeferaz Have you tried version 2.3.1?  I have a sony xperia Z3v and it worked with that version.  I selected 'Allow Restore to different tag' and used Write-Auto.   

I also couldn't get any of the releases newer than 2.3.1 to work writing tags.

**Comment by Mikeferaz** [comment]
@johnaho ibe tried every release in the link I outted in my comment ,  2.3.1 is the one that sais permisison strikes back lol, but no ot dodnt work, perhaps your version is diferent? If you still have the Apk fule roaming in your smarthphone can you send ir to me? Ans the keys too? maybe a long shot bur who knows, ive tried everything

**Comment by johnaho** [comment]
@Mikeferaz Well, I just used the files ending in *.apk   Unless you want to compile your own version of this application you don't need the source code zips.

I just used the 2.3.1 release listed on the page.

I can't send you the keys, that is something you have to find yourself. When you do have the keys loaded it will display "Unfixed key OK and Locked key OK" on the upper left side of the screen. 

Technique wise, I put my sticker tag down and when I was ready to write I put the phone down on the tag and moved it slowly until it recognized the tag and when it was finished it said "done" and went back to the main menu screen.

**Comment by Mikeferaz** [comment]
@johnaho  I just tried with the sticker laid down like you said, still the same prolem, also Im using 2.3.1, I do have the keys ON (green) however I asked if I could use your files because Im not really a programer nor anything close, and at this point Im just trying with everything I find. I still got the same error stage 1 message, so far nothing, what could I be posiblely doing wrong, for everyone in youtube works like a charm!

**Comment by raindog14** [comment]
being unable to make the edits and compile, I went and installed the 2.3.1 and after crashing on my xperia m4 aqua on lollipop using the first 3, that one worked (pressed button to write, no crash, put on tag, it wrote!)

**Comment by scottjl** [comment]
Ditto for me, LG V20 (LG-H918) running Android 7.0.

Going back to 2.3.1 works for me. I can read and write, but the "Edit SSB Data" option will crash on a .bin, works on a real Amiibo.

**Comment by vallieres** [comment]
Pixel XL, crashing on 2.3.4b and 2.3.3 but 2.3.2 works. Names of scans are wrong though.

**Comment by quantumfizix** [comment]
@vallieres Are you trying to load and write newer amiibos? The library currently isn't complete, so you may see a generic load profile, even though the amiibo is the correct code.  The library was built out more in 2.3.4+

**Comment by vallieres** [comment]
@quantumfizix old and new. Makes no difference, I get the app stopped working and the NFC card is useless. I did notice the weird names so I think I might just fork the repo and cherry pick the commits that refer to the up to date library.

**Comment by quantumfizix** [comment]
@vallieres I am working on a Samsung Galaxy S4, and on version 2.3.2, and most of the tags I populate come back as Mario (with the correct type).  Didn't know if it was the same issue that I was working with.

**Comment by vallieres** [comment]
@quantumfizix Yes, the name is wrong.  Like Mario (LOZ) for Zelda amiibos and I think this is expected since 2.3.2 has an incomplete library. But the tag written to the NFC card is valid.

**Comment by quantumfizix** [comment]
@vallieres sounds like we are experiencing the same issue then.

I'm trying to work on the code to separate the hashlists into an XML and allow just that to be updated, so you don't need to get a new version of the code every time, just the updated XML.  Will try to commit if I get it working.

**Comment by zshaheen** [comment]
2.3.2 works on my S7 Edge SM-G935T. I'm on 7.0.

**Comment by Bombastisch** [comment]
Try the newest release. Your problems should be fixed.

**Comment by scottjl** [comment]
Tried to install 2.5 but my phone keeps telling me that the apk is corrupt. I was able to install 2.4.3 successfully though.

**Comment by HiddenRambler** [comment]
@scottjl  can you uninstall the old version and install the latest? that worked for another user.

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
