### ISSUE TITLE
Project Abandoned - See Details

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#248]
https://github.com/8BitDream/TagMo has continued this project. 

Please feel free to direct issues to https://github.com/8BitDream/TagMo/issues to have them reviewed.

> I understand the original author and contributors may no longer wish to maintain the project, which is why I am requesting push access. 
> 
> I have merged many of the changes that received a positive response to my own fork, along with updating for both older and newer Android. I have converted most of the application to allow translation and would be more than willing to manage integrating it.
> 
> I can easily branch off these changes to avoid replacing any current checkpoints. This is strictly for the benefit of the user, as I feel the current statements about the project still working no longer apply to a large portion of the remaining community.
> 
> I also understand that this project may no longer be tracked by anyone with the proper permissions to grant this request. I will continue to submit my changes to the PR for the next 72 hours before converting this issue and the PR into a redirect. I will retain any and all credit to the original contributors and will gladly respect any requests by the original authors to discontinue any or all actions.
> 
> Thank you

**Comment by HiddenRambler** [comment]
@AbandonedCart It's true i currently lack the time to maintain this project. Would you like commit acccess to this project?

**Comment by AbandonedCart** [comment]
That's up to you. I'm not sure the automated signing will port over to this repository without a key being set up, but that isn't significant compared to the progress.

**Comment by HiddenRambler** [comment]
I have sent an invite please double check and let me know if it's working. (It's been a while since i've dealt with github permissions)

**Comment by AbandonedCart** [comment]
It worked. I am closing down the notices and moving the updated code to a new local branch. Thanks
