### ISSUE TITLE
Error while writing main data (stage 1)

### ISSUE THREAD

**Issue by LordFrz** [HiddenRamblings/TagMo#25]
I am getting an error saying tag was lost, any idea on what I am doing wrong?

**Comment by LordFrz** [comment]
Was able to run it on my old Samsung Axiom, must be an issue with new version of android or the S7 Edge.

**Comment by Zuryan** [comment]
I had the same error on my Galaxy S5 SM-G911F Android 6.0.1

**Comment by demalmar** [comment]
Same here, Note 4, Android 5.1.1. I can't re-write a written card. Any help on this?

**Comment by LordFrz** [comment]
@demalmar I don't think you can rewrite a written card. Not with this program anyway, as it's for amiibo which can NOT be overwritten.

**Comment by Bombastisch** [comment]
Could you descrbe your problem more specific?   Did you want to write on a already existing amiibo or did you uave blank Ntag215s?

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
