### ISSUE TITLE
Display active bank (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#262]
Active bank should appear on initial scan
Active bank should be selected when performing actions without selecting a new item

**Comment by AbandonedCart** [comment]
The long press menu is actually identical to the N2 Elite app, so it should (theoretically) be second nature to people replacing that app with this one. The three dot menu is for the browser, which would end up being confused as deleting a bin file.

A lot of the navigation stuff can just as easily be explained in a first-run tour. If the entire thing is to be explained as navigation happens, the UI with become so bogged down with explanations that it will be tedious to use.

**Comment by burndive** [comment]
With 07b6d84:
The active Bank is highlighted in green, but so are several other banks.
![Screenshot_20211021-181847_TagMo](https://user-images.githubusercontent.com/19560779/138377990-cd9df198-cd56-4efb-acae-0905a5d71db3.jpg)
