### ISSUE TITLE
N2 - Set bank count (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#263]
Bank count should change when writing to hardware
Bank count should be reflected in list of items
Bank count menu should be visible over other lists when opening the appropriate menu

**Comment by AbandonedCart** [comment]
The highest would make more sense, since it "drops the value to meet the new max" but N2 probably figured it would be easier to set it as one. You still potentially end up setting a blank slot, either way. As it stands, the N2 fails to populate the list if the active slot is set as a blank. The official app handles this fine, but that's because it doesn't use half the data on the physical unit. It's all cached copies and placeholders.

**Comment by burndive** [comment]
With 77fe5bc:
Attempting to set bank count lower than active bank shows message: "Active bank beyond new count!"

**Comment by AbandonedCart** [comment]
You only need to post an issue once in the feature it best fits. It still ends up in the same pile eventually.

**Comment by AbandonedCart** [comment]
Seems the unit is wired to reset the active bank to the first when performing certain actions. Until recently, the active bank was being written with almost any action.

**Comment by burndive** [comment]
With 4860c5b:
TESTED SUCCESSFULLY: Bank count should change when writing to hardware
TESTED SUCCESSFULLY: Bank count should be reflected in list of items
TESTED SUCCESSFULLY: Bank count menu should be visible over other lists when opening the appropriate menu

"Bank # Active, # Banks Enabled" now updates correctly after Activate and Write Bank Count operations.
