### ISSUE TITLE
N2 - View hardware info (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#264]
Hardware ID should appear in the bottom menu on initial scan
Hardware ID should populate in settings after a scan is completed
Hardware ID should remain visible in settings when disabling support until it is replaced

**Comment by burndive** [comment]
Hardware ID appears in the bottom of the menu after initial scan (though it is too long to fit, and an ellipsis "..." is used in the middle--this is probably fine, given it's available in Settings).
Hardware ID appears in Settings after scan (full ID displayed)
Hardware ID disappears when Enable N2 Support is deselected in Settings, but reappears as before when re-enabled.
