### ISSUE TITLE
View all banks (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#265]
List should populate when scanning hardware
List should include all banks up to bank count
List should include slot number for each item
Blank slots should appear in the list and be identified as blank slots
Each item should be clickable, with the image opening the image page and the item opening the Amiibo page

**Comment by burndive** [comment]
Testing with a9090b1:
List populates when scanning hardware
List includes all banks up to bank count (including blank banks)
List includes slot number for each item
Blanks appear on list and are identified as such
Each *populated* item is clickable, with the image showing a larger version of the image, and the data opening up a mini-window as if an individual amiibo was just scanned.

Blanks do not respond to clicking on the image (this is fine)
Issue:
Clicking on item area of blank entry immediately crashes TagMo app.
