### ISSUE TITLE
Write a single bank (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#266]
Selecting an Amiibo from the browser should allow writing to the N2
Writing should support selecting the target bank
Write should complete and be reflected in future scans of the full collection

**Comment by burndive** [comment]
Selecting an amiibo from browser allows writing to N2 Elite
Writing allows the user to a bank, with the active bank selected by default
Writing completes, and is reflected in future scans of full collection

Issues:
Writing interface allows access to all slots, including slots above bank count.
Writing interface does not show user what is in the slots, including the slot being overwritten, potentially resulting in accidentally overwriting data.

**Comment by burndive** [comment]
With 77fe5bc:
With Bank count set at 85, I can select to write in slots 1 - 86 (an improvement from 1 - 20, but still not quite there).

**Comment by AbandonedCart** [comment]
Slot 1 is actually slot 0. Slot 86 is the 85th slot. Fixing the UI means you always have one less slot than you wanted.

**Comment by AbandonedCart** [comment]
I don't think you understand the problem, but the bank count and active bank use a different index. Correcting for that index so slot 0 is labeled slot 1 (as previously demanded) means slot 85 is slot 86. Again, you will always lose 1 slot to make the UI right if setting a count of 85 has slot numbers that stop at 85.

**Comment by burndive** [comment]
I understand how zero-based array indexing works.  Under the covers, if I set the Bank Count to 85 in the GUI, I will have access to slots indexed 0 - 84 (85 slots in total).  When I go to write, I am presented with a selection of slots 1 - 86 in the GUI (which correspond to slots 0 - 85 under the covers).  

That's still one extra slot.  If I selected slot 86 in the GUI, I would be accessing slot with a zero-based index of 85, which is out of the range of slots indexed 0 - 84.

**Comment by burndive** [comment]
![Screenshot_20211020-165709_TagMo](https://user-images.githubusercontent.com/19560779/138188286-129e0453-de01-479e-bbd9-9f4c5f58f049.jpg)
Here's a screenshot of the Write interface after I set my Bank Count to 200.

I should never have access to slot 201. It doesn't exist.

**Comment by AbandonedCart** [comment]
It does. It's the 200th slot.

**Comment by AbandonedCart** [comment]
No, slot 0 is the first slot.

**Comment by burndive** [comment]
Okay, 
Slot 0 is the 1st slot
Slot 1 is the 2nd slot
Slot 2 is the 3rd slot
...
Slot 198 is the 199th slot
Slot 199 is the 200th slot

Slot 200 doesn't exist.

**Comment by AbandonedCart** [comment]
Sure?

**Comment by AbandonedCart** [comment]
<img width="513" alt="Screen Shot 2021-10-20 at 8 11 40 PM" src="https://user-images.githubusercontent.com/1173913/138189233-698e6fdb-1000-46e2-8db8-a6a6e7d78316.png">

**Comment by AbandonedCart** [comment]
Letting the bank count limit the max was actually pushing the visible number 1 past where the limit should stop it. In the UI, you aren't supposed to see that slot 200 is slot 201 and only in the write scan dialog would it be possible to select it, but other checks should have killed the process before it would attempt to write. It's all part of the offset for the slots. The UI has to keep correcting the displayed numbers regardless of what's actually happening.

**Comment by burndive** [comment]
You have an off-by one error in your logic somewhere.  I just set my Active bank to the first bank, and then tried to set my Bank Count to 1.  It wouldn't let me.  It did let me set it to 2.

After that, I went to write an amiibo, and it listed numbers 1, 2, 3 as options for writing.

Clearly, if I have 2 banks, I should be able to write to only banks 1 or 2 (slots 0 or 1), not banks 1 - 3.

You have the hardware.  You can repeat these tests I'm doing.

With the N2 Elite app, I set the Bank Count to 1.  The TagMo app correctly displayed this.  When I went to write, it gave me the option to write to banks 1 or 2.
