### ISSUE TITLE
Clear / delete bank (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#267]
Long pressing an item should open a context menu that includes delete
Delete should remove the Amiibo from the hardware after the changes are scanned
Removed Amiibo should be reflected in the list

**Comment by burndive** [comment]
Clicking (or long-pressing) on a blank slot should provide a way to select a bin file to populate that slot with.  Currently if I have a blank slot, I have to exit the list, go find a bin I want, and then remember what the slot number was I was trying to populate.

**Comment by burndive** [comment]
Another random UI issue: pulling down on the list of slots causes a spinner to appear (as if it's refreshing).  Does this do anything (like refresh the images being displayed)?
