### ISSUE TITLE
Set current bank (Verified)

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#271]
Active bank should be configurable by long-clicking a slot
Active bank should remain selected when performing other actions
Active bank should not exceed the current bank count without notifying the user of a possible conflict

**Comment by burndive** [comment]
Selecting "Activate Bank" and scanning N2 Elite device successfully activates the selected bank.
Activating a bank makes this bank default for performing other actions (e.g., Write).
Scanning in TagMo, then using N2 Elite app to lower bank count, then attempting to activate a bank above the new bank count results in message: "Selected bank exceeds count!"

Issues:
- After activating a new bank, the GUI display of active bank (after expanding bottom panel where you set Bank Count) still displays the old bank in "Bank # Active, # Banks Enabled" until re-scan.
- There is no visual indication in the list of which bank is active.  There used to be a brief pop-up "Bank # Active" message, but that no longer appears.  The N2 Elite app shows the active bank with a different colored background.
- Activating a Blank bank results in "Error getting data. Possibly not a NTAG215", that is only fixable using the N2 Elite app to select another bank.

**Comment by AbandonedCart** [comment]
It's still not something that has any universal solution. Every solution sucks.
