### ISSUE TITLE
Display/Search by Mii name and Nickname for each amiibo

### ISSUE THREAD

**Issue by burndive** [HiddenRamblings/TagMo#276]
In the amiibo list, display Mii Name and Nickname fields, if they are present.

Add the ability to search and sort by these attributes.

Note: make sure we are interpreting Mii name field correctly.  See #275

**Comment by AbandonedCart** [comment]
Amiibo name, ID, release dates, format, and game details are definitive. The reason these are searchable and sortable is that they will exist for every Amiibo. When adding in "missing" files, the only variant is that the path no longer exists. Every file has a path and every missing item does not.

In the larger scope, these values are also cross-referenced to known Amiibo details in APIs and in manufacturer records. They are, for all intents and purposes, hardcoded to the specific Amiibo. While the filter and search APIs can handle missing values, the premise is that most files are relevant.

Given enough Amiibo with relevant data, that leaves alphabetical sorting and searching for a specific value. When it comes down to it, nicknaming one Wario "fat guy" is just as easily located by searching Wario. As for the specific Wario, it is limited to a selection that will never really exceed 10 results. That is easily manageable.

Putting aside the questionable origins of the items, there simply isn't justified reason to redesign the UI, sort, and search to promote these items to the main screen.
