### ISSUE TITLE
N2: Selected bank exceeds count

### ISSUE THREAD

**Issue by ishtangli** [HiddenRamblings/TagMo#300]
Keep getting this error. I've already set bank count to 1 and set active to bank 1 using official app.

**Comment by AbandonedCart** [comment]
I finally tracked down the specific cause of this one. In all of the confusion between the positions being zero-based and pickers starting with 1, there were one or two processes that were reversed. The actual writing to the N2 and viewing from the UI worked, but the comparison was adding the 1 on the wrong side. I finally moved everything into the picker itself, which should prevent any future confusion with that.
