### ISSUE TITLE
IT Shows only 2/780 bins

### ISSUE THREAD

**Issue by Ericzion1999** [HiddenRamblings/TagMo#307]
I have the newest Version ,ef302f1, And It shows only 2 Bins , (i have all bin's) []()![Screenshot_2021-10-30-19-28-54-461_com.hiddenramblings.tagmo.jpg](https://user-images.githubusercontent.com/82835573/139543212-6bc0c354-82e5-4dbe-928f-3b78f82bd8b2.jpg)

**Comment by Ericzion1999** [comment]
I have tagmo deleted and then i have Install it and it Show all 780 bin's

**Comment by AbandonedCart** [comment]
It was a bug on experimental only. Attempting to pull files by mimetype to speed up loading didn't work. It's been removed.
