### ISSUE TITLE
Cannot Click on files when browsing from TagMo app.

### ISSUE THREAD

**Issue by codymitch16** [HiddenRamblings/TagMo#310]
when I click the import keys button, it takes me to my file locations as it should, and I am able to see the files I need, but they are grayed out in all file locations and I can't tap/click them at all!
![Screenshot_20211101-002023_TagMo](https://user-images.githubusercontent.com/93504906/139621246-6aed0bb6-2baf-4c96-a011-7488b784a7ec.jpg)
![Screenshot_20211101-001945_Files](https://user-images.githubusercontent.com/93504906/139621252-80576cb0-f5c8-4614-bc06-9bcb97751057.jpg)

**Comment by Ericzion1999** [comment]
Hy , where did you Download the Keys?

**Comment by AbandonedCart** [comment]
See if https://github.com/HiddenRamblings/TagMo/commit/cf48b397005f1ba51030138a77cc6ed996c39eeb fixes the issue. If not, we can remove the mimetype helper altogether. It's supposed to help locate the files, not prevent picking them.

**Comment by AbandonedCart** [comment]
Closing this unless a new report comes in about it.

**Comment by greed77** [comment]
Confirming issue is still in  80da530. Android 12, Pixel 6.
![Screenshot_20211106-093849](https://user-images.githubusercontent.com/865116/140612165-fc93888a-8120-4c4b-a130-be897807acb7.png)
Unable to select keys from local folder.

**Comment by greed77** [comment]
Another interesting thing that I discovered when I was testing, I think I'm able to delete the file from my download folder and then load into tagmo from the trash.

**Comment by Ericzion1999** [comment]
Try the Keys from here: [locked_secret](https://drive.google.com/file/d/1j6y1xuccbf3DnNaTs5pw_bYDl6kZvZBD/view?usp=drivesdk)

And 
[Unfixed_info](https://drive.google.com/file/d/1HJ3TiMyW1TBjApjH-b74EgTP906bVpW0/view?usp=drivesdk)

**Comment by AbandonedCart** [comment]
Seems the mimetype detection may be broken with certain files. I'll have to test with the "approved locations" further (Downloads, Ringtones, etc).

**Comment by AbandonedCart** [comment]
See if https://github.com/HiddenRamblings/TagMo/commit/ec7cac4e54e43333aa2d4ad0804067a219c0daf0 fixes it. If not, I can dump the entire mimeType check. It's supposed to make things faster, but not working is too fast.

**Comment by greed77** [comment]
After a little more testing, it looks like it's only when it's in the root of the Download folder. Moving into a subfolder allows me to import the keys just fine.

**Comment by AbandonedCart** [comment]
Looks like that build will probably make things worse, not better. I have a feeling it has to do with "Downloads" having special access.

**Comment by greed77** [comment]
Probably, permissions are always annoying XD

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/commit/d0ee00b5245829c03bf2c1579737606be3679226 should help, though.

**Comment by codymitch16** [comment]
thanks for all the help sorry I never replied but I got it to work! thanks!
