### ISSUE TITLE
N2 Elite: 3-dot menu is small and hard to press

### ISSUE THREAD

**Issue by burndive** [HiddenRamblings/TagMo#313]
When viewing an N2 Elite Bank, the 3-dot menu is small.
When attempting to tap it, half the time I either tap outside and the view closes or tap inside and the Replace menu opens.
![Screenshot_20211101-104813_TagMo](https://user-images.githubusercontent.com/19560779/139718304-b5b0f971-6a7b-47e0-ae4f-3ed0cdbe6b92.jpg)

For a non-N2 amiibo, the similar menu is spaced out and easy to tap:
![Screenshot_20211101-104854_TagMo](https://user-images.githubusercontent.com/19560779/139718388-dec7a37f-eb73-4c6e-9219-6d75f49c93df.jpg)

**Comment by AbandonedCart** [comment]
Padding added in https://github.com/HiddenRamblings/TagMo/commit/93c991c5379109cfc736c072703fa6bf18e1946b

**Comment by burndive** [comment]
Tested with 93c991c and 7155225, and it looks and behaves the same as before.

**Comment by AbandonedCart** [comment]
Buttons are now centered across the views and N2 view is considerably larger.

**Comment by burndive** [comment]
The menu is entirely gone now. Is that expected?
The only options are: Activate, Scan, Write, Replace

No Wipe, Edit, or Hex


![Screenshot_20211102-143924_TagMo](https://user-images.githubusercontent.com/19560779/139955597-0f246f6d-5116-47d1-88be-d4983782c226.jpg)

**Comment by burndive** [comment]
With 1ddf118 the menu is back, but it's still difficult to target with a finger per the original issue (although erring to the right no longer closes the amiibo interface).

Also: it looks like there is an off-by-one error displaying the Bank number: "Bank 14" in the screenshot should be "Bank 15" instead. 

![Screenshot_20211102-164534_TagMo](https://user-images.githubusercontent.com/19560779/139967109-da1f3658-c02d-4cb0-8f92-4c97055f9d78.jpg)
