### ISSUE TITLE
"Emulated storage mode" setting cannot be disabled

### ISSUE THREAD

**Issue by ArutanSipdrae** [HiddenRamblings/TagMo#314]
As mentionned in the title, if your disable it, it reenable itself once you leave the settings.

I am using the latest version, TagMo-09dcefa.
I'm running it in Androind 9 on a Galaxy S8.

**Comment by AbandonedCart** [comment]
Do you have a physical sdcard?

**Comment by AbandonedCart** [comment]
Are your files being stored there?

**Comment by ArutanSipdrae** [comment]
Yes

**Comment by AbandonedCart** [comment]
Alright. I'll look into it.

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/commit/943a7a45d5b65a5003ec05a7a162638e85996104 should help with the balance between the app finding files and those that can't find settings.

**Comment by ArutanSipdrae** [comment]
I installed the new release, I could uncheck the setting but it still displayed "No amiibo found" so I deleted all the data, reopened the app, gave permission and reset the keys, but now it keeps saying "Keys not loaded" despite both being found in the settings

**Comment by AbandonedCart** [comment]
Can you grab a log? It's the logcat option in the extended menu on the main page.

**Comment by ArutanSipdrae** [comment]
So uh I generated the log and it unblocked the app. Now I have all my bin correctly found, but here's the log still

[tagmo_logcat[1].txt](https://github.com/HiddenRamblings/TagMo/files/7463745/tagmo_logcat.1.txt)

**Comment by AbandonedCart** [comment]
Looks like it was a permissions issue. Generating the log must have forced it through.

**Comment by ArutanSipdrae** [comment]
There's a prompt missing then because when I deleted the data I said yes to all permission prompt (there was only 1)

**Comment by AbandonedCart** [comment]
That's the only prompt.

**Comment by ArutanSipdrae** [comment]
Oh well, that's gonna be fun to debug ^^"

**Comment by AbandonedCart** [comment]
Beats the posts on reddit.

**Comment by AbandonedCart** [comment]
Figured it all out. It was less a permission and more a context issue.
