### ISSUE TITLE
Seems not compatible with Felica (NFC in Japan phone) ?

### ISSUE THREAD

**Issue by DenisLin** [HiddenRamblings/TagMo#32]
I have a Sony Z3 compact purchased from Japan. None of the version reads ntag215.
Is this a hardware issue or software one?

**Comment by morimori007** [comment]
I also tried it on two Japan mobile (Fujitsu Arrows) but could not read ntag215
Perhaps a hardware problem

**Comment by Johnathan1218** [comment]
Same here, getting crash from 2.3.2 to 2.3.4
2.3.1 ok but getting back Error message saying it is not NTAG215 when I scan my amiibo
It should not be hardware problem since other app could read amiibo
My phone is Fujitsu Arrows F02G

**Comment by Bombastisch** [comment]
Could you post a logcat? Just try to write, then click on the three dots at the top right corner and press "Dump Logcat". Then send the file here on github so we can try to fix it :)

**Comment by Bombastisch** [comment]
Closing due to a lack of feedback, if the problem still occurs please open a new issue thread! ;)
