### ISSUE TITLE
Application Crash in my android samsung

### ISSUE THREAD

**Issue by luffygaming85** [HiddenRamblings/TagMo#320]
Hello i have a problem with the new version  of tagmo, this apply crash everywhere...i tried reinstalling the old version of tagmo but nothing works ..is it possible to help me please 

thank you

**Comment by AbandonedCart** [comment]
Can you post a log from after it crashes?

**Comment by luffygaming85** [comment]
How do I do it with my Phone for extract log please ?

**Comment by AbandonedCart** [comment]
Can you get into the app at all?

**Comment by AbandonedCart** [comment]
Going to assume this is also related to https://github.com/HiddenRamblings/TagMo/issues/315 for now. If the log says otherwise, we can open it back up.

Logs can be written using the Logcat option in the extended menu of the main page.
