### ISSUE TITLE
Stuck writing and reading tags

### ISSUE THREAD

**Issue by scriss312** [HiddenRamblings/TagMo#325]
On both current version and previous version, TagMo got stuck reading and writing tags. I keep seeing the message "Mifare UltraLight scanning..." But then nothing happens.
![Screenshot_20211104-190928](https://user-images.githubusercontent.com/77134299/140447048-12380484-2dce-4093-8dda-d9850456c02b.jpg)

**Comment by AWernerCS** [comment]
Same issue. I was using a much older version that worked just fine and updated tonight after getting a new batch of bin files, now I am unable to write - I get stuck on the exact same screen with the same message.

**Comment by AbandonedCart** [comment]
Are you removing the tag when you hear a beep? Don't.

**Comment by scriss312** [comment]
> Are you removing the tag when you hear a beep? Don't.

I tried both ways. It takes way longer to register a tag is even there compared to previous builds. And it doesn't seem to matter how long I leave the tag, I still have the same message. I've also tried clearing the app cache and restarting my phone and it's the same thing.

**Comment by AbandonedCart** [comment]
It shouldn't take any longer if you haven't enabled N2 support. With that enabled, it does an extra scan to avoid corrupting your tags or N2.

**Comment by AbandonedCart** [comment]
I'll look into speeding it up a bit more. There may be a loophole.

**Comment by AbandonedCart** [comment]
Merged with the other open issue about scanning generic tags.
