### ISSUE TITLE
Error while writing main data (stage 1)

### ISSUE THREAD

**Issue by Caelowo** [HiddenRamblings/TagMo#326]
Hi! I'm getting this error while trying to write tags. The full error text is "Error while writing main data (stage 1) java.io.IOException: Trancieve failed.

Attaching screenshots from NXP tag info

![Screenshot_20211105-151710_TagInfo](https://user-images.githubusercontent.com/93779093/140525618-79485cdc-4c32-4f1c-8a95-ca9700acd823.jpg)
![Screenshot_20211105-151820_TagInfo](https://user-images.githubusercontent.com/93779093/140525651-aee9e181-1036-4127-9726-a3fa91832463.jpg)

![Screenshot_20211105-151843_TagInfo](https://user-images.githubusercontent.com/93779093/140525666-e7ae4eff-cd84-4351-873c-5e066dfd5e54.jpg)
![Screenshot_20211105-151904_TagInfo](https://user-images.githubusercontent.com/93779093/140525672-10937a05-8c2f-4175-b982-f9441fea2caa.jpg)
![Screenshot_20211105-151908_TagInfo](https://user-images.githubusercontent.com/93779093/140525680-db430aeb-a898-41da-be77-6c105b9fd673.jpg)

**Comment by AbandonedCart** [comment]
NXP appears to be saying they're write protected.

**Comment by Caelowo** [comment]
> NXP appears to be saying they're write protected.

Hm. I've used these same tags before without issue... The tags that failed to write still scan in as amiibos when I scan them, but they don't work in animal crossing.

**Comment by AbandonedCart** [comment]
I'll have to increase the logging and see if it gives a better reason. It looks like it is missing a write step. I wouldn't write any more tags until after the update, just to be safe. No use wasting them.

**Comment by Caelowo** [comment]
Alright, thanks. I only have one empty tag left for now anyways, so I wouldn't want to use it until I'm more certain it would work. If it's any help I can show you the NXP tag info for the tags that got something written on them but don't work as amiibos?

**Comment by AbandonedCart** [comment]
NXP info is practically useless for debugging why it didn't write. That just gives the status of the tag after it failed.

**Comment by Caelowo** [comment]
Ah, okay. Well I can only wish you good luck then I guess, and give all of you working on the app my thanks!

**Comment by AbandonedCart** [comment]
If https://github.com/HiddenRamblings/TagMo/commit/e3ffed6de00efc9ab5c2c8b60a5d63d0b6b1b3e9 doesn't end up fixing the issue, it will at least provide thorough logs
