### ISSUE TITLE
Cant read Series 5 Animal Crossing Amiibo

### ISSUE THREAD

**Issue by NPW11** [HiddenRamblings/TagMo#327]
I have backed up the bin files for Series 5 Animal Crossing Amiibo but on tagmo they don't show up.

**Comment by AbandonedCart** [comment]
Have you updated TagMo or synced the API? Made sure your keys are valid (because older ones don't work anymore)? Have you made sure you **backed up** your bins reliably?

**Comment by NPW11** [comment]
![Screenshot_20211105-153907_My Files](https://user-images.githubusercontent.com/93782635/140537797-dd248bcb-9db2-4c28-8c7b-626f8593a54b.jpg)
I have them in the same folder as the other bin files and I have the updated tagmo.

**Comment by NPW11** [comment]
> Have you updated TagMo or synced the API? Made sure your keys are valid (because older ones don't work anymore)? Have you made sure you **backed up** your bins reliably?

![Screenshot_20211105-153907_My Files](https://user-images.githubusercontent.com/93782635/140538009-60e0aef1-34c5-4ea1-9e87-1a3efdc4ea87.jpg)
I have them in a folder with the other bin files and I have the updated tagmo.

**Comment by NPW11** [comment]
> Have you updated TagMo or synced the API? Made sure your keys are valid (because older ones don't work anymore)? Have you made sure you **backed up** your bins reliably?

![Uploading Screenshot_20211105-154319_TagMo.jpg…]()

**Comment by NPW11** [comment]
> > Have you updated TagMo or synced the API? Made sure your keys are valid (because older ones don't work anymore)? Have you made sure you **backed up** your bins reliably?
> 
> ![Screenshot_20211105-153907_My Files](https://user-images.githubusercontent.com/93782635/140538009-60e0aef1-34c5-4ea1-9e87-1a3efdc4ea87.jpg) I have them in a folder with the other bin files and I have the updated tagmo.

![Uploading Screenshot_20211105-154319_TagMo.jpg…]()

**Comment by NPW11** [comment]
> Have you updated TagMo or synced the API? Made sure your keys are valid (because older ones don't work anymore)? Have you made sure you **backed up** your bins reliably?

I have them in a folder with the other bin files and I have the updated tagmo
![Screenshot_20211105-153907_My Files](https://user-images.githubusercontent.com/93782635/140538785-c408ff28-2c6f-4cbe-8296-8a5ea952628c.jpg)
![Screenshot_20211105-154319_TagMo](https://user-images.githubusercontent.com/93782635/140538792-6f4dab65-b4b7-467a-acb3-95332b1e5ffe.jpg)

**Comment by AbandonedCart** [comment]
That doesn't answer any of the questions, though.

Have you updated the TagMo app or synced the API in settings?

After doing one of the above, did you refresh in the browser?

Are you sure the files are compatible with TagMo and your keys?

**Comment by NPW11** [comment]
> That doesn't answer any of the questions, though.
> 
> Have you updated the TagMo app or synced the API in settings?
> 
> After doing one of the above, did you refresh in the browser?
> 
> Are you sure the files are compatible with TagMo and your keys?

I have updated tagmo and I have synced the API. I have refreshed. They should be, I downloaded them from the same place as the other files and they work so I'm not sure why series 5 isn't working

**Comment by AbandonedCart** [comment]
We can't provide support for pirated files. Sorry.
