### ISSUE TITLE
APK will not install.  LG G5

### ISSUE THREAD

**Issue by ynomeikiba** [HiddenRamblings/TagMo#33]
I don't know if this needs a root, or what, but I cannot install any TagMo release on my LG G5.

**Comment by Bombastisch** [comment]
You phone doen't need to be rooted.

Reboot your phone and try to install the newest release of tagmo!

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
