### ISSUE TITLE
App goes to black screen when trying to select import keys

### ISSUE THREAD

**Issue by klxxi** [HiddenRamblings/TagMo#331]
Using Android 7 on a galaxy note 5. I've tried several different things, I tried using an older version of tagmo and it worked for one file but when I try to upload the unfixed file it black screens again. Advice?

**Comment by klxxi** [comment]
I think I got it to work now D:

**Comment by AbandonedCart** [comment]
Older versions are never recommended. The entire purpose of putting a ton of time and effort into effective logging is so we can keep moving forward.
