### ISSUE TITLE
Support Unencrypted (Code Generated) Files

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#334]
Came across https://hax0kartik.github.io/amiibo-generator/ and got the idea that it may be not only possible, but preferable to support generated bin files.

This still requires some research, but will not replace existing support for backups.

**Comment by AbandonedCart** [comment]
This actually ended up being super easy. We could technically ship with support for downloading these directly into the app. No bin files required. Only keys.

**Comment by AbandonedCart** [comment]
* Download the latest experimental build.
* Open the app settings and scroll to the very bottom.
* Wait for the link to appear and click bulk download.
* Wait for the download to finish and press back.
* Watch as the dialog throws up lots of text.
* Return to the browser and select the new folder.

**Comment by ishtangli** [comment]
Tried this but tags didnt show up. Promising though
