### ISSUE TITLE
Build Wumiibo error page

### ISSUE THREAD

**Issue by x7l7j8cc** [HiddenRamblings/TagMo#339]
As the title suggest, when i tap on the Build Wumiibo option i get this error page.
And the decrypted amiibo doesnt show up anymore, while before the latest update, worked perfectly.

![Screenshot_20211109_111522_com hiddenramblings tagmo](https://user-images.githubusercontent.com/526407/140905906-f4aa5fa9-473e-43d8-9229-e447d6bbfae2.jpg)

**Comment by AbandonedCart** [comment]
Make sure to check the box to display the download folder. It's in the extended menu under content.

**Comment by x7l7j8cc** [comment]
It's checked, but nothing.
Decrypted Amiibo doesnt show up, and the Build Wumiibo page give that error.

But as i said, yesterday before the latest update (the version with 'Amiibo Generator' page) worked.

**Comment by AbandonedCart** [comment]
Yes. There were some changes since then. It appears not all phones are compatible with them.

**Comment by x7l7j8cc** [comment]
Can you send me the version with the 'Amiibo Generator' page?
At least that worked fine for me.

Anyway, i have a huawei p30 pro, if this helps for something. And if you want i can test for you a version that fix the problem on this phone (dont know others), if you want.

**Comment by AbandonedCart** [comment]
I don't have that old version. They are replaced when a new one builds.

**Comment by x7l7j8cc** [comment]
Great, no decrypted amiibo (need to recrypt, again)...
Anyway, neither on my Samsung S6 Tablet work that page.

![IMG_20211109_130611](https://user-images.githubusercontent.com/526407/140921399-dcabdcb3-ea6a-4c6e-8c60-98741294f54d.jpg)

**Comment by AbandonedCart** [comment]
I believed you.

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/HiddenRamblings/TagMo/commit/3e5a31ebb13aa24f81c8acbb21996192d7279552

**Comment by x7l7j8cc** [comment]
Yep, thhis new version , fixed the error on both devices.

**Comment by AbandonedCart** [comment]
Shame it won't work as an asset for the bandwidth savings, but oh well.

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/commit/4a0f39e70f56ef86a40f1ff9969f9a50663e353b should be the best of both

**Comment by x7l7j8cc** [comment]
Sorry but nope...

Error again.
![Screenshot_20211109_230411_com hiddenramblings tagmo](https://user-images.githubusercontent.com/526407/141012318-fb1f3d35-4fd1-4aff-92ac-907a3eebecc6.jpg)

**Comment by AbandonedCart** [comment]
I figured out the issue. GitHub Actions wasn't pulling the submodule. Newest build should fix it.
