### ISSUE TITLE
TagMo doesn't see tag?

### ISSUE THREAD

**Issue by shadraak** [HiddenRamblings/TagMo#34]
Trying on my nephews Samsung mega.  Keys load.  Bin loads. When I hit write auto it says to lay the phone on the tag.  And that's as far as I get.  Thought it was just his phone.  Tried on my sisters note 3. And exact same issue.  I've tried 2.3.2 and 2.3.3.  Any ideas?

**Comment by xxBigRonxx** [comment]
There is a known Samsung issue.  Try an older build or build/find an .apk with the latest source.

**Comment by shadraak** [comment]
I tried the two oldest ones I could find.   Guess I'll try the beta?

**Comment by shadraak** [comment]
Still same issue.  Just keeps saying place phone on tag

**Comment by xxBigRonxx** [comment]
Try this one.  
https://uploadfiles.io/e872p

**Comment by shadraak** [comment]
What is that?

**Comment by xxBigRonxx** [comment]
A tagmo .apk using the latest source.  It has the fix for Samsung.

**Comment by shadraak** [comment]
Says can't open file

**Comment by dtb1987** [comment]
Uninstall it from your phone and try again

**Comment by shadraak** [comment]
no i mean the download wont install

**Comment by shadraak** [comment]
app-fat-universal-debug.apk   Is the name and not opening.

**Comment by xxBigRonxx** [comment]
Not sure why.  Works great for me.  You can watch some YouTube videos and create your own .apk from the source.

**Comment by shadraak** [comment]
his samsung mega is on i believe android 4.4.2 andd i download that and try
to install and it says that it can't.

**Comment by shadraak** [comment]
But is this the known Samsung issue?  I don't get any errors or anything.  It just doesn't see any tags at all

**Comment by xxBigRonxx** [comment]
Yes it is a known issue. Check out the following:
https://github.com/Kidel/TagMo

**Comment by shadraak** [comment]
Nothing there. Weird.

**Comment by xxBigRonxx** [comment]
Look in desktop mode

**Comment by ElForever** [comment]
Hmm that also happened to me, i tried with 2 different phones a Galaxy S4 and a HTC One M7, NFC obviously activated, when i tried to scan tags it didn't scan them and when i tried to write a tag it just says done without even putting the NTAG.. Wish i knew what's the issue :/

**Comment by Bombastisch** [comment]
Should be fixed by now. Try to use the newest release! If there are any issues, please open a new issue thread
