### ISSUE TITLE
List doesnt update after writing to N2

### ISSUE THREAD

**Issue by ishtangli** [HiddenRamblings/TagMo#343]
When you replace the tag in a slot, the list isnt updated. It will still show the same amiibo. Write is successful though. Confirmed by rescanning.

**Comment by AbandonedCart** [comment]
Addressed in https://github.com/HiddenRamblings/TagMo/commit/42d6614f7820cae2ec03b909161137635f9869f8, pending some more work on the submodules building with Actions
