### ISSUE TITLE
Wumiibo displayed even if Downloads folder is excluded

### ISSUE THREAD

**Issue by ishtangli** [HiddenRamblings/TagMo#346]
Tested the wumiibo function. Tried to exclude the downloads folder but they were still included in the list

**Comment by AbandonedCart** [comment]
Update.

**Comment by ishtangli** [comment]
They are in different folders. My normal Amiibos are in /Amiibo while the wumiibo are in /Downloads/wumiibo. This results in duplicates

![Screenshot_20211111-134814](https://user-images.githubusercontent.com/17796839/141244822-7be2e2ab-eea4-4355-ac95-3243fe2c2a9f.jpg)

**Comment by AbandonedCart** [comment]
Yes, but this was fixed.

**Comment by ishtangli** [comment]
I just updated and still seeing duplicates. Anyway, i think it will be fixed in future release. Thanks for the hard work and the amazing app.

**Comment by AbandonedCart** [comment]
I still haven't been able to duplicate this, even on a fresh install.

**Comment by AbandonedCart** [comment]
Do you have an Amiibo (Decrypted) folder in your usual one? If you tried any of the really early tests, the folder was there. It can be safely deleted.

**Comment by ishtangli** [comment]
Its fixed on the latest release.

**Comment by AbandonedCart** [comment]
I don't know what fixed it, but thanks for the update. I'll keep an eye on it so it doesn't come back.

**Comment by ishtangli** [comment]
Thanks for the great work!
