### ISSUE TITLE
TagMo Crash on LG G5 when writing

### ISSUE THREAD

**Issue by cerealfordinner** [HiddenRamblings/TagMo#35]
Just got my NTAG215 tag in the mail today and i was really exited to write some amiibos to it but so far i havent been able to write using any version of TagMo (from 2.3.0-2.3.4) or any amiibo file. When i attempt to use write(auto) on the newer versions of TagMo the app just crashed and when i use the older versions like people have advised i get a javascript error "Error while writing main data".

Any help would greatly appreciated thank you.

**Comment by scottjl** [comment]
Ditto for me, LG V20 (LG-H918) running Android 7.0, stock, T-Mobile.

**Comment by reno777** [comment]
Same thing happens for me on Moto z force Android 7.0 Going to try 2.3.1

**Comment by jayd189** [comment]
I have an LG G5 and 2.3.1 worked for me.

**Comment by smilzo** [comment]
Same with HUAWEI P9 lite with Android 7.0 TagMo 2.3.3. Don't work the "Show HEX" and "Edit SSB Data"

**Comment by charedj** [comment]
Likewise, ASUS Zenfone 2 5.5" running Android 5.0.

**Comment by DJTheodorson** [comment]
Newest version crashes on S6 Active. Going to try 2.3.1

**Comment by xaviertidus** [comment]
Crashes also on Huawei Nexus 6P and Sony Xperia Z2 & Z3. Attempted using all 2.3.x versions

**Comment by xaviertidus** [comment]
Just tested Kidel's code changes on all devices, code changes do indeed fix this issue.

https://github.com/HiddenRambler/TagMo/pull/14/commits/18548177312a3836472b9fa40bc875a72dc9c265

**Comment by Bombastisch** [comment]
Should be fixed. Use the newest version!  If there are still any problems, feel free to open a new issue thread :)
