### ISSUE TITLE
Failed to decrypt tag

### ISSUE THREAD

**Issue by cocconutdoggo** [HiddenRamblings/TagMo#353]
So i recently bought some NFC Sticker off of Amazon and when i tried them today no matter what i tried with the keys and everything it just seems to not want to work... Ive tried scanning other NFC Cards that i bought previously (already written on unfortunatly) and they seem to work just fine... any ideas how i can fix it? and hopefully telling me i didnt waste my money on these stickers.

**Comment by AbandonedCart** [comment]
Do you have a log? It's possible they are bad bin files or there is a bug, but it is impossible to tell which based on the message alone.

**Comment by cocconutdoggo** [comment]
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7540651/tagmo_logcat.txt)
hope this works

**Comment by AbandonedCart** [comment]
You're using a really old version. There is a good chance the issue was already fixed, but we can investigate further if it wasn't.

**Comment by cocconutdoggo** [comment]
I was just dumb and forgot to follow one step.
