### ISSUE TITLE
Scanning NFC tag stalls until the tag is removed and put back again

### ISSUE THREAD

**Issue by burndive** [HiddenRamblings/TagMo#355]
Scan icon -> Scan NFC Tag
Place tag under the phone -> NFC tag detected -> Mifare UltraLight scanning....
(This screen does not change, not matter how long I leave it in place).

If I want it to proceed, I need to remove the NFC tag from the back of the phone, and then place it on the back of the phone again.

When I do so, it immediately scans the tag and displays the results.

**Comment by burndive** [comment]
I've observed a similar issue when I attempt to write to a blank tag.

After "Mifare UltraLight scanning..." I have to remove the tag and then put it back before it will proceed with the write.

**Comment by AbandonedCart** [comment]
This is by design.
