### ISSUE TITLE
N2: errors on View Hex Data or Edit Properties

### ISSUE THREAD

**Issue by burndive** [HiddenRamblings/TagMo#357]
When selecting View Hex Data or Edit Properties on an N2 Bank, I get either "Failed to decrypt data" or "Failed to encrypt data". Which error will I get seems unpredictable, but an error always occurs, and I am never successfully shown the data.

Logcat from a run where both kinds of errors occurred:
https://www.dropbox.com/s/4fheqci80qlzdj8/tagmo_logcat%20%282%29.txt?dl=0

**Comment by AbandonedCart** [comment]
Part of converting to dealing with encrypted (working) data is that any data made unencrypted is obsolete. Whatever the app can't fix will need to be written fresh. Additional attempts to repair data were added, but nothing more can be done about it.
