### ISSUE TITLE
Bin files

### ISSUE THREAD

**Issue by Xcaitlin3012** [HiddenRamblings/TagMo#358]
The bin files (that used to work) don't load anymore on TAGMO. How is this issue fixed?

**Comment by AbandonedCart** [comment]
There's not much to work with here.

**Comment by AbandonedCart** [comment]
If the changes made for https://github.com/HiddenRamblings/TagMo/issues/357 don't fix this issue, this can be opened again with a logcat. Bin files cannot be shared, so there is no way to test if the issue is the bin files. The log will at least be able to determine that.

**Comment by Xcaitlin3012** [comment]
How do I use a logcat?

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/wiki/Reporting-Issues
