### ISSUE TITLE
N2 support broken in TagMo-aa59599

### ISSUE THREAD

**Issue by riley-west** [HiddenRamblings/TagMo#359]
Latest update crashes when scanning my N2 tag
[crash_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7549809/crash_logcat.txt)
.

**Comment by AbandonedCart** [comment]
That makes sense. Completely forgot to convert that. It'll be fixed as soon as I unbury my computer.

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/HiddenRamblings/TagMo/commit/184628f4f5a5ed451f0b43ffd6c3ce5f2320c55e
