### ISSUE TITLE
Increasing N2 bank count freezes the app

### ISSUE THREAD

**Issue by AuroraWright** [HiddenRamblings/TagMo#365]
When increasing the N2 bank count, the app crashes and needs to be reopened. The change occurs successfully though. On a related note, reducing the bank count doesn't cause a crash but the N2 window doesn't get refreshed.
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7598675/tagmo_logcat.txt)

**Comment by AuroraWright** [comment]
Latest commit works fine increasing but crashes decreasing
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7599135/tagmo_logcat.txt)
:

**Comment by AuroraWright** [comment]
There's no more crashing now, but after decreasing it seems the wrong banks are shown:
![Screenshot_20211125-012955_TagMo](https://user-images.githubusercontent.com/15571693/143330157-dbe913a9-b0b8-4f09-8302-200749b5f2a2.png)
![Screenshot_20211125-012907_TagMo](https://user-images.githubusercontent.com/15571693/143330167-22cf6949-b888-4041-ba9d-d74cab1acb24.png)

**Comment by AbandonedCart** [comment]
Lol. Android really broke adapters...

**Comment by AbandonedCart** [comment]
Included in https://github.com/HiddenRamblings/TagMo/commit/3c5d76026ea200f010ab01b73aa45f8f4decefb6
