### ISSUE TITLE
Serial randomizer fixed in fork 

### ISSUE THREAD

**Issue by Havael** [HiddenRamblings/TagMo#367]
@Havael Sorry you got steamrolled on your own issue. Please open a new one if the issue persists.

_Originally posted by @AbandonedCart in https://github.com/HiddenRamblings/TagMo/issues/350#issuecomment-978070561_

So it seems that fork was working on the given issue. But, since it's very unstable, I would like to know if that solution will be implemented. While avoiding crashing randomly after some time(or rotating the screen).

**Comment by AbandonedCart** [comment]
I don't know what fork that is, but a solution has been implemented.

**Comment by Havael** [comment]
> I don't know what fork that is, but a solution has been implemented.

Oh. I guess I'll try before saying the fork

**Comment by Havael** [comment]
By the looks of it. It's working. But it would be nice to edit properties in the n2 banks directly. Maybe another issue

**Comment by AbandonedCart** [comment]
I'm not sure I understand what that means.
