### ISSUE TITLE
Tagmo not indentifying n2 as NTAG215

### ISSUE THREAD

**Issue by Havael** [HiddenRamblings/TagMo#368]
Self explanatory. Not much to add

**Comment by Havael** [comment]
When scanning

**Comment by AbandonedCart** [comment]
It's popping up as a single tag?

**Comment by Havael** [comment]
Yeah

**Comment by AbandonedCart** [comment]
Make sure n2 support is enabled in settings

**Comment by Havael** [comment]
> Make sure n2 support is enabled in settings

It is

**Comment by AbandonedCart** [comment]
Unlock the hardware

**Comment by Havael** [comment]
> Unlock the hardware

Done also

**Comment by Havael** [comment]
It just started doing this

**Comment by AbandonedCart** [comment]
Is your N2 going bad?

**Comment by Havael** [comment]
> Is your N2 going bad?

Nope. Just tested it with the n2 elite app and, sure enough, working as usual

**Comment by Havael** [comment]
I think this happened before with an older version of tagmo. But it just solved itself, so no idea what happened

**Comment by AbandonedCart** [comment]
There are only 3 causes for it. N2 support disabled, locked hardware, and corrupt signature.

**Comment by Havael** [comment]
Sorry. Worded the problem wrongly

**Comment by Havael** [comment]
It thinks it's an unsupported format

**Comment by AbandonedCart** [comment]
Oh. Scan it in the official app and change active banks. The recovery code isn't in TagMo yet.

**Comment by Havael** [comment]
Oh. I'm stupid. I was trying to scan a bank I emptied

**Comment by Havael** [comment]
Maybe there should be a clearer error message. But it's probably my smooth brain talking. Sorry to bother

**Comment by AbandonedCart** [comment]
It's not our error message. That's the NFC hardware.

**Comment by Havael** [comment]
> It's not our error message. That's the NFC hardware.

Ah I see. Maybe put a warning in the wiki, if there isn't already, so people don't make this mistake or smth

**Comment by Havael** [comment]
> It's not our error message. That's the NFC hardware.
> 
> What I've tried to do is catch the ones with known solutions and offer that instead of the vague error.

Well that's better at least. Thanks

**Comment by AbandonedCart** [comment]
You shouldn't be able to scan a blank bank unless you keep TagMo open to the N2 browser, swap to the N2 app and clear one, then return. As for the other cause, that should get resolved by overwriting any banks with the bad serial numbers. I wouldn't know what sort of warning to give, other than not to use old builds. I think it does say to update somewhere.
