### ISSUE TITLE
Attempt to get length of null array

### ISSUE THREAD

**Issue by riley-west** [HiddenRamblings/TagMo#369]
I'm getting the above message when scanning and writing tags. Not sure if it's an error or not but it comes up in big red text
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7605680/tagmo_logcat.txt)
.

**Comment by AbandonedCart** [comment]
Are you scanning empty tags and trying to write amiibo you don't have?

**Comment by riley-west** [comment]
To be clear, the message shows up both when using the data validation option or the writing tag option and is successful.  But it appears during both processes.

**Comment by AbandonedCart** [comment]
That wasn't what I was asking, though. I was asking if you are writing valid bin files and scanning tags with data on them.

**Comment by riley-west** [comment]
Yes & yes.

**Comment by AbandonedCart** [comment]
Looks like you're using an old version. The lines referenced in the log don't exist anymore.

**Comment by riley-west** [comment]
It's the newest version with the self update enabled.

He's another scan of another tag done just now
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7605769/tagmo_logcat.txt)
.
I also did a screen capture showing the message appearing.
[https://streamable.com/k4gs3q](https://streamable.com/k4gs3q)

**Comment by AbandonedCart** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.sort(java.util.Comparator)' on a null object reference
11-22 09:07:37.490 21572 21572 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:206)
11-22 09:07:37.490 21572 21572 E AndroidRuntime: 	at com.hiddenramblings.tagmo.adapter.BrowserAmiibosAdapter$AmiiboFilter.publishResults(BrowserAmiibosAdapter.java:245)

https://github.com/HiddenRamblings/TagMo/blob/master/app/src/main/java/com/hiddenramblings/tagmo/adapter/BrowserAmiibosAdapter.java#L245

**Comment by AbandonedCart** [comment]
Power Tag or card / coin?

**Comment by riley-west** [comment]
They're single use tags.  I do have N2 compatibility enabled.

I just disabled N2 in the settings and the error goes away.

**Comment by AbandonedCart** [comment]
That's because the hardware will instantly fail on the check for an n2 tag. Yours doesn't. It needs a secondary check for if it doesn't.

**Comment by riley-west** [comment]
Oh ok, so it's not an error.  Good to know, thanks for explaining.
