### ISSUE TITLE
Cant Install the Version 834c86f

### ISSUE THREAD

**Issue by Ericzion1999** [HiddenRamblings/TagMo#374]
I have the Samsung a3 (2017) With Android 8 , When i try to Install the Apk , my Phone says ,,App was not installed,,![IMG_20211209_143814_476.jpg](https://user-images.githubusercontent.com/82835573/145406563-61173089-b0a1-44ea-9115-0aa9f1d5a098.jpg)

**Comment by AbandonedCart** [comment]
Current versions can't be installed directly over those from 2020 and earlier.

**Comment by Ericzion1999** [comment]
I don't have tagmo installed before

**Comment by Ericzion1999** [comment]
I have it installed Version 3cb304b now on my HTC one but it Crashes everytime If i want to Open the App 
[logcat](https://drive.google.com/file/d/1B-bv8sDX9O32w7xB9f8Fm5mInLI7gT4T/view?usp=drivesdk)

**Comment by AbandonedCart** [comment]
There's no way of knowing why it won't install without running logcat during the install. That's Android stopping it. The most common reasons being installing with a different signature and not having the hardware for a required feature (NFC is the only one)

**Comment by Ericzion1999** [comment]
This one ?
https://play.google.com/store/apps/details?id=com.google.android.gms

**Comment by Ericzion1999** [comment]
It works now on my HTC one 0493ec5
I think IT doesnt Work on my Samsung because i have Not enough space , sorry for the issue
