### ISSUE TITLE
After scanning N2 and pressing the bottom bar, it shows an error and not the active bank

### ISSUE THREAD

**Issue by riley-west** [HiddenRamblings/TagMo#375]
Screenshot attached. 
![Screenshot_20211210-182444](https://user-images.githubusercontent.com/94332992/145656623-8cb0b27e-7b69-45a2-be72-e47d70551102.png)

**Comment by AbandonedCart** [comment]
It never showed the active bank, but clicking on the active bank should display correctly. The view isn't being removed when nothing it loaded. No functionality has actually broken.

**Comment by riley-west** [comment]
Just seemed like a missed opportunity to show *anything* when hitting the bottom bar.

Thanks for everything you do!

**Comment by AbandonedCart** [comment]
Thanks for the idea. Displaying the active bank as the initial default is better than starting blank. It may not make sense for every time it was blank, but it definitely works there.
