### ISSUE TITLE
Is it possible to have an option to stop tagmo scanning when closed. 

### ISSUE THREAD

**Issue by riley-west** [HiddenRamblings/TagMo#376]
The case for my phone let's me keep my credit cards in them. However. TagMo thinks I'm trying to scan a tag when the credit card touches the back of my phone and keeps opening itself.

Is it possible to have an option in the settings to turn this off?

**Comment by AbandonedCart** [comment]
It's not something that can be toggled on and off, but possibly improved.

**Comment by riley-west** [comment]
Hello!

I saw the latest update, the issue is still present with my Visa card triggering tagmo to open.

**Comment by AbandonedCart** [comment]
I may have added an option to disable the auto scan, but at the cost of no auto scan, even in the browser.

**Comment by riley-west** [comment]
Oh that's excellent, I'll give it a test, thank you 👍

**Comment by riley-west** [comment]
All seems to work just fine! Thank you for your efforts.
