### ISSUE TITLE
Scanning Powertag in Tagmo doesnt work

### ISSUE THREAD

**Issue by UmarM211** [HiddenRamblings/TagMo#382]
![Screenshot_20211224-151144_TagMo](https://user-images.githubusercontent.com/96634026/147370653-77d3f510-88d3-4216-87cf-d6e1f5fb59c0.jpg)

When I scan the powertag after going on write on one of the amiibos. It just stays on Mifare UltraLight scanning and then it goes to detected after I take it away and put it back on. After that, it just stays on detected and doesn't change or anything.

**Comment by AbandonedCart** [comment]
Did you enable Power Tag support in the app settings and perform the setup from https://tagmo.gitlab.io/powertags.html?

If both are complete, a log will be needed. After it gets stuck, return to the main screen and use the logcat item in the 3 dot menu.
