### ISSUE TITLE
NFC goes wonky after installation

### ISSUE THREAD

**Issue by NuclearDeLorean** [HiddenRamblings/TagMo#39]
Hello! I have a HTC One Remix with NFC running android 4.4.2 and when I load TagMo with NFC enabled/on and fully functional.  As soon as any version of TagMo gets installed, NFC now cycles on and off and I cannot use it nor turn it off unless I do a factory reset.  Then NFC returns to normal. I have installed now every version of TagMo on the site. Cycles between "scanning tag" and "NFC Not Enabled!" back and forth. Any thoughts?

**Comment by Bombastisch** [comment]
Could you try the latest version and check if your problems are solved!

**Comment by LoyalUser** [comment]
Having the exact same problem with HTC One Mini 2 also running on android 4.4.2.

**Comment by Bombastisch** [comment]
Could you open the app, enable nfc and just run the app for a few seconds. then click on the three dots upper right and click "dump logcat" and post the file in here?   logcat.txt can be found in the tagmo folder of the phones base directory

**Comment by Bombastisch** [comment]
I still need sonone of you to send me a logcat, since I cant replicate that bug. If we have a logcat we can most likely fix the problem easily

**Comment by Bombastisch** [comment]
Closing this due to a lack of feedback.
If the issue still appears please open a new issue thread. :)
