### ISSUE TITLE
kind of a n00b here, but what does this mean?

### ISSUE THREAD

**Issue by Sel1432** [HiddenRamblings/TagMo#390]
"Attempt to invoke virtual method 'void com.hiddenramblings.tagmo.nfctech.NTAG215.connect()' on a null object reference"

Does this mean that the chips i'm trying to use are no good, incompatible, or what? I bought ones specifically for amiibo stuff...

**Comment by AbandonedCart** [comment]
It could mean a few things. Incompatible tags, not holding them close enough or long enough to the NFC antenna, or the device doesn't support reading or writing the technology type.

**Comment by Sel1432** [comment]
It will briefly flash mifare classic detected but then immediately give that error after doing so.

**Comment by AbandonedCart** [comment]
Oh, then likely the wrong tags. You need mifare ultralight (NTAG215).
