### ISSUE TITLE
Error when selecting erase banks on N2

### ISSUE THREAD

**Issue by Miss1sle** [HiddenRamblings/TagMo#394]
![Screenshot_20220119-103353](https://user-images.githubusercontent.com/97257924/150174070-4103a885-c666-4722-aebe-68f656364b6e.png)

**Comment by Miss1sle** [comment]
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7898867/tagmo_logcat.txt)

**Comment by AbandonedCart** [comment]
`TagLostException: android.nfc.TagLostException: Tag was lost.`

You're yanking the tag away before it's finished.

**Comment by Miss1sle** [comment]
Nope, the tag is held there the whole time. Some of the slots are already empty and I'm telling it to erase every slot.

But the tag is very much held there and not moved. The error comes up instantly. Should I make a video?

**Comment by Miss1sle** [comment]
https://user-images.githubusercontent.com/97257924/150179564-14466532-2336-4378-971d-cb6a35cd718c.mp4

**Comment by AbandonedCart** [comment]
Unfortunately, the log says the tag is lost. It's hard for me to argue with the log. I can look into why it loses the tag, but it definitely loses the tag.

**Comment by Miss1sle** [comment]
That's super weird. And the speed it comes up makes me think it's something else. Let me populate every slot and see if it changes anything.

**Comment by Miss1sle** [comment]
Still fails with every slot populated, let me try a different phone.

**Comment by Miss1sle** [comment]
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/7899188/tagmo_logcat.txt)

Fails in exactly the same way.
