### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by Bex89** [HiddenRamblings/TagMo#401]
I've tried to install it on my oneus 7t pro 5g but it says app not installed

**Comment by AbandonedCart** [comment]
Are you trying to install it over a really old version?

**Comment by Bex89** [comment]
No I tried installing out right. The last working version that will install is 2.7.0

**Comment by AbandonedCart** [comment]
Assuming you realized you can't install over 2.7.0. Changes in 2.7.3 made that the earliest that allows replacing.
