### ISSUE TITLE
Error Message: Attempt to invoke virtual Method

### ISSUE THREAD

**Issue by ASpooner85** [HiddenRamblings/TagMo#407]
I get the error Message
Attempt to invoke virtual Method 'void v4.e.connect()' on a null object reference. Every time i will spielen something with the Tag (scan, write, Update)

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/wiki#reporting-issues

**Comment by AbandonedCart** [comment]
Based on the message alone with no other details, it sounds like the device doesn't support NFC.

**Comment by ASpooner85** [comment]
My Device is an OnePlus Nord CE 5G
NFC works fine with my ID card. 

![Screenshot_20220221-161058](https://user-images.githubusercontent.com/74454870/154982029-2244d4a5-b11f-4caa-8331-7edcc3b7cf69.jpg)

**Comment by AbandonedCart** [comment]
The screenshot has confirmed that the error message was typed correctly.

**Comment by ASpooner85** [comment]
Now. After installing the newest Version, the App Crashs without generating a log.

Seems my telephone and his user are both to dumb to use the App.

**Comment by AbandonedCart** [comment]
If the app crashes instantly, it writes a log.
