### ISSUE TITLE
2.3.3 and 2.3.4 Beta crashes when writing on tag using Nexus 5X

### ISSUE THREAD

**Issue by TonySpegel** [HiddenRamblings/TagMo#42]
After trying to write a bin file onto a tag the app crashes. Another app displays that there weren't any bytes written.

**Comment by Bombastisch** [comment]
I have the same problem with my Nexus 5X!  In my case I use a Lineage ROM with Open Gapps, Android 7.0.1  . But if you compile some of the Pull requests the app works perfectly! But on the other side all Pull requests miss the feature of editing SSB data.

**Comment by TonySpegel** [comment]
Version 2.3.2 worked for me w/o crashing :3

**Comment by Bombastisch** [comment]
Have you tried to edit the SSB data of real Amiibo? This feature always crashes... Does it work on somebodys phone?

**Comment by TonySpegel** [comment]
I don't own any Amiibos - I just had problems writing bin file onto Tags.

**Comment by Bombastisch** [comment]
On 2.3.2 SSB data editing works perfectly! But on the newer versions SSB fails all the time...(app crashes)  Dunno what to do, the pull requests miss that feature entirely. I really hope it will be added or fixed. I love that feature!

**Comment by HiddenRambler** [comment]
is this still an issue with the latest?

**Comment by Bombastisch** [comment]
No more problems. App works perfectly fine!
