### ISSUE TITLE
2.3.3 and 2.3.4 crashes when reading or writing tags on Pixel XL

### ISSUE THREAD

**Issue by whatinthenameofgod** [HiddenRamblings/TagMo#43]
Tried installing different versions of TagMo and had no luck.

**Comment by HiddenRambler** [comment]
is this still an issue on the latest?

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
