### ISSUE TITLE
Bluup Flask Compatibility

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#461]
This issue is for tracking progress of Bluup Flask compatibility. 

As it stands now, Bluetooth LE (BLE) support is limited to devices with Jelly Bean MR2 (4.3.1) or newer. Development is being conducted in the current test branch. Testing is open to anyone, but not recommended for those looking to replace their current connection method.

Progress is currently based on log data. All progress is purely experimental and completely untested when published until further notice. Any changes may break support at any time, as code is not yet verified.

Logs are available using the current submission methods provided in TagMo. As this is experimental code, ambiguous error messages and other forms of generic output (ie. Screenshots) do not provide necessary details.

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/issues/463
https://github.com/HiddenRamblings/TagMo/issues/464

**Comment by withgallantry** [comment]
Hi, I now have some hardware I can provide to develop against. I had some delay due to ongoing chip and components shortages. Let me know where I can send it to at bluup@bluuplabs.com. I'm also reachable at that address if you need anything.

**Comment by AbandonedCart** [comment]
Hope you're feeling better. I had a feeling you might not be actively checking GitHub, but didn't want anyone thinking it was just randomly paused for no reason.

**Comment by AbandonedCart** [comment]
Doing a little housekeeping to make navigation "pretty" before going back to working on functionality. Just a heads up that most of the recent and upcoming commits for the moment are cosmetic.

**Comment by AbandonedCart** [comment]
It seems the permission flow for bluetooth is somewhat convoluted. Documentation claims I need access to fine location for bluetooth. Background location is also acceptable on Android 12. To obtain fine background location, I should request both or the option won't be displayed. Makes sense.

Doing that actually ends up saying I should get foreground permission first and then prevents displaying any prompts and immediately returns denied. Asking for background location and denying it manually works.

**Comment by AbandonedCart** [comment]
Has anyone tested connecting recently? It won't actually do anything yet, but it should successfully connect.

**Comment by Ericzion1999** [comment]
It says ,,Not a valid flask device,,

**Comment by AbandonedCart** [comment]
> Logs are available using the current submission methods provided in TagMo. As this is experimental code, ambiguous error messages and other forms of generic output (ie. Screenshots) do not provide necessary details.

**Comment by Ericzion1999** [comment]
So , do you need a Logcat ?

**Comment by AbandonedCart** [comment]
The method to identify the device has been changed a bit and now there is a status message when it's found.

**Comment by Ericzion1999** [comment]
it finds all my bluetooth devices but not the flask

**Comment by AbandonedCart** [comment]
There isn't much I can do with that information.

**Comment by Ericzion1999** [comment]
What is the correct Method to find It With tagmo? maybe I'm doing something wrong all the time

**Comment by AbandonedCart** [comment]
Scroll over to the "Flask BLE" window. If it is found (based on the device name), it tries to connect. If it was renamed, it should show up in the list and it needs to be clicked. If it's not paired, the add new device option opens pairing options.

It may work or it may not. I have no idea. I don't have one yet to see what happens.

**Comment by Ericzion1999** [comment]
this is exactly what i was doing all the time, i connected the flask to my phone but it didn't show up in the tagmo list, only other devices

**Comment by AbandonedCart** [comment]
Then it doesn't work.

**Comment by AbandonedCart** [comment]
It can confirm that my iPad has BLE services available, but none match the Flask characteristics. Beyond that, I can't test until the hardware arrives.

**Comment by Miss1sle** [comment]
I have paid my phone to my flask but the only 3 devices I see in TagMo are my car, my printer and an old Bluetooth speaker. None of which are near me or actively connected to my phone.

**Comment by AbandonedCart** [comment]
Everything sounds normal so far. The part I can't test myself is what happens after that point.

**Comment by AbandonedCart** [comment]
Added a visual notice for when the app finds the Flask on its own. This should reduce some of the confusion that it isn't being listed.

**Comment by AbandonedCart** [comment]
To confirm, there are no popups stating that the device was detected since the latest change to add them?

**Comment by Ericzion1999** [comment]
Yes , there is No Popup

**Comment by AbandonedCart** [comment]
@Miss1sle Are you getting the same?

**Comment by Ericzion1999** [comment]
I don't know if this is a helpful tip, but if you use the web version, there is no point in pairing the flask with the smartphone/PC via Bluetooth beforehand, because then the web version can no longer find the flask

**Comment by Miss1sle** [comment]
I now see the flask in the list in tagmo, however when I click it, tagmo tells me it's not a valid device.

**Comment by AbandonedCart** [comment]
Connecting without pairing on Android would require the MAC address, which we don't have going into the process.

**Comment by AbandonedCart** [comment]
Progress should ramp up in the next week or two. The entire format is changing and will more closely resemble that of the N2 in that selecting the device from a list will be replaced with detecting the device.

**Comment by AbandonedCart** [comment]
It seems a bit silly to maintain an issue for testing at this point.

**Comment by AbandonedCart** [comment]
... since connecting works.
