### ISSUE TITLE
LEGO Dimensions Support

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#465]
After stumbling across someone requesting a way to write LEGO Dimensions tags, I ended up looking into the format. It seems that they are generated and may not be entirely difficult to support. Since TagMo already includes the means to differentiate tag formats, the transition between NTAG215 and NTAG213 shouldn't be a problem.

Is this something that would be worth looking into further?

**Comment by stub2k2** [comment]
I support this feature

**Comment by AbandonedCart** [comment]
This will be attempted after Flask integration gets closer to a working design.
