### ISSUE TITLE
Bulk Write Amiibo's to N2 Elite

### ISSUE THREAD

**Issue by cyclikal94** [HiddenRamblings/TagMo#470]
Hi - Is there any way to pre-load the banks for my N2 Elite with the Amiibo's I want, then in one go write them to each bank? Kinda like how the erase all banks goes through each bank? Ideally, I'd like to be able select an Amiibo and then fill say 10 slots with it (each with a randomised serial) - I'm trying to get the special weapons / equipment in Breath of the Wild, and it only allows one scan of the same Amiibo per day.

**Comment by AbandonedCart** [comment]
https://tagmo.gitlab.io/n2elite.html?s=writing

**Comment by AbandonedCart** [comment]
Loading 10 copies of the same amiibo would load 10 of the same serial, leaving you to go back and change each one to write again. At that point, it saves time to simply generate the serial and write it. Due to the number of users that struggle with basic reading and writing, amiibo data is not cached between operations.

**Comment by cyclikal94** [comment]
Ahh thank you I've re-read that a couple times now and finally figured it out! D'oh, I was confused thinking the 'Write X Banks to N2 Elite' actually changed the number of banks the N2 device had - but actually clicking it I can select multiple amiibo's! Thanks for pointing me in the right direction!

**Comment by cyclikal94** [comment]
> Loading 10 copies of the same amiibo would load 10 of the same serial, leaving you to go back and change each one to write again. At that point, it saves time to simply generate the serial and write it. Due to the number of users that struggle with basic reading and writing, amiibo data is not cached between operations.

I think I've figured a way to be able to pre-create the bin's, so I have duplicates in the list with differing serials - maybe! That'll at least save me scanning between each one! Thanks again! :)

**Comment by AbandonedCart** [comment]
Making them into separate bins is one option, but can easily get confusing.
 Changing the serial before saving will store a file with the new serial.

**Comment by AbandonedCart** [comment]
After the current new features get moving, i'll circle back to improving bulk handling for this. I've kept it open because the current options aren't the most efficient.

**Comment by AbandonedCart** [comment]
I think the best option here would be a fill option. That would be an option to select a single bin and make X copies with random serial numbers. That would allow one bin to exist without having to track all of the data, but still allow for making multiple copies with different serial numbers when writing it.

**Comment by hutje** [comment]
But why is it not possible to select multiple Amiibo's and write all Amiibo's in order to each bank?

**Comment by AbandonedCart** [comment]
It is...

**Comment by hutje** [comment]
> It is...

When press any Amiibo it wants to send only that amiibo to all banks

**Comment by hutje** [comment]
I found the problem. When enabling random serial, it only gives 1 Amiibo of course...

**Comment by random11x** [comment]
When I have random serial on and I choose "write to banks" the file selector pops up and doesnt let you choose anything. As soon as you go to choose a file it pops up with a dialog asking if you want to write the selected file (even though there are none selected) and then if you say yes it writes blank data to each bank.
