### ISSUE TITLE
Testing: Flask scan and refresh

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#484]
A full scan (inventory and active slot) is supposed to happen after each major change (add, delete). My testing has shown it works 99.9% of the time.

If anyone finds the list doesn't load or refresh, please send in a log and report it here.

**Comment by Miss1sle** [comment]
When trying to add or refresh my flask it never ends. The notification doesn't go away unless I swipe it off. 

When trying to add new amiibo the process never ends. 


TagMo - #4d669b2
Android S_V2 (12)

--------- beginning of main
06-02 09:43:33.787 10938 11851 W BluetoothLeService: FlaskRX 4,
06-02 09:43:33.799 10938 11851 W BluetoothLeService: FlaskRX  -
06-02 09:43:33.811 10938 11851 W BluetoothLeService: FlaskRX 4
06-02 09:43:33.821 10938 11851 W BluetoothLeService: FlaskRX , 
06-02 09:43:33.832 10938 11851 W BluetoothLeService: FlaskRX -,
06-02 09:43:33.844 10938 11851 W BluetoothLeService: FlaskRX  -
06-02 09:43:33.856 10938 11851 W BluetoothLeService: FlaskRX 3
06-02 09:43:33.865 10938 11851 W BluetoothLeService: FlaskRX 3,
06-02 09:43:33.877 10938 11851 W BluetoothLeService: FlaskRX  2
06-02 09:43:33.889 10938 11851 W BluetoothLeService: FlaskRX 1
06-02 09:43:33.899 10938 11851 W BluetoothLeService: FlaskRX , 
06-02 09:43:33.912 10938 11851 W BluetoothLeService: FlaskRX -2
06-02 09:43:33.922 10938 11851 W BluetoothLeService: FlaskRX 9
06-02 09:43:33.934 10938 11851 W BluetoothLeService: FlaskRX , 
06-02 09:43:33.946 10938 11851 W BluetoothLeService: FlaskRX -3
06-02 09:43:33.957 10938 11851 W BluetoothLeService: FlaskRX 1,
06-02 09:43:33.967 10938 11851 W BluetoothLeService: FlaskRX  
06-02 09:43:33.979 10938 11851 W BluetoothLeService: FlaskRX -3
06-02 09:43:33.990 10938 11851 W BluetoothLeService: FlaskRX , 
06-02 09:43:34.001 10938 11851 W BluetoothLeService: FlaskRX -
06-02 09:43:34.012 10938 11851 W BluetoothLeService: FlaskRX 10
06-02 09:43:34.022 10938 11851 W BluetoothLeService: FlaskRX [A[A[A[A[A[A[
06-02 09:43:34.033 10938 11851 W BluetoothLeService: FlaskRX A[A[A[A[A[A[A
06-02 09:43:34.044 10938 11851 W BluetoothLeService: FlaskRX [A[A[A[A[A[A[A
06-02 09:43:34.056 10938 11851 W BluetoothLeService: FlaskRX [A[A[A
[JExecuti
06-02 09:43:34.064 10938 10938 W RecyclerView: No adapter attached; skipping layout
06-02 09:43:34.067 10938 11851 W BluetoothLeService: FlaskRX on Interrupted
06-02 09:43:34.067 10938 11851 W BluetoothLeService: >tag
06-02 09:43:34.079 10938 11851 W BluetoothLeService: FlaskRX .startTagUpload(5tag
06-02 09:43:34.080 10938 10938 W RecyclerView: No adapter attached; skipping layout
06-02 09:43:34.090 10938 11851 W BluetoothLeService: FlaskRX .tagUploadChunk([4, 
06-02 09:43:34.097 10938 10938 W RecyclerView: No adapter attached; skipping layout
06-02 09:43:34.101 10938 11851 W BluetoothLeService: FlaskRX 62, 55, -123, -126, 
06-02 09:43:34.113 10938 11851 W BluetoothLeService: FlaskRX -5, 107, -127, -109,
06-02 09:43:34.113 10938 10938 W RecyclerView: No adapter attached; skipping layout
06-02 09:43:34.123 10938 11851 W BluetoothLeService: FlaskRX  72, 15, -32, -15, 1
06-02 09:43:34.131 10938 10938 W RecyclerView: No adapter attached; skipping layout
06-02 09:43:34.135 10938 11851 W BluetoothLeService: FlaskRX 6, -1, -18, -91, 0, 
06-02 09:43:34.146 10938 11851 W BluetoothLeService: FlaskRX 0, 0, 66, 36, -50, -
06-02 09:43:34.157 10938 11851 W BluetoothLeService: FlaskRX 117, 124, -97, -96, 
06-02 09:43:34.169 10938 11851 W BluetoothLeService: FlaskRX 27, 123, -79, 33, -1
06-02 09:43:34.180 10938 11851 W BluetoothLeService: FlaskRX 1, 83, -3, 24, -66, 
06-02 09:43:34.191 10938 11851 W BluetoothLeService: FlaskRX -73, -74, -17, -6, -
06-02 09:43:34.203 10938 10951 W BluetoothLeService: FlaskRX 109, 94, -55, 95, 9,
06-02 09:43:34.213 10938 10951 W BluetoothLeService: FlaskRX  -36, -20, -106, 50,
06-02 09:43:34.226 10938 10951 W BluetoothLeService: FlaskRX  30, -71, 38, -104, 
06-02 09:43:34.238 10938 10951 W BluetoothLeService: FlaskRX 87, -25, 125, 11, 9,
06-02 09:43:34.247 10938 10951 W BluetoothLeService: FlaskRX  -24, -97, 112, -69,
06-02 09:43:34.259 10938 10951 W BluetoothLeService: FlaskRX  43, -42, 112, -4, -
06-02 09:43:34.271 10938 10951 W BluetoothLeService: FlaskRX 50, -39, -124, -79, 
06-02 09:43:34.281 10938 10951 W BluetoothLeService: FlaskRX 42, 40, 125, 94, 119
06-02 09:43:34.293 10938 10951 W BluetoothLeService: FlaskRX , -110, 48, 76, 116,
06-02 09:43:34.304 10938 11851 W BluetoothLeService: FlaskRX  -32, 46, -73, -25, 
06-02 09:43:34.314 10938 10951 W BluetoothLeService: FlaskRX 73, 53, 8, 0, 0, 4, 
06-02 09:43:34.327 10938 10951 W BluetoothLeService: FlaskRX 15, 24, 2, 13, 18, 6
06-02 09:43:34.338 10938 10951 W BluetoothLeService: FlaskRX 8, 25, -77, 126, 102
06-02 09:43:34.348 10938 10951 W BluetoothLeService: FlaskRX , -63, -69, -43, 24,
06-02 09:43:34.361 10938 10951 W BluetoothLeService: FlaskRX  2, 69, 12, -53, 90,
06-02 09:43:34.372 10938 10951 W BluetoothLeService: FlaskRX  54, -41, 36, 90, 98
06-02 09:43:34.382 10938 10951 W BluetoothLeService: FlaskRX , 97, 110, 79, -52, 
06-02 09:43:34.394 10938 10951 W BluetoothLeService: FlaskRX 111, 29, 60, -99, -8
06-02 09:43:34.404 10938 10951 W BluetoothLeService: FlaskRX 6, 76, -85, 81, -36,
06-02 09:43:34.416 10938 10951 W BluetoothLeService: FlaskRX  -23, 75])
06-02 09:43:34.416 10938 10951 W BluetoothLeService: :tag.tag
06-02 09:43:34.428 10938 10951 W BluetoothLeService: FlaskRX UploadChunk([-127, -
06-02 09:43:34.438 10938 10951 W BluetoothLeService: FlaskRX 29, 63, 52, -73, 127
06-02 09:43:34.451 10938 10951 W BluetoothLeService: FlaskRX , -105, -87, -107, -
06-02 09:43:34.462 10938 10951 W BluetoothLeService: FlaskRX 1, 77, 54, -26, 91, 
06-02 09:43:34.472 10938 10951 W BluetoothLeService: FlaskRX 115, 69, 116, 120, 2
06-02 09:43:34.484 10938 10951 W BluetoothLeService: FlaskRX , 103, -37, -97, 58,
06-02 09:43:34.496 10938 10951 W BluetoothLeService: FlaskRX  -74, -4, 99, -103, 
06-02 09:43:34.506 10938 10951 W BluetoothLeService: FlaskRX -9, 36, 107, 119, 16
06-02 09:43:34.517 10938 10951 W BluetoothLeService: FlaskRX , 125, 94, -25, 22, 
06-02 09:43:34.529 10938 10951 W BluetoothLeService: FlaskRX -75, 0, -80, -98, 22
06-02 09:43:34.540 10938 10951 W BluetoothLeService: FlaskRX , -7, 54, 82, -74, -
06-02 09:43:34.563 10938 10951 W BluetoothLeService: FlaskRX 24, 42, -106, -79, -
06-02 09:43:34.563 10938 10951 W BluetoothLeService: FlaskRX 37, -95, 14, 49, 105
06-02 09:43:34.574 10938 10951 W BluetoothLeService: FlaskRX , -82, 47, -43, -58,
06-02 09:43:34.585 10938 11851 W BluetoothLeService: FlaskRX  -108, 93, 80, -60, 
06-02 09:43:34.607 10938 10951 W BluetoothLeService: FlaskRX 113, 71, -89, 64, 10
06-02 09:43:34.607 10938 10951 W BluetoothLeService: FlaskRX 9, 83, 27, -106, -55
06-02 09:43:34.620 10938 11851 W BluetoothLeService: FlaskRX , 37, -19, 4, 100, -
06-02 09:43:34.630 10938 10951 W BluetoothLeService: FlaskRX 46, -122, 41, -9, -3
06-02 09:43:34.642 10938 10951 W BluetoothLeService: FlaskRX 5, 42, -3, -4, -56, 
06-02 09:43:34.653 10938 10951 W BluetoothLeService: FlaskRX -48, -28, 29, -8, 89
06-02 09:43:34.663 10938 10951 W BluetoothLeService: FlaskRX , -83, 102, -14, 51,
06-02 09:43:34.675 10938 10951 W BluetoothLeService: FlaskRX  -73, -46, -63, 98, 
06-02 09:43:34.687 10938 11851 W BluetoothLeService: FlaskRX 22, 0, 37, 64, 51, -
06-02 09:43:34.697 10938 11851 W BluetoothLeService: FlaskRX 14, -6, -30, -48, 47
06-02 09:43:34.710 10938 11851 W BluetoothLeService: FlaskRX , -117, -89, -30, 11
06-02 09:43:34.720 10938 10951 W BluetoothLeService: FlaskRX , -5, -80, 2, 80, -3
06-02 09:43:34.730 10938 10951 W BluetoothLeService: FlaskRX 6, -77, 23, 63, 121,
06-02 09:43:34.743 10938 10951 W BluetoothLeService: FlaskRX  3, 50, 124, -79, -1
06-02 09:43:34.754 10938 10951 W BluetoothLeService: FlaskRX 7, 97, 78, 67])
06-02 09:43:34.754 10938 10951 W BluetoothLeService: :ta
06-02 09:43:34.765 10938 10951 W BluetoothLeService: FlaskRX g.tagUploadChunk([41
06-02 09:43:34.777 10938 10951 W BluetoothLeService: FlaskRX , -38, 74, 75, 100, 
06-02 09:43:34.788 10938 10951 W BluetoothLeService: FlaskRX -63, -86, -70, -9, -
06-02 09:43:34.799 10938 10951 W BluetoothLeService: FlaskRX 53, 121, 107, -22, 4
06-02 09:43:34.811 10938 10951 W BluetoothLeService: FlaskRX 5, -47, -39, -117, 1
06-02 09:43:34.833 10938 10951 W BluetoothLeService: FlaskRX 04, -128, 61, -36, -
06-02 09:43:34.844 10938 10951 W BluetoothLeService: FlaskRX 59, -122, -116, -98,
06-02 09:43:34.844 10938 10951 W BluetoothLeService: FlaskRX  88, 37, 46, -85, 10
06-02 09:43:34.855 10938 11851 W BluetoothLeService: FlaskRX 2, 109, 12, 37, -76,
06-02 09:43:34.867 10938 11851 W BluetoothLeService: FlaskRX  11, 83, 84, -76, 63
06-02 09:43:34.878 10938 11851 W BluetoothLeService: FlaskRX , 22, 34, -42, -3, -
06-02 09:43:34.888 10938 11851 W BluetoothLeService: FlaskRX 73, -78, 52, -66, -1
06-02 09:43:34.900 10938 11851 W BluetoothLeService: FlaskRX 9, -52, -42, 60, -56
06-02 09:43:34.912 10938 11851 W BluetoothLeService: FlaskRX , -63, -16, 68, -85,
06-02 09:43:34.922 10938 11851 W BluetoothLeService: FlaskRX  3, 63, 122, -116, -
06-02 09:43:34.934 10938 11851 W BluetoothLeService: FlaskRX 10, -100, 92, -45, 1
06-02 09:43:34.945 10938 11851 W BluetoothLeService: FlaskRX 09, 56, -78, 100, 71
06-02 09:43:34.956 10938 11851 W BluetoothLeService: FlaskRX , 54, 114, 46, -49, 
06-02 09:43:34.968 10938 11851 W BluetoothLeService: FlaskRX 123, 1, 74, 80, 76, 
06-02 09:43:34.979 10938 11851 W BluetoothLeService: FlaskRX -102, -8, -92, 9, -4
06-02 09:43:34.990 10938 11851 W BluetoothLeService: FlaskRX 2, 35, -83, -84, -50
06-02 09:43:35.001 10938 10951 W BluetoothLeService: FlaskRX , 47, 48, 119, 64, -
06-02 09:43:35.013 10938 10951 W BluetoothLeService: FlaskRX 57, 79, -65, 112, -1
06-02 09:43:35.024 10938 10951 W BluetoothLeService: FlaskRX 8, -68, 52, -4, 103,
06-02 09:43:35.036 10938 11851 W BluetoothLeService: FlaskRX  61, -79, 45, 2, -77
06-02 09:43:35.046 10938 11851 W BluetoothLeService: FlaskRX , -70, -65, -6, -58,
06-02 09:43:35.057 10938 11851 W BluetoothLeService: FlaskRX  90, -99, 111, -11, 
06-02 09:43:35.069 10938 11851 W BluetoothLeService: FlaskRX -34, 83, 97, -69, -2
06-02 09:43:35.080 10938 11851 W BluetoothLeService: FlaskRX 4, -46, 69, 43, 99, 
06-02 09:43:35.092 10938 11851 W BluetoothLeService: FlaskRX 94, 10, -65, 92, 64,
06-02 09:43:35.103 10938 10951 W BluetoothLeService: FlaskRX  -67])
06-02 09:43:35.103 10938 10951 W BluetoothLeService: :tag.tagUplo
06-02 09:43:35.113 10938 10951 W BluetoothLeService: FlaskRX adChunk([104, -18, -
06-02 09:43:35.125 10938 10951 W BluetoothLeService: FlaskRX 20, -22, -68, 27, -5
06-02 09:43:35.137 10938 11851 W BluetoothLeService: FlaskRX , -107, -90, -70, 35
06-02 09:43:35.147 10938 11851 W BluetoothLeService: FlaskRX , -15, -29, 91, 104,
06-02 09:43:35.160 10938 11851 W BluetoothLeService: FlaskRX  11, 30, 71, 51, 102
06-02 09:43:35.171 10938 11851 W BluetoothLeService: FlaskRX , 52, 70, -93, -11, 
06-02 09:43:35.181 10938 11851 W BluetoothLeService: FlaskRX 125, -100, -35, 74, 
06-02 09:43:35.193 10938 11851 W BluetoothLeService: FlaskRX 31, 126, -57, 106, -
06-02 09:43:35.205 10938 11851 W BluetoothLeService: FlaskRX 34, 42, 125, 13, 65,
06-02 09:43:35.216 10938 11851 W BluetoothLeService: FlaskRX  -36, 100, 115, -90,
06-02 09:43:35.227 10938 11851 W BluetoothLeService: FlaskRX  52, -55, -44, 108, 
06-02 09:43:35.238 10938 11851 W BluetoothLeService: FlaskRX 61, 106, -67, 95, -5
06-02 09:43:35.249 10938 11851 W BluetoothLeService: FlaskRX 3, -16, 32, 86, 98, 
06-02 09:43:35.260 10938 11851 W BluetoothLeService: FlaskRX -24, -59, 120, -80, 
06-02 09:43:35.271 10938 11851 W BluetoothLeService: FlaskRX -83, 50, -83, 5, 74,
06-02 09:43:35.282 10938 11851 W BluetoothLeService: FlaskRX  117, 45, 98, -36, 8
06-02 09:43:35.294 10938 11851 W BluetoothLeService: FlaskRX 5, 42, -80, -114, 35
06-02 09:43:35.305 10938 11851 W BluetoothLeService: FlaskRX , -3, 50, 1, -96, 30
06-02 09:43:35.317 10938 11851 W BluetoothLeService: FlaskRX , -18, -75, -50, 42,
06-02 09:43:35.328 10938 11851 W BluetoothLeService: FlaskRX  -13, 119, 49, -92, 
06-02 09:43:35.339 10938 11851 W BluetoothLeService: FlaskRX -114, 94, 16, -9, 14
06-02 09:43:35.351 10938 11851 W BluetoothLeService: FlaskRX , -65, -45, -83, 86,
06-02 09:43:35.362 10938 11851 W BluetoothLeService: FlaskRX  -57, -89, 30, 38, -
06-02 09:43:35.372 10938 11851 W BluetoothLeService: FlaskRX 25, -102, 28, -40, -
06-02 09:43:35.396 10938 11851 W BluetoothLeService: FlaskRX 89, 126, -58, 25, -2
06-02 09:43:35.396 10938 10951 W BluetoothLeService: FlaskRX 1, -114, 123, -86, -
06-02 09:43:35.407 10938 10951 W BluetoothLeService: FlaskRX 3, 86, 20, 115, -116
06-02 09:43:35.418 10938 10951 W BluetoothLeService: FlaskRX , -12, -83, -20, 56,
06-02 09:43:35.429 10938 10951 W BluetoothLeService: FlaskRX  6, -31, 49, 8, -126
06-02 09:43:35.440 10938 10951 W BluetoothLeService: FlaskRX , 77, 126, -76, 67])
06-02 09:43:35.454 10938 10951 W BluetoothLeService: FlaskRX 
06-02 09:43:35.454 10938 10951 W BluetoothLeService: :tag.tagUploadChun
06-02 09:43:35.462 10938 10951 W BluetoothLeService: FlaskRX k([-30, 11, -125, -5
06-02 09:43:35.474 10938 10951 W BluetoothLeService: FlaskRX 2, -87, 15, -37, -58
06-02 09:43:35.484 10938 10951 W BluetoothLeService: FlaskRX , 1, 0, 15, -67, 0, 
06-02 09:43:35.496 10938 10951 W BluetoothLeService: FlaskRX 0, 0, 4, 95, 0, 0, 0
06-02 09:43:35.507 10938 10951 W BluetoothLeService: FlaskRX , 0, 0, 0, 0, 0, 0, 
06-02 09:43:35.519 10938 10951 W BluetoothLeService: FlaskRX 0, 0, 0, 0, 0, 0, 0,
06-02 09:43:35.530 10938 11851 W BluetoothLeService: FlaskRX  0, 0, 0, 0, 0, 0, 0
06-02 09:43:35.541 10938 11851 W BluetoothLeService: FlaskRX , 0, 0, 0, 0, 0, 0, 
06-02 09:43:35.552 10938 11851 W BluetoothLeService: FlaskRX 0, 0, 0, 0, 0, 0, 0,
06-02 09:43:35.564 10938 11851 W BluetoothLeService: FlaskRX  0, 0, 0, 0, 0, 0, 0
06-02 09:43:35.577 10938 10951 W BluetoothLeService: FlaskRX , 0, 0, 0, 0, 0, 0, 
06-02 09:43:35.585 10938 11851 W BluetoothLeService: FlaskRX 0, 0, 0, 0, 0, 0, 0,
06-02 09:43:35.597 10938 10951 W BluetoothLeService: FlaskRX  0, 0, 0, 0, 0, 0, 0
06-02 09:43:35.608 10938 10951 W BluetoothLeService: FlaskRX , 0, 0, 0, 0, 0, 0, 
06-02 09:43:35.630 10938 10951 W BluetoothLeService: FlaskRX 0, 0, 0, 0, 0, 0, 0,
06-02 09:43:35.631 10938 10951 W BluetoothLeService: FlaskRX  0, 0, 0, 0, 0, 0, 0
06-02 09:43:35.642 10938 11851 W BluetoothLeService: FlaskRX , 0, 0, 0, 0, 0, 0, 
06-02 09:43:35.649 10938 10938 D BluetoothAdapter: isLeEnabled(): ON
06-02 09:43:35.649 10938 10938 D BluetoothLeScanner: could not find callback wrapper
06-02 09:43:35.649 10938 10938 D BluetoothGatt: cancelOpen() - device: CF:B5:2D:84:63:85
06-02 09:43:35.652 10938 11851 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=CF:B5:2D:84:63:85
06-02 09:43:35.653 10938 11851 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=CF:B5:2D:84:63:85
06-02 09:43:35.653 10938 11851 D BluetoothGatt: discoverServices() - device: CF:B5:2D:84:63:85
06-02 09:43:35.661 10938 11810 D OpenGLRenderer: endAllActiveAnimators on 0xb4000073ff5fea60 (RippleDrawable) with handle 0xb40000730f5fbb70
06-02 09:43:35.667 10938 10938 D BluetoothGatt: close()
06-02 09:43:35.668 10938 10938 D BluetoothGatt: unregisterApp() - mClientIf=8
06-02 09:43:37.234 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:37.234 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:37.234 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:37.234 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:38.306 10938 10938 I ContentCaptureHelper: Setting logging level to OFF
06-02 09:43:38.489 10938 11810 D OpenGLRenderer: endAllActiveAnimators on 0xb4000073ff698580 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000730f603100
06-02 09:43:50.288 10938 12239 I OpenGLRenderer: Davey! duration=2431ms; Flags=1, FrameTimelineVsyncId=2166448, IntendedVsync=47240878298030, Vsync=47240878298030, InputEventId=0, HandleInputStart=47240891979202, AnimationStart=47240891981285, PerformTraversalsStart=47240892296129, DrawStart=47240915640454, FrameDeadline=47240911464696, FrameInterval=47240891973368, FrameStartTime=16666666, SyncQueued=47240917538006, SyncStart=47240921893632, IssueDrawCommandsStart=47240922350350, SwapBuffers=47240925749934, FrameCompleted=47243314261110, DequeueBufferDuration=20053, QueueBufferDuration=800417, GpuCompleted=47243314261110, SwapBuffersCompleted=47240927024726, DisplayPresentTime=0, 
06-02 09:43:50.300 10938 12239 I OpenGLRenderer: Davey! duration=2438ms; Flags=0, FrameTimelineVsyncId=2166451, IntendedVsync=47240894918304, Vsync=47240928251636, InputEventId=0, HandleInputStart=47240934982748, AnimationStart=47240934983633, PerformTraversalsStart=47240935172748, DrawStart=47240939150196, FrameDeadline=47240944751636, FrameInterval=47240934980143, FrameStartTime=16666666, SyncQueued=47240939339154, SyncStart=47240939426706, IssueDrawCommandsStart=47240939530300, SwapBuffers=47240940788998, FrameCompleted=47243333123611, DequeueBufferDuration=11302, QueueBufferDuration=426354, GpuCompleted=47243333123611, SwapBuffersCompleted=47240941455613, DisplayPresentTime=0, 
06-02 09:43:52.511 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:52.511 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:52.511 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 09:43:52.511 10938 10938 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
