### ISSUE TITLE
Cannot scan N2 Elite

### ISSUE THREAD

**Issue by CAYCE-VII** [HiddenRamblings/TagMo#486]
Not sure why the app didn't grab my logcat.

**Comment by CAYCE-VII** [comment]
![Screenshot_20220602-172700.png](https://user-images.githubusercontent.com/45942996/171761650-40996c43-5044-4e16-b14f-4574b7fd7978.png)

**Comment by CAYCE-VII** [comment]
TagMo - #4d669b2
Android S_V2 (12)

--------- beginning of main
06-02 17:31:39.634 15314 15314 D InputMethodManager: showSoftInput() view=com.google.android.material.textfield.TextInputEditText{2cd90bd VFED.VCL. .F.P..ID 0,0-1272,231 #7f09004c app:id/air_inputDescription aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
06-02 17:31:39.645 15314 15314 I AssistStructure: Flattened final assist data: 5100 bytes, containing 1 windows, 27 views
06-02 17:31:39.690 15314 15314 D InsetsController: show(ime(), fromIme=true)
06-02 17:31:53.489 15314 15339 D OpenGLRenderer: endAllActiveAnimators on 0xb400007e215d1e60 (RippleDrawable) with handle 0xb400007d31515b90
06-02 17:32:51.603 15314 20198 W IOException: java.io.IOException: /storage/emulated/0/Documents/key_retail.bin size: 160, Expected: 532
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1315)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-02 17:32:51.603 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-02 17:32:51.603 15314 20198 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 17:32:51.603 15314 20198 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 17:32:51.603 15314 20198 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-02 17:32:52.311 15314 20198 W IOException: java.io.IOException: /storage/emulated/0/.$Trash$/.$Content$/.4106865493382056216_0/Amiibo Bin Dump/key_retail.bin size: 160, Expected: 532
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1315)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-02 17:32:52.311 15314 20198 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-02 17:32:52.311 15314 20198 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 17:32:52.311 15314 20198 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 17:32:52.311 15314 20198 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-02 17:32:53.762 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:32:53.763 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:32:53.763 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:32:53.763 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:32:55.486 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:55.487 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.062 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.077 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.085 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.094 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.112 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.112 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:56.137 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.568 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.587 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.611 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.635 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.645 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.660 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.678 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.695 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.720 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.735 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.753 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:32:58.778 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:00.661 15314 15314 I WebViewFactory: Loading com.google.android.webview version 101.0.4951.61 (code 495106134)
06-02 17:33:00.689 15314 15314 I cr_WVCFactoryProvider: Loaded version=101.0.4951.61 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
06-02 17:33:00.697 15314 15314 I cr_LibraryLoader: Successfully loaded native library
06-02 17:33:00.697 15314 15314 I cr_CachingUmaRecorder: Flushed 9 samples from 9 histograms.
06-02 17:33:00.859 15314 20277 D libEGL  : loaded /vendor/lib64/egl/libGLES_mali.so
06-02 17:33:00.870 15314 15314 I ContentCaptureHelper: Setting logging level to OFF
06-02 17:33:00.871 15314 20245 W cr_media: Requires BLUETOOTH permission
06-02 17:33:00.901 15314 20277 D mali_cmarp_predictor: checking cmar_predictor for com.hiddenramblings.tagmo
06-02 17:33:00.929 15314 20277 D mali_cmarp_predictor: checking cmar_predictor for com.hiddenramblings.tagmo
06-02 17:33:01.002 15314 15314 I ContentCaptureHelper: Setting logging level to OFF
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.454 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:33.602 15314 20370 W IOException: java.io.IOException: /storage/emulated/0/Documents/key_retail.bin size: 160, Expected: 532
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1315)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-02 17:33:33.602 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-02 17:33:33.602 15314 20370 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 17:33:33.602 15314 20370 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 17:33:33.602 15314 20370 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-02 17:33:34.184 15314 20370 W IOException: java.io.IOException: /storage/emulated/0/.$Trash$/.$Content$/.4106865493382056216_0/Amiibo Bin Dump/key_retail.bin size: 160, Expected: 532
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1315)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-02 17:33:34.184 15314 20370 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-02 17:33:34.184 15314 20370 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-02 17:33:34.184 15314 20370 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-02 17:33:34.184 15314 20370 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-02 17:33:35.066 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.067 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.068 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:35.068 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.062 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.071 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.087 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.099 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.105 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.113 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.121 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.129 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.138 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.146 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.155 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.163 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.172 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:38.188 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:39.535 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:39.535 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:40.249 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:40.249 15314 15314 E ramblings.tagm: Invalid ID 0x00000000.
06-02 17:33:41.889 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:41.889 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:41.889 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:41.889 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:52.411 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:52.411 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:52.411 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-02 17:33:52.411 15314 15314 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()

**Comment by AbandonedCart** [comment]
Did you enable N2 in settings?

**Comment by CAYCE-VII** [comment]
Yes, it's shown as enabled in the video link I posted. I have also cleared appdata, and re-granted permissions and re-enabled N2 in settings, restarted my device, locked and unlocked the N2 in the N2 app itself.

I looked at these closed issues as well:

https://github.com/HiddenRamblings/TagMo/issues/409
https://github.com/HiddenRamblings/TagMo/issues/404 - seems the closest
https://github.com/HiddenRamblings/TagMo/issues/368
https://github.com/HiddenRamblings/TagMo/issues/359
https://github.com/HiddenRamblings/TagMo/issues/252

**Comment by CAYCE-VII** [comment]
Hmm, after some fiddling around, that error happens when you scan the N2 while on an empty bank. Luckily I still had a Bank that had data on it, after setting that as the active bank in the N2 app itself, hopping over to Tagmo and scanning again, it pulls up the file picker

**Comment by CAYCE-VII** [comment]
No worries, had my N2 had no banks with data on it I wouldn't have been able to get around it. Is it notated or documented anywhere that the N2 can't scan on an empty bank and I just missed it? Also you can close this issue.

**Comment by AbandonedCart** [comment]
There is the initial inconvenience of confirming it's an N2 when the active bank is empty, but only when entering the bank browser. It will skip verifying again until the window is closed.
