### ISSUE TITLE
File browser not refreshing as I navigate folders. 

### ISSUE THREAD

**Issue by Miss1sle** [HiddenRamblings/TagMo#492]
Not sure how to describe this, but as I navigate folders I have to enter the folder, close the folder navigation, drag down to refresh the screen and then it'll update where I am, then navigate to the next folder.

TagMo - #80a6853
Android S_V2 (12)

--------- beginning of crash
06-08 11:57:19.569 15067 15067 E AndroidRuntime: FATAL EXCEPTION: main
06-08 11:57:19.569 15067 15067 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 15067
06-08 11:57:19.569 15067 15067 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.hiddenramblings.tagmo.UpdateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at com.hiddenramblings.tagmo.UpdateReceiver.onReceive(UpdateReceiver.java:25)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
06-08 11:57:19.569 15067 15067 E AndroidRuntime: 	... 9 more
06-09 13:38:19.167 14545 14545 E AndroidRuntime: FATAL EXCEPTION: main
06-09 13:38:19.167 14545 14545 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 14545
06-09 13:38:19.167 14545 14545 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.hiddenramblings.tagmo.UpdateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at com.hiddenramblings.tagmo.UpdateReceiver.onReceive(UpdateReceiver.java:26)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
06-09 13:38:19.167 14545 14545 E AndroidRuntime: 	... 9 more
--------- beginning of main
06-11 19:22:14.530 19144 19144 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
06-11 19:22:14.531 19144 19144 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:14.557 19144 19144 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10481; state: ENABLED
06-11 19:22:14.581 19144 19144 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:14.582 19144 19144 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:14.676 19144 19144 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
06-11 19:22:14.678 19144 19144 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:14.679 19144 19144 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
06-11 19:22:14.679 19144 19144 D RenderScript HIDL Adaptation: Using Fallback Path.
06-11 19:22:14.718 19144 19144 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:14.718 19144 19144 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:14.734 19144 19144 I ContentCaptureHelper: Setting logging level to OFF
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: QUALCOMM build                   : 85da404, I46ff5fc46f
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Build Date                       : 11/30/20
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Local Branch                     : promo490_3_Google
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Remote Branch                    : 
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Remote Branch                    : 
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Reconstruct Branch               : 
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
06-11 19:22:14.793 19144 19164 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-11 19:22:14.794 19144 19164 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:14.798 19144 19164 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
06-11 19:22:14.801 19144 19164 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
06-11 19:22:14.801 19144 19164 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
06-11 19:22:14.832 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:23.922 19144 19144 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10481; state: ENABLED
06-11 19:22:24.149 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:27.298 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:27.299 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:27.299 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:27.299 19144 19144 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:29.233 19144 19164 D OpenGLRenderer: endAllActiveAnimators on 0xb400007903923cd0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb400007813862510
06-11 19:22:30.050 19144 19214 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10481; state: ENABLED
06-11 19:22:34.539 19344 19344 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
06-11 19:22:34.541 19344 19344 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:34.596 19344 19344 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10481; state: ENABLED
06-11 19:22:34.664 19344 19344 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:34.664 19344 19344 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:34.851 19344 19344 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
06-11 19:22:34.852 19344 19344 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:34.852 19344 19344 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
06-11 19:22:34.852 19344 19344 D RenderScript HIDL Adaptation: Using Fallback Path.
06-11 19:22:34.864 19344 19344 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:34.865 19344 19344 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:34.879 19344 19344 I ContentCaptureHelper: Setting logging level to OFF
06-11 19:22:34.904 19344 19344 D AndroidRuntime: Shutting down VM
06-11 19:22:34.904 19344 19344 E AndroidRuntime: FATAL EXCEPTION: main
06-11 19:22:34.904 19344 19344 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 19344
06-11 19:22:34.904 19344 19344 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.hiddenramblings.tagmo.UpdateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at com.hiddenramblings.tagmo.UpdateReceiver.onReceive(UpdateReceiver.java:26)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
06-11 19:22:34.904 19344 19344 E AndroidRuntime: 	... 9 more
06-11 19:22:34.904 19344 19344 E UncaughtException: java.lang.RuntimeException: Unable to start receiver com.hiddenramblings.tagmo.UpdateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.os.Looper.loopOnce(Looper.java:201)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.os.Looper.loop(Looper.java:288)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-11 19:22:34.904 19344 19344 E UncaughtException: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at com.hiddenramblings.tagmo.UpdateReceiver.onReceive(UpdateReceiver.java:26)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
06-11 19:22:34.904 19344 19344 E UncaughtException: 	... 9 more
06-11 19:22:34.904 19344 19344 W System.err: java.lang.RuntimeException: Unable to start receiver com.hiddenramblings.tagmo.UpdateReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4384)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.os.Looper.loop(Looper.java:288)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
06-11 19:22:34.904 19344 19344 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-11 19:22:34.904 19344 19344 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-11 19:22:34.904 19344 19344 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
06-11 19:22:34.904 19344 19344 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getSchemeSpecificPart()' on a null object reference
06-11 19:22:34.904 19344 19344 W System.err: 	at com.hiddenramblings.tagmo.UpdateReceiver.onReceive(UpdateReceiver.java:26)
06-11 19:22:34.904 19344 19344 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4375)
06-11 19:22:34.904 19344 19344 W System.err: 	... 9 more
06-11 19:22:34.924 19344 19344 I ramblings.tagm: System.exit called, status: 1
06-11 19:22:34.924 19344 19344 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
06-11 19:22:38.419 19474 19474 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
06-11 19:22:38.421 19474 19474 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:38.431 19474 19474 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10481; state: ENABLED
06-11 19:22:38.442 19474 19474 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:38.443 19474 19474 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-11 19:22:38.523 19474 19474 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
06-11 19:22:38.523 19474 19474 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:38.523 19474 19474 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
06-11 19:22:38.523 19474 19474 D RenderScript HIDL Adaptation: Using Fallback Path.
06-11 19:22:38.531 19474 19474 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:38.531 19474 19474 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-11 19:22:38.543 19474 19474 I ContentCaptureHelper: Setting logging level to OFF
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: QUALCOMM build                   : 85da404, I46ff5fc46f
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Build Date                       : 11/30/20
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.01
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Local Branch                     : promo490_3_Google
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Remote Branch                    : 
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Remote Branch                    : 
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Reconstruct Branch               : 
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
06-11 19:22:38.607 19474 19491 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-11 19:22:38.608 19474 19491 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
06-11 19:22:38.616 19474 19491 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
06-11 19:22:38.620 19474 19491 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
06-11 19:22:38.620 19474 19491 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
06-11 19:22:38.922 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:40.248 19474 19523 W Filter  : An exception occured during performFiltering()!
06-11 19:22:40.248 19474 19523 W Filter  : java.util.ConcurrentModificationException
06-11 19:22:40.248 19474 19523 W Filter  : 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
06-11 19:22:40.248 19474 19523 W Filter  : 	at com.hiddenramblings.tagmo.adapter.BrowserAmiibosAdapter$AmiiboFilter.performFiltering(BrowserAmiibosAdapter.java:197)
06-11 19:22:40.248 19474 19523 W Filter  : 	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:236)
06-11 19:22:40.248 19474 19523 W Filter  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-11 19:22:40.248 19474 19523 W Filter  : 	at android.os.Looper.loopOnce(Looper.java:201)
06-11 19:22:40.248 19474 19523 W Filter  : 	at android.os.Looper.loop(Looper.java:288)
06-11 19:22:40.248 19474 19523 W Filter  : 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-11 19:22:45.095 19474 19474 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10481; state: ENABLED
06-11 19:22:46.004 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:52.150 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:53.687 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:53.687 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:53.687 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:53.687 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:55.265 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:57.152 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:57.152 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:57.152 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:57.152 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.172 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.173 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.173 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.173 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.173 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:22:58.173 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:23:03.070 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.070 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.070 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.070 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.071 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.780 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.858 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:03.958 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.075 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.126 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.208 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.328 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.859 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.892 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.925 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.958 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:04.976 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:05.043 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:06.881 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:06.881 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:06.881 19474 19474 E ramblings.tagm: Invalid ID 0x00000000.
06-11 19:23:11.375 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:23:11.376 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:23:11.376 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-11 19:23:11.376 19474 19474 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()

**Comment by AbandonedCart** [comment]
Fixed by 7ab489d275d10ec182e05bef5636705e572c39eb
