### ISSUE TITLE
Only With the Etoile amiibo

### ISSUE THREAD

**Issue by Ericzion1999** [HiddenRamblings/TagMo#500]
when I upload Etoile to the flask, the amiibo is shown to me like this, but the amiibo is on the flask
![IMG_20220617_172517](https://user-images.githubusercontent.com/82835573/174330095-f242d582-38d1-4808-8eaf-b4aeadc90bfe.jpg)

**Comment by AbandonedCart** [comment]
There is no way to debug that based on what's provided.

**Comment by AbandonedCart** [comment]
A bunch of Unicode support was added that seems to have fixed the issue.
