### ISSUE TITLE
[Bug]: NFC interface is null

### ISSUE THREAD

**Issue by EndahCookieh** [HiddenRamblings/TagMo#507]
### Issue Description

Attempt to invoke virtual method 'voidcom.hiddinramblings.tagmo.nfctech.NTAG215.connect()' on a null object reference.

Every time i scan or try to write into a tag this error pops up , could I have a fix?

Thank you

### Logcat Output

```shell
Attempt to invoke virtual method 'voidcom.hiddinramblings.tagmo.nfctech.NTAG215.connect()' on a null object reference.

Every time i scan or try to write into a tag this error pops up , could I have a fix?

Thank you
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
The phone probably doesn't support NFC. It's hard to say based on just an error message.

**Comment by AbandonedCart** [comment]
Make sure to update.

**Comment by EndahCookieh** [comment]
Update, The issue was with the tags, I bought new ones and it seemed to work , just from a different provider
