### ISSUE TITLE
Update prompt

### ISSUE THREAD

**Issue by serratedhalo** [HiddenRamblings/TagMo#523]
I'm on github version 2.7.8 which appears to be the most recent stable version.  Each time I open the app I get a prompt "Do you want to update this app?"  I tried toggling "stable update checks" checked and unchecked in the settings menu but they both result in the same prompt when the app is opened.

**Comment by AbandonedCart** [comment]
2.7.8 is like a year old.

**Comment by serratedhalo** [comment]
Ah on the releases tab it looks like the most current stable version, but I'm guessing that's because the app store version just updates in the top "master" slot?

**Comment by AbandonedCart** [comment]
Google Play requires each new release have a separate incremental version number, so GitHub uses the hash of the commit for versioning.

**Comment by serratedhalo** [comment]
Makes sense, thanks for the great app.
