### ISSUE TITLE
User's Guide for latest version of TagMo

### ISSUE THREAD

**Issue by 070221090** [HiddenRamblings/TagMo#524]
Where can I find User's Guide for latest version of TagMo?

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo#instructions
https://github.com/HiddenRamblings/TagMo/wiki#instructions
https://play.google.com/store/apps/details?id=com.hiddenramblings.tagmo.eightbit -> Developer contact -> Website
Opening the app, clicking the far right tab labeled "Guides"

If you still haven't found it, you might want to start buying your tags premade.

**Comment by 070221090** [comment]
Can you make a Youtube video tutorial explaining how to use the latest TagMo apk version (stable)?

**Comment by AbandonedCart** [comment]
No. There simply isn't the time on top of everything else.
