### ISSUE TITLE
[Bug]: some class lose

### ISSUE THREAD

**Issue by iamzzj** [HiddenRamblings/TagMo#533]
### Issue Description

com.hiddenramblings.tagmo.GlideApp;
com.hiddenramblings.tagmo.settings.Preferences_;

please add to git

### Logcat Output

```shell
class lose
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
Glide is a library, so there is no local GlideApp and Preferences_ is a reference to Preferences that is already included.
