### ISSUE TITLE
Samsung Galaxy S6 Edge Plus Wont Write

### ISSUE THREAD

**Issue by Murkdeth** [HiddenRamblings/TagMo#55]
Ive tried every build of Tagmo and still havent been able to get past the error message it says done before the scan starts and gives an error message when it tries to write

**Comment by aruur** [comment]
Same issue here, with my Nexus 6p

**Comment by HiddenRambler** [comment]
Could one of you please give me a logcat output. it would help greatly. Without one i have no way to reproduce this issue.

**Comment by HiddenRambler** [comment]
Could you check the latest version (2.4.3) hoping it fixed this issue as well.

**Comment by Murkdeth** [comment]
How do I retrieve the logcat output for you? 2.4.3 didn't work either unfortunately I really appreciate your help and effort though thanks!

**Comment by HiddenRambler** [comment]
You can try the test version in this comment: https://github.com/HiddenRambler/TagMo/issues/54#issuecomment-315600206

**Comment by HiddenRambler** [comment]
Can you check the solution that worked for #54

**Comment by RRMalone** [comment]
I have the normal GS6 Edge and it will not work on my phone, I've used every version and every file manager. I tried to just use my PowerSave and unfortunately there's not a clear way to write using that.

**Comment by HiddenRambler** [comment]
@RRMalone, What exactly is happenning? do you see an error?

**Comment by RRMalone** [comment]
It just says failed, I downloaded the right files and everything but it just won't work.



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by HiddenRambler** [comment]
Please:
1) Use the latest version (new release as of yesterday)
2) Do a scan tag and scan an existing tag.
3) Generate a logcat (there is a menu option for it)
4) Attach the generated logcat txt file to the ticket.

**Comment by Murkdeth** [comment]
[tagmo_logcat.txt](https://github.com/HiddenRamblings/TagMo/files/1194453/tagmo_logcat.txt)

**Comment by Murkdeth** [comment]
Hi sorry for the late reply I used the most recent version 2.5 to generate the logcat. Im still running into the same issue as before on this build. Thanks for your time I really appreciate this project

**Comment by HiddenRambler** [comment]
The error in the log looks similar to what one gets when wrong type of tags are used. 

Could you install https://play.google.com/store/apps/details?id=com.nxp.taginfolite app and scan your tag with that and tell us if it clearly says NTAG215 in the app or something different like NTAG213/NTAG216.

**Comment by RRMalone** [comment]
It's definitely not the tags, they're 215's. With this many not working on the galaxy's it has to be the app. I used actual Amiibo, copies and downloaded tags.



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by HiddenRambler** [comment]
Actually a lot of of complaints on galaxy was resolved. There was a recent ticket where the guy recieved mixed tags from a seller with both 215's and 216.

**Comment by RRMalone** [comment]
I didn't say Galaxy's won't work, I said there's a lot of people saying it doesn't work and most the ones I see are Galaxy's!
That would be a problem with the tags though, not the phone or app.
There were a few people that said the newer ones cut out a piece of code but u can't even view mine, nothing on it will work.


Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by Murkdeth** [comment]
![screenshot_20170802-142856](https://user-images.githubusercontent.com/30148745/28888595-291762ae-778f-11e7-96b9-587b264e4a6e.png)

**Comment by HiddenRambler** [comment]
That indeed looks like the correct tag type. Just to check one more error condition could you do a full scan on the nxp app and send a screenshot of the hex dump that is shown ("Memory Content")

Or after the full scan you can use the "share" option to export the xml/text of the output.

**Comment by Murkdeth** [comment]
![screenshot_20170802-142856](https://user-images.githubusercontent.com/30148745/28892064-a6a7cfe6-779a-11e7-8f97-60ce276b376a.png)

**Comment by Murkdeth** [comment]
![screenshot_20170802-154840](https://user-images.githubusercontent.com/30148745/28892103-bbd65612-779a-11e7-8bbe-eaecb9cbcbf6.png)

**Comment by Murkdeth** [comment]
![screenshot_20170802-154845](https://user-images.githubusercontent.com/30148745/28892115-c91c5fc4-779a-11e7-8bd6-2d9244e64ae6.png)

**Comment by Murkdeth** [comment]
![screenshot_20170802-154858](https://user-images.githubusercontent.com/30148745/28892126-d5d89408-779a-11e7-95d8-5ab28a222624.png)

**Comment by Murkdeth** [comment]
![screenshot_20170802-154912](https://user-images.githubusercontent.com/30148745/28892147-e4e25510-779a-11e7-89e7-787c5c796254.png)

**Comment by Murkdeth** [comment]
![screenshot_20170802-154919](https://user-images.githubusercontent.com/30148745/28892164-f5b44e16-779a-11e7-8541-60df330e5f95.png)

**Comment by Murkdeth** [comment]
Hope that's the right thing

**Comment by Murkdeth** [comment]
i bought the tags off aliexpress i guess they sent me bum tags. I only tried to write to one of the 15 but unfortunately the all show the lock and the 0x00 bytes so i guess im screwed.. lol I appreciate your help anyways thanks man

**Comment by RRMalone** [comment]
I ordered some through AliExpress too but mine are unlocked and have 540



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by RRMalone** [comment]
504*



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by HiddenRambler** [comment]
@RRMalone still waiting for the reply to my previous post.

Please:

    Use the latest version (new release as of yesterday)
    Do a scan tag and scan an existing tag.
    Generate a logcat (there is a menu option for it)
    Attach the generated logcat txt file to the ticket.

**Comment by Bombastisch** [comment]
Will we get any response? Help is appreciated ;)

**Comment by RRMalone** [comment]
I just used my GS3 and it works fine. My 6 edge won't work. Apparently it cuts out part of the code. I saw done images online and one of the numbers kept not showing up on Android 7.0



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by HiddenRambler** [comment]
@RRMalone Could you submit a debug log? I'm sure we could get it to work. I've tested with mulitple 7.0 androids and it works.

@Bombastisch Welcome back ;)

**Comment by Bombastisch** [comment]
Haha, I am still in Cincinnati, OH for the next to weeks, before I fly back to Germany. But I'll just moderate the issue thread from here! ;)

**Comment by RRMalone** [comment]
I tried to a couple times a few weeks ago but I can try again and see if it'll let me.



Sent from my U.S. Cellular® Smartphone


-------- Original message --------

**Comment by Bombastisch** [comment]
Help is appreciated! ;)

**Comment by RRMalone** [comment]
I finally got the GS6 to work using an old version (4.2) and now I can't get the S8 to load the keys and I tried every single version multiple times.

**Comment by Bombastisch** [comment]
This is an old thread now.
Could you please describe your problem again and include a logcat? 
I am glad we finally hear something on this thread again.

**Comment by Bombastisch** [comment]
Closing due to a lack of feedback. If your problem still occurs please open a new issue thread. We developers are just simple persons. We don't own every kind of phone on this earth. If something isn't working correctly we need your help to work closely with us together to fix this problem for all of us. Thank you. :)
