### ISSUE TITLE
Possible Huawei Android 10 incompatibility

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#567]
Seem to be getting a lot of beta feedback from Google about issues from Huawei users on Android 10, but none have actually submitted logs and the reviews are somewhat vague. The general idea is that apparently it freezes. For now, I am posting this issue in case someone with a Huawei on Android 10 can provide more information.

**Comment by ZIK999** [comment]
I'm on Asus ROG5 (Android 12), app freezes every time after 5-10 seconds after start. Can't use it at all.
Sent logs through google form.

**Comment by AbandonedCart** [comment]
Doesn't appear to be a hardware issue and there is no evidence to suggest it is ongoing, so this is being closed in favor of individual reports.
