### ISSUE TITLE
[Bug]: Tagmo keeps freezing

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#575]
### Issue Description

Hello I just updated and the new version loads and then after about 10 seconds it just freezes and I can't do anything sorry I don't know how to make the log file because it froze.  Thank you.

### Logcat Output

```shell
I don't know how to make one when it freezes
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Closing as duplicate of https://github.com/HiddenRamblings/TagMo/issues/574

**Comment by AbandonedCart** [comment]
That's fine. Android 13 is not widely distributed yet, but the chances it is unrelated are like 2%.
