### ISSUE TITLE
[Bug]: Failed to decrypt tag data

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#576]
### Issue Description

Failed to decrypt tag data

### Logcat Output

```shell
09-28 21:43:30.295 16571 17902 W Exception: java.lang.Exception: Failed to decrypt tag data
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.amiibo.KeyManager.decrypt(KeyManager.java:130)
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagWriter.writeToTagAuto(TagWriter.java:93)
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.NfcActivity.onTagDiscovered(NfcActivity.java:379)
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.NfcActivity.lambda$onNewIntent$0(NfcActivity.java:249)
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.NfcActivity.$r8$lambda$vP5NXNBqg2kDV8eg_wytd2g-zlQ(Unknown Source:0)
09-28 21:43:30.295 16571 17902 W Exception: 	at com.hiddenramblings.tagmo.NfcActivity$$ExternalSyntheticLambda16.run(Unknown Source:4)
09-28 21:43:30.295 16571 17902 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-28 21:43:30.295 16571 17902 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-28 21:43:30.295 16571 17902 W Exception: 	at java.lang.Thread.run(Thread.java:1012)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Fixed by 1bb41af7250d33bf189c3e22cd1d349c8e2a76b1

**Comment by AbandonedCart** [comment]
<img width="1114" alt="Failed to decrypt tag dat" src="https://user-images.githubusercontent.com/1173913/193487849-d745d6b1-4db7-4a55-983c-39cced283651.png">

Google Play review is still pending, but there is no way to actually notify anyone before they send feedback.

**Comment by AbandonedCart** [comment]
The update finally hit some time early this morning.

**Comment by DarkSkull91** [comment]
I continue to get this error. What I need to do?

**Comment by AbandonedCart** [comment]
Update

**Comment by DarkSkull91** [comment]
is the version on the Google Play store good?

**Comment by AbandonedCart** [comment]
3.2.0 or newer was after the issue was fixed.

**Comment by DarkSkull91** [comment]
I have installe the 3.2.2 version

**Comment by AbandonedCart** [comment]
That is the newest Google Play version, but keep in mind the Play builds are notoriously slower.

**Comment by DarkSkull91** [comment]
I have installed the 3.2.2 version but the problem is also there and the version on this repo can't install on my phone.

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/wiki#reporting-issues
