### ISSUE TITLE
[Bug]: encryption error

### ISSUE THREAD

**Issue by eripai** [HiddenRamblings/TagMo#581]
### Issue Description

when I scan a blank tag on the foomiibo catalog, I get an error saying failed to decrypt tag data. the nfc scanner on my phone is fine, and the chip itself works. I don't understand why it's even trying to decrypt data, anyway. shouldn't it be encrypting it ? please help me !

### Logcat Output

```shell
TagMo - #420566f4
Android S (12)
2.67 GB RAM
Installed by publish

--------- beginning of main
09-30 10:34:16.882 17709 18151 W Exception: java.lang.Exception: Failed to decrypt tag data
09-30 10:34:16.882 17709 18151 W
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/HiddenRamblings/TagMo/commit/903fd25a9775a807ef099e492d73f25f0d052894
