### ISSUE TITLE
[Feature]: Being able to use the mobile device as an amibo

### ISSUE THREAD

**Issue by Pegoku** [HiddenRamblings/TagMo#599]
### Feature Explanation

I would like to be able to use my phone as an amibo, and without the need to write it to an nfc card, i.e. select an amibo from the phone and then bring it closer to the controller so that the game detects it as an amibo

### Usage Confirmation

- [X] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
https://tagmo.gitlab.io/?s=emulating

**Comment by ThatOneOcto** [comment]
and how would you use nfcfgate to emulate the amiibo
