### ISSUE TITLE
Galaxy Avant "can't decrypt tag" 2.4.3

### ISSUE THREAD

**Issue by OmegaX01** [HiddenRamblings/TagMo#62]
Have the everything loaded and checked my tags are 215. When I have no tag loaded it is able to read the tag as empty. Yet when I try to write  (auto) I get the message "failed to decrypt tag"

Any suggestions would be greatly appreciated.

**Comment by HiddenRambler** [comment]
Most likley cause is you have a corrupted or invalid file. can you use a hex editor and past the first few bytes of the file?

**Comment by OmegaX01** [comment]
Yeah it was a bad set of tags. Found a different download site and those work. Thanks for the help.
