### ISSUE TITLE
Ver 2.5 package appears to be corrupt

### ISSUE THREAD

**Issue by raindog14** [HiddenRamblings/TagMo#64]
Downloads fine, installation says appears to be corrupt. 
![screenshot_20170801-193115](https://user-images.githubusercontent.com/26898198/28823417-02c741f4-76f0-11e7-8fd1-25261fc3ccc0.png)

**Comment by Bombastisch** [comment]
What android version do you use? Or try to redownload the apk and reboot your phone and try again.

I was able to install the app without any issues.

**Comment by raindog14** [comment]
Download it 5 times, all tbe same. I'll try on a different phone am using an xperia xa ultra

**Comment by raindog14** [comment]
Update, installs fine on my other phone. I tried uninstalling the app on the xa ultra and installed the new one, that worked. Seems like the app warnings were just off.
