### ISSUE TITLE
Force Software Layer

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#659]
Hello I hope this information proves useful but about a month ago I submitted some bug reports and you said it would be fixed by converting to a new system (sorry I didn't understand) but today I am still having issues.  I have reset the cache and everything for TagMo and it was still happening but then I decided to try clicking Force Software Layer and it all works much better now.

I don't know if telling you this helps but I thought it best to share that I found a solution thank you.

**Comment by AbandonedCart** [comment]
It was added for that reason.

**Comment by AbandonedCart** [comment]
It's based on manufacturer, not region. Asus, OnePlus, Huawei, and Oppo are some of the more common ones.
