### ISSUE TITLE
[Issue]: Not saved in folder

### ISSUE THREAD

**Issue by HectorZaGa** [HiddenRamblings/TagMo#662]
### Issue Description

After having installed the application and selected the folder, I enter the Foomiibo digital library and "save" an Amiibo, however, the bin file does not appear in the selected folder, and I have searched all over my cell phone and I cannot find it .

### Logcat Output

```shell
No logcat
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
That's by design. It will still be available in TagMo.
