### ISSUE TITLE
[Issue]: Editing Properties Not Saving

### ISSUE THREAD

**Issue by AlphaxHax** [HiddenRamblings/TagMo#670]
### Issue Description

I have tried a few different Amiibo so far including King K. Rool, Bowser, Mario, Pikachu and some others. When ever I press edit properties and change anything then press save it just does not save. Re-opening the panel shows no change and same with writing, maybe I am stupid and missing something but I dont know.

### Logcat Output

```shell
I don't know what to put here.
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Extension of https://github.com/HiddenRamblings/TagMo/issues/514
