### ISSUE TITLE
[Issue]: cannot see all options when scanning an amiibo or ntag with an amiibo

### ISSUE THREAD

**Issue by Uriel022** [HiddenRamblings/TagMo#671]
### Issue Description

What happens is that when you scan an amiibo or a ntag with an amiibo, when the mobile is vertical, not all the options appear, but if you put it horizontally, what happens is that you don't see anything, you only see the image of the character and you cannot access any of the options offered to you when scanning the amiibo

### Logcat Output

```shell
What happens is that when you scan an amiibo or a ntag with an amiibo, when the mobile is vertical, not all the options appear, but if you put it horizontally, what happens is that you don't see anything, you only see the image of the character and you cannot access any of the options offered to you when scanning the amiibo
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Please make sure to include a log in the log field. This is why it specifically states that it is not meant to paste the description.
