### ISSUE TITLE
Randomize Serial Number with duplicates

### ISSUE THREAD

**Issue by Aleksxz** [HiddenRamblings/TagMo#676]
### Feature Explanation

Hello.

When I try to use the "duplicate with random serial" method for N2Elite, I can only start from the beginning of the banks, wich wipe the previous amiibo saved.
I tried to randomize serial on N2 Elite official app or Ally, but it doesn't work anymore for an obscure reason (probably a limited amount) with the error "Randomizing serial failed !".

So my suggestion is : when you want to start a duplication with randomized amiibo, you can set it to start at the 50th bank so you can preserve the previous one from wiping.

Or maybe try to find a fix for the error message, it seems like a lot of people have the same issue with n2 elite.

I greatly appreciate your insane work, and I hope you keep this app updated because you're our only hope. With the release of TotK, people will start to use their n2 elite again.

### Usage Confirmation

- [X] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
Continuation of 674
