### ISSUE TITLE
[Feature]: The ability to move that NFC circle

### ISSUE THREAD

**Issue by thatmagicstore** [HiddenRamblings/TagMo#682]
### Feature Explanation

It's in the way when trying to edit amiibo. Just give me the ability to set it to a different location or possibly remove it.

### Usage Confirmation

- [X] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
It's been restricted to the main browser only. This also means that using manual scan for an N2 will require leaving the N2 screen to open it, but whatever.
