### ISSUE TITLE
Wolf link editor not working

### ISSUE THREAD

**Issue by HiddenRambler** [HiddenRamblings/TagMo#69]
@jmh363905 reports wolf link editor is not working (#66).

**Comment by HiddenRambler** [comment]
@jmh363905 could you check the latest release a few minutes ago?

**Comment by jmh363905** [comment]
The new version fixed it.  I was still using the last one you told me to try.  Checked this morning and there wasn't a 2.5.1 yet.

**Comment by HiddenRambler** [comment]
Yup. just released it hot off the compiler ;).
