### ISSUE TITLE
[Issue]: amiibo creation has stopped working

### ISSUE THREAD

**Issue by Billbobbybill** [HiddenRamblings/TagMo#693]
### Issue Description

My last issue was marked as resolved, but the issue is still here. Ever since the last playstore update, I cannot write onto my blank nfc cards anymore. They were working yesterday.

### Logcat Output

```shell
Issue
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
https://github.com/HiddenRamblings/TagMo/wiki#reporting-issues
