### ISSUE TITLE
[Issue]: nfc issue not solved

### ISSUE THREAD

**Issue by Billbobbybill** [HiddenRamblings/TagMo#695]
### Issue Description

the app has updated twice but the issue has not been resolved. I cannot write or read cards anymore on the app. This happened ever since the first of the updates I named.

### Logcat Output

```shell
, the app has updated twice but the issue has not been resolved.
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Duplicate of https://github.com/HiddenRamblings/TagMo/issues/694
