### ISSUE TITLE
[Issue]: TagMo App cannot detect Crypt Keys

### ISSUE THREAD

**Issue by thedamino** [HiddenRamblings/TagMo#702]
### Issue Description

Using both the direct APK Installation from Github and the App downloaded from the Play Store, the ability to select the location of the Cryto Keys appears to do nothing. The device I'm using in the Samsung Galaxy A51 on OneUI 5.1. I select the option to locate the BIN files, and have tried both selecting the individual files, and pressing and holding to multi-select files, neither allows the files to be detected by the app. I noted the Warning to not have the files in the Root Download folder, and had them in a Sub-Directory, as I figured this may still be affected by Permissions, I copied the files to an SD-Card, with the same issue. 

I did ensure that in the app Preferences, I have given the TagMo "All Folder" access. I tried to find an earlier build through Github, but it looks like all old builds are only Archived by enthusiasts. Any assistance on the current build would be appreciated. 

### Logcat Output

```shell
No Unfixed key!
No Locked key!
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
They can't be loaded directly from the download folder.
