### ISSUE TITLE
[Feature]: Enable NFC Emulation

### ISSUE THREAD

**Issue by JanB97** [HiddenRamblings/TagMo#704]
### Feature Explanation

Apps like NFC Tools Pro and NDEF Tag Emulator allow the emulation of a NFC tag directly from your phone. 
This would allow to scan a amiibo from your phone without writing to a tag. 
Would be a cool feature to add.

### Usage Confirmation

- [X] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
They emulate payment cards, not unlike Google Wallet, Samsung Pay, and Apple Pay. NTAG215 cannot be emulated. It is requested nearly every other day, though, which is why a section about it has been added to the instructions.
