### ISSUE TITLE
The tagmo catalog is not working

### ISSUE THREAD

**Issue by ravage007** [HiddenRamblings/TagMo#707]
I have no idea why but the catalog is not working I have spent a couple days trying to troubleshoot as Myself by uninstalling reinstalling trying different devices

**Comment by AbandonedCart** [comment]
Unfortunately, we are unable to accept issues that attempt to circumvent the requirements. If you would like to submit this issue, please use the appropriate template and include the required information. See https://github.com/HiddenRamblings/TagMo/wiki#reporting-issues for details.
