### ISSUE TITLE
[Feature]: themes

### ISSUE THREAD

**Issue by Gabriele2355** [HiddenRamblings/TagMo#714]
### Feature Explanation

it would be nice that you can create custom tagmo themes

### Usage Confirmation

- [x] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
Are you talking about color schemes?

**Comment by Gabriele2355** [comment]
wallpapers

**Comment by AbandonedCart** [comment]
That requires a significant amount of overhead and a lot of people are already struggling just to load the lists.
