### ISSUE TITLE
[Issue]: bluetooth connection problem with Amiloop

### ISSUE THREAD

**Issue by Vorffeed** [HiddenRamblings/TagMo#722]
### Issue Description

As much as I try to pair the amiilop, all the time it refuses the connection is there any way to connect it to be able to write on the amiibos on the device?

**Comment by AbandonedCart** [comment]
The instructions for connecting are posted at https://tagmo.gitlab.io/keyfobs.html

**Comment by Vorffeed** [comment]
I have looked in the instructions it says that you can connect, but I get an error I have a Redmi note 9 pro, with other app I have no problems to connect the AmiLoop and when I try to connect I get this 
![Screenshot_2023-11-18-13-13-13-656_com hiddenramblings tagmo eightbit](https://github.com/HiddenRamblings/TagMo/assets/10000442/575cf4fd-ef35-4747-9bac-fcc3d9d05314)
![Screenshot_2023-11-18-10-22-44-311_com hiddenramblings tagmo eightbit](https://github.com/HiddenRamblings/TagMo/assets/10000442/67315257-71ee-4c08-8171-865351fa9e21)

and it does not connect, I have tried to install it on my mother's phone which is a redmi note 9 and she connects without problems ><

I have used lodgcat reader to see if I could find the bug, I don't know if it will be in this piece because it shows me a lot of information and I don't understand how to make it monitor only the tagmo ><

`:31:33.090  3740  3740 I KeyguardIndicationInjector: handleChargeTextAnimation: false;powerPluggedIn=true
11-18 12:31:33.097  1676  5186 I WindowManagerService: Physical orientation not applied, rotation=0
11-18 12:31:33.248  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:33.448  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:33.650  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:33.851  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:33.876  1676  2007 I BatteryService: current mPlugType1current mHealthInfo.batteryLevel40current mHealthInfo.batteryTemperature372
11-18 12:31:33.880  5695  5695 I BatteryInfoReceiver: ACTION_BATTERY_CHANGED
11-18 12:31:33.886  5695  5695 I PowerNoticeUI: handleBatteryChanged oldPlugType 1 mPlugType 1 oldBatteryLevel 40 mBatteryLevel 40 temperature 372
11-18 12:31:34.051  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:34.130  1676  7576 I WindowManagerService: Physical orientation not applied, rotation=0
11-18 12:31:34.252  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:34.453  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:34.456  1676  7576 W InputManager-JNI: Input channel object '3fd1ede PopupWindow:a8515f1 (client)' was disposed without first being removed with the input manager!
11-18 12:31:34.653  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:34.670  3384  3826 I BtGatt.ScanManager: msg.what = 6
11-18 12:31:34.670  1676  3270 I MiuiNetworkPolicy: updateUidState uid = 10196, uidState = 5
11-18 12:31:34.854  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:35.055  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:35.101  1676  7576 W InputManager-JNI: Input channel object '878ec5 com.hiddenramblings.tagmo.eightbit/com.hiddenramblings.tagmo.BrowserActivity (client)' was disposed without first being removed with the input manager!
11-18 12:31:35.178  3384  4066 I bt_stack: [INFO:gatt_api.cc(1239)] GATT_Register 7cba8101-ce13-4f4b-6e6b-8f0a38a7cf80
11-18 12:31:35.178  3384  4066 I bt_stack: [INFO:gatt_api.cc(1260)] allocated gatt_if=10
11-18 12:31:35.185  3384  4066 I bt_stack: [INFO:gatt_api.cc(1429)] GATT_Connect gatt_if=10, address=e4:a2:5d:9f:01:d9 is_direct 1
11-18 12:31:35.187  1043  1043 I vendor.qti.bluetooth@1.0-uart_transport: ## userial_vendor_ioctl: UART Flow Off
11-18 12:31:35.188  1043  1043 I vendor.qti.bluetooth@1.0-uart_transport: ## userial_vendor_set_baud: 17
11-18 12:31:35.189  1043  1043 I vendor.qti.bluetooth@1.0-uart_transport: SetBaudRate: in BOTHER
11-18 12:31:35.189  1043  1043 I vendor.qti.bluetooth@1.0-uart_transport: ## userial_vendor_ioctl: UART Flow On
11-18 12:31:35.189  1043  1043 I vendor.qti.bluetooth@1.0-ibs_handler: DeviceWakeUp: Writing IBS_WAKE_IND
11-18 12:31:35.191  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_ACK: 0xFC
11-18 12:31:35.191  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Signal wack_cond_
11-18 12:31:35.193  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
11-18 12:31:35.193  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
11-18 12:31:35.210 16324 16324 E FullInputEventModel: onStartInput event aborted: ky.y: could not obtain extracted text (class ky.y)
11-18 12:31:35.256  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:35.274  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
11-18 12:31:35.321  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
11-18 12:31:35.322  1043  4063 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
11-18 12:31:35.324  3384  4066 I bt_stack: [INFO:btm_ble_connection_establishment.cc(179)] btm_ble_conn_complete BD addr e4:a2:5d:9f:01:d9 Not resolved
11-18 12:31:35.324  3384  4066 I bt_stack: [INFO:connection_manager.cc(280)] lower the scan parameters used for connecting
11-18 12:31:35.325  3384  4066 I bt_stack: [INFO:btm_ble_bgconn.cc(429)] Already connection initiated (or) No Pending connections(or) Resources of lcb are exhausted
11-18 12:31:35.325  3384  4066 W bt_btm  : btm_acl_created hci_handle=12 link_role=0  transport=2
11-18 12:31:35.325  3384  4066 I bt_stack: [INFO:btm_ble_bgconn.cc(429)] Already connection initiated (or) No Pending connections(or) Resources of lcb are exhausted
11-18 12:31:35.333  3384  4066 I bt_stack: [INFO:gatt_main.cc(1630)] gatt_data_process op_code = 2, msg_len = 2
11-18 12:31:35.333  3384  4066 I bt_stack: [INFO:gatt_sr.cc(915)] MTU request PDU with MTU size 247
11-18 12:31:35.333  3384  4066 E bt_btm  : BTM_SetBleDataLength failed, peer does not support request
11-18 12:31:35.334  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=3
11-18 12:31:35.334  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=4
11-18 12:31:35.334  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=5
11-18 12:31:35.334  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=7
11-18 12:31:35.334  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=8
11-18 12:31:35.335  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=9
11-18 12:31:35.335  3384  4066 W bt_stack: [WARNING:gatt_utils.cc(916)] Call back not found for application conn_id=10
11-18 12:31:35.335  3384  4066 E bt_btif : bta_dm_acl_change new acl connetion:count = 1
11-18 12:31:35.335  3384  4066 W bt_btif : bta_dm_acl_change info: 0x0
11-18 12:31:35.335  3384  4066 W bt_l2cap: L2CA_SetDesireRole() new:x1, disallow_switch:0
11-18 12:31:35.341  3384  4066 E bt_stack: [ERROR:bta_gattc_cache.cc(733)] bta_gattc_cache_load: can't open GATT cache file /data/misc/bluetooth/gatt_cache_e4a25d9f01d9 for reading, error: No such file or directory
11-18 12:31:35.342  3384  4066 I bt_stack: [INFO:hearing_aid.cc(1814)] GetDeviceCount: Not initialized yet
11-18 12:31:35.342  3384  4066 I bt_stack: [INFO:gatt_api.cc(903)] GATTC_Discover conn_id=0x000a, disc_type=1, s_handle=0x0001, e_handle=0xffff
11-18 12:31:35.384  1676  1676 I CompanionDeviceManagerService: onDeviceNearby(justAppeared, address = E4:A2:5D:9F:01:D9)
11-18 12:31:35.390  1676  3270 I MiuiNetworkPolicy: updateUidState uid = 1000, uidState = 0
11-18 12:31:35.415  3384  3384 I BluetoothPhonePolicy: processDeviceConnected, device=E4:A2:5D:9F:01:D9
11-18 12:31:35.416 28898 29141 W NullPointerException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattCharacteristic android.bluetooth.BluetoothGattService.getCharacteristic(java.util.UUID)' on a null object reference
11-18 12:31:35.416 28898 29141 W NullPointerException: at com.hiddenramblings.tagmo.bluetooth.GattService.setCharacteristicRX(GattService.kt:653)
11-18 12:31:35.416 28898 29141 W NullPointerException: at com.hiddenramblings.tagmo.fragment.GattSlotFragment$gattServerConn$1$onServiceConnected$1$1.onPixlServicesDiscovered(GattSlotFragment.kt:1440)
11-18 12:31:35.416 28898 29141 W NullPointerException: at com.hiddenramblings.tagmo.bluetooth.GattService$mGattCallback$1.onMtuChanged(GattService.kt:483)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.bluetooth.BluetoothGatt$1$13.run(BluetoothGatt.java:673)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.bluetooth.BluetoothGatt$1.onConfigureMTU(BluetoothGatt.java:668)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:339)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.os.Binder.execTransactInternal(Binder.java:1187)
11-18 12:31:35.416 28898 29141 W NullPointerException: at android.os.Binder.execTransact(Binder.java:1146)
11-18 12:31:35.420  3384  4066 I bt_stack: [INFO:gatt_api.cc(1566)] GATT_Disconnect conn_id=0x000a
11-18 12:31:35.421  3384  4066 I bt_stack: [INFO:bta_gattc_act.cc(652)] Local close event client_if:
11-18 12:31:35.421  3384  4066 I bt_stack:  conn_id: 10 reason: 0
11-18 12:31:35.421  3384  4066 I bt_stack: [INFO:bta_gattc_act.cc(339)] Cancel GATT client background connection
11-18 12:31:35.421  3384  4066 E bt_stack: [ERROR:bta_gattc_utils.cc(458)] bta_gattc_mark_bg_conn unable to find the bg connection mask for bd_addr=e4:a2:5d:9f:01:d9
11-18 12:31:35.421  3384  3446 E bt_btif_gattc: btif_gattc_upstreams_evt: Unhandled event (8)!
11-18 12:31:35.433 28898 28898 W RecyclerView: No adapter attached; skipping layout
11-18 12:31:35.434  4182  4182 W BluetoothEventManager: AclStateChangedHandler: activeDevice is null
11-18 12:31:35.441  3740  4013 W BluetoothEventManager: AclStateChangedHandler: activeDevice is null
11-18 12:31:35.442  3384  3446 E bt_stack: [ERROR:bta_gattc_cache.cc(696)] Unknown conn_id=0x000a
11-18 12:31:35.442  3384  3446 E BtGatt.GattService: app or callback is null
11-18 12:31:35.444  4182  4182 I AIVS    : BluetoothBase:onConnection Find device :E4:A2:5D:9F:01:D9 not exist.
11-18 12:31:35.449 28898 28898 W RecyclerView: No adapter attached; skipping layout
11-18 12:31:35.453  4182  4182 I AIVS    : BluetoothBase:onReceive: ACTION_ACL_CONNECTED,  device : BluetoothDeviceInfo{ mCurrentOpType: 2 Device Ble='AmiLoop; E4:A2:5D:9F:01:D9 vid:0xffff pid:0xffff MandatoryUpgrade:false channelStatus:0bleStatus:0 sppStatus:0 authStage:0 PowerMode:0 mBackUpMode:-1 isDeviceInfoUpdated:false authCmd:false FailedReason:0x0}
11-18 12:31:35.455 28898 28898 W IllegalAccessException: java.lang.IllegalAccessException: Bluetooth adapter unavailable!
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.hiddenramblings.tagmo.bluetooth.GattService.setCharacteristicTX(GattService.kt:668)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.hiddenramblings.tagmo.bluetooth.GattService.queueByteCharacteristic(GattService.kt:723)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.hiddenramblings.tagmo.bluetooth.GattService.setSortingMode(GattService.kt:1039)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.hiddenramblings.tagmo.fragment.GattSlotFragment$onViewCreated$2$2$1.onItemSelected(GattSlotFragment.kt:183)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.widget.AdapterView.access$300(AdapterView.java:55)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.os.Handler.handleCallback(Handler.java:938)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.os.Handler.dispatchMessage(Handler.java:99)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.os.Looper.loopOnce(Looper.java:210)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.os.Looper.loop(Looper.java:299)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at android.app.ActivityThread.main(ActivityThread.java:8319)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at java.lang.reflect.Method.invoke(Native Method)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
11-18 12:31:35.455 28898 28898 W IllegalAccessException: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
11-18 12:31:35.456  3694  8700 I SarService: Receiver polling >>>> Change receiver mode: off
11-18 12:31:35.458  1676  3270 I MiuiNetworkPolicy: updateUidState uid = 1002, uidState = 0
11-18 12:31:35.458  1676  3270 I MiuiNetworkPolicy: updateUidState uid = 10196, uidState = 5
11-18 12:31:35.461  1676  2027 I ActivityManager: Start proc 29227:com.google.android.projection.gearhead:shared/u0a198 for broadcast {com.google.android.projection.gearhead/com.google.android.apps.auto.wireless.bluetooth.WifiBluetoothReceiver} caller=com.android.bluetooth
11-18 12:31:35.497 29227 29227 I gearhead:share: Using CollectorTypeCC GC.
11-18 12:31:35.511  3384  4066 I bt_stack: [INFO:gatt_main.cc(1630)] gatt_data_process op_code = 17, msg_len = 13
11-18 12:31:35.511  3384  4066 W bt_stack: [WARNING:gatt_cl.cc(1288)] ATT - clcb already not in use, ignoring response`
