### ISSUE TITLE
[Feature]: The Flipper-Zero nfc files should contain the correct password so that they can be run directly on the Flipper-Zero.

### ISSUE THREAD

**Issue by danizwam** [HiddenRamblings/TagMo#732]
### Feature Explanation

For the first time in months, I've been working with Amiibos on the Flipper-Zero and today I realized that NFC files now have to contain a password in order to be correctly emulated by the Flipper-Zero and recognized by the Switch. 

To be able to use the NFC files generated by TagMo on the Flipper-Zero, there are various options. There are several ways to convert them directly on the Flipper-Zero, but all of them are very complicated and require either the Switch and its NFC reader or a real Amiibo. If the password found is incorrect, there may be problems. If you use an external Amiibo and its password, the NFC is encrypted with it (but this ensures that the NFC Amiibo is no longer unique). Another option is to use an external tool to convert the NFC on the PC. I found the last option to be the easiest and it always worked perfectly.

The password for the Amiibos is generated from the 7 bytes of the UID and stored in page 133.
A default value is written to page 134.

On this repository https://github.com/turbospok/Flipper-NTAG215-password-converter there is a Python script that can be used to convert the NFC files so that they run on the Flipper-Zero.

I was able to convert the NFC files generated by TagMo with this tool. It would be great if the NFC files generated by TagMo contained the password and could be run directly on the Flipper-Zero.

### Usage Confirmation

- [X] I confirm this is a request for a new feature, not an issue

**Comment by AbandonedCart** [comment]
Looks like it's the second version of their format, so the real question is if adding the password to everything will break the first or if I need to also check for the version.

**Comment by AbandonedCart** [comment]
I meant there are apparently two iterations of the flipper firmware.

**Comment by AbandonedCart** [comment]
I should have this fixed tonight. I added a note with the changes, but want to verify before publishing with everything being live.

**Comment by AbandonedCart** [comment]
Hopefully I did that right. First 3 bytes of page 0, all of page 4 as the uid. Xor a bunch of stuff and write to page 133. Inject predefined values in page 134.

**Comment by AbandonedCart** [comment]
Their documentation said it was 3 bytes from page 0, all 4 from page 1. That sounds like just pages 3 and 4.

**Comment by AbandonedCart** [comment]
If you can't already tell, I don't actually have a Flipper to verify any of this.

**Comment by AbandonedCart** [comment]
Just so it makes sense if you read through the code, the reason I dropped the copy entirely is a page is 4 bytes, so copyOf(4) is essentially just the entire page.

**Comment by AbandonedCart** [comment]
Awesome. Thanks. Let me know if you run into any other issues.
