### ISSUE TITLE
[Issue]: Can not scroll in Bluetooth window. 

### ISSUE THREAD

**Issue by ottoxgam** [HiddenRamblings/TagMo#734]
### Issue Description

I am unable to scroll through the enumerated Bluetooth devices while in the Bluetooth window. This issue is not affected by portrait vs landscape. 

Video showing the issue:
https://jmp.sh/s/6d1QcM2eG0sfa9jLg9dN

### Logcat Output

```shell
ImeTracker
com.hiddenramblings.tagmo.eightbit:TagMo:ff916a96: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_FROM_VIEW

ImeTracker
com.hiddenramblings.tagmo.eightbit:TagMo:ff916a96: onFailed at PHASE_CLIENT_VIEW_SERVED

ImeTracker
com.hiddenramblings.tagmo.eightbit:TagMo:b954826f: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_FROM_VIEW
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Google Play or GitHub?

**Comment by ottoxgam** [comment]
TagMo 4.2.2 (GitHub Release) #d1c1d16

**Comment by AbandonedCart** [comment]
This should be fixed in the newest build.

**Comment by ottoxgam** [comment]
Thank you! Works as expected!

**Comment by AbandonedCart** [comment]
Great! Thanks for the report.
