### ISSUE TITLE
Package appears to be corrupt?

### ISSUE THREAD

**Issue by scottjl** [HiddenRamblings/TagMo#75]
This is on a LG V20 running 7.0, any help? Thanks in advance! this is 2.5 or 2.5.1.

**Comment by Bombastisch** [comment]
Please uninstall Tagmo, reboot your phone, and install the latest version of Tagmo ("Fixes"). If it works please let me know. :)

**Comment by scottjl** [comment]
Ah, sorry, that fixed it. I had 2.4.3 installed and for some reason trying to upgrade it told me 2.5.x was corrupt. Uninstalling 2.4.3 first allowed 2.5.1 to install without any error message.
