### ISSUE TITLE
Ability to update stats on existing amiibo?

### ISSUE THREAD

**Issue by Ekim0789** [HiddenRamblings/TagMo#8]
Is there any way to update stats of an already programmed NFC chip or real amiibo? If not is this a planned future addition? Thanks.

**Comment by LinkofHyrule89** [comment]
You should probably be more specific than this. The app already has ssb editing and a version for editing Wolf Link.

**Comment by JimmyMultani** [comment]
@LinkofHyrule89, I think @Ekim0789 is asking whether you can write directly onto the amiibo.

**Comment by Bombastisch** [comment]
If you want to edit the SSB data of a SSB-amiibo, you can do that easily. Just scan the amiibo, click on "Edit SSB", edit the attributes and then restore the changes to your existing amiibo.


Did this answer your question?

**Comment by Bombastisch** [comment]
Closing this issue, because it doesnt seem like I will get any response soon. If there are still any issues, open a new issue thread. Thank you! :)
