### ISSUE TITLE
Browser Folder Navigation

### ISSUE THREAD

**Issue by North101** [HiddenRamblings/TagMo#87]
https://github.com/HiddenRamblings/TagMo/tree/folder_navigation

Features:
1. Default dir /tagmo
2. Remember which folder
3. Option for finding files from current folder or every subfolder

Preview:
![screenshot_20170904-194947](https://user-images.githubusercontent.com/1031451/30036334-45669616-91aa-11e7-9346-cc2707fb22be.png)
![screenshot_20170904-194943](https://user-images.githubusercontent.com/1031451/30036335-456afd6e-91aa-11e7-855e-6bf68e868787.png)

**Comment by Bombastisch** [comment]
Love it, great idea! I am mainly using the search option, but i guess with that you can filter out certain amiibos more easily!

**Comment by North101** [comment]
@Bombastisch its mainly to let people select where files are found from. Its also good UX as it shows which root folder is being read from

**Comment by residentevil789** [comment]
It works well though it somehow reads internal memory instead of external

**Comment by North101** [comment]
@residentevil789 are you talking about my unreleased branch?
Can you explain what you mean by "though it somehow reads internal memory instead of external"

**Comment by residentevil789** [comment]
Well I assume it would read the external memory card for the .bin files but instead decided to read the internal memory of my phone. I'm using the 2.5.2 version and weirdly enough i have no idea how to make it show pictures as well

**Comment by North101** [comment]
@residentevil789 external memory is in the works. The pictures will be in the next release

**Comment by residentevil789** [comment]
ah. Can't wait for the next release then 👍

**Comment by HiddenRambler** [comment]
@North101  this is good. I usualy end up files in the download folder and have to copy them to tagmo before i can use it. This will make life easier.

I take it this isnt ready to merge yet?

**Comment by North101** [comment]
@HiddenRambler its like 95% ready. Need to add keep settings when rotating

**Comment by Bombastisch** [comment]
can be closed?
