### ISSUE TITLE
Save Icon on ImageView doesnt work

### ISSUE THREAD

**Issue by Bombastisch** [HiddenRamblings/TagMo#89]
The save icon on imageview actually doesnt save the picture of the amiibo.

**Comment by Bombastisch** [comment]
(version 2.6)

**Comment by North101** [comment]
Well its fixed in the dev/next version. Wasn't expecting a release before the last change was merged (but also didn't know something was commented out)

**Comment by HiddenRambler** [comment]
@North101 apoloies. I wasn't aware tha t merge was pending. I can do another update if you let me know when. 

perhaps we should come release process. Create a new Issue for atleast a day when a new release is needed/about to be released?

**Comment by North101** [comment]
@HiddenRambler no problem, was my mistake anyway.

I'm fine with the current build now for my changes.

**Comment by HiddenRambler** [comment]
I'll do a new release tonight then.

**Comment by Bombastisch** [comment]
Thank you for the quick responses! ;)

**Comment by HiddenRambler** [comment]
Release 2.6.1 done.
