### ISSUE TITLE
Storing lookup values in sqlite

### ISSUE THREAD

**Issue by HiddenRambler** [HiddenRamblings/TagMo#93]
@North101 Would it make sense to store lookup values (amiibo data, powertag keys) in a sqlite db? Perhaps using a library like Room https://developer.android.com/topic/libraries/architecture/room.html?

We would probably need to initialise it on the first install from a static xml but afterwards the lookups and loading of the app would be more efficient.

**Comment by North101** [comment]
I considered that for the amiibo data but I think its easier to just parse the json. Its very very quick to parse so I don't think it'll be noticeably different.

**Comment by HiddenRambler** [comment]
I suppose you're right. We'll open this again if we get complaints on slower phones.
