### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by HiddenRambler** [HiddenRamblings/TagMo#95]
@North101,

I will be going on a holiday and would not be able to do much work on TagMo for atleast a month. I think it would be a good idea if you are able to do releases as well. I'm willing to give you the android signing key for TagMo. Please let me know if you're ok with doing releases. It's not much work to be honest just creating a signed release build and uploading the the file to github with a small note on changes.

**Comment by AbandonedCart** [comment]
A generic key has been generated for the experimental branch. While it does require uninstalling older versions to switch to the new key, there have been enough changes between the last official release and the experimental version to justify it.

Closing this for the sake of minimizing the open issues.
